
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Hospital` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Hospital
 * 
 */
export type HospitalModel = runtime.Types.Result.DefaultSelection<Prisma.$HospitalPayload>

export type AggregateHospital = {
  _count: HospitalCountAggregateOutputType | null
  _avg: HospitalAvgAggregateOutputType | null
  _sum: HospitalSumAggregateOutputType | null
  _min: HospitalMinAggregateOutputType | null
  _max: HospitalMaxAggregateOutputType | null
}

export type HospitalAvgAggregateOutputType = {
  lat: number | null
  lng: number | null
}

export type HospitalSumAggregateOutputType = {
  lat: number | null
  lng: number | null
}

export type HospitalMinAggregateOutputType = {
  id: string | null
  name: string | null
  code: string | null
  sizeLevel: $Enums.HospitalSizeLevel | null
  sapLevel: $Enums.HospitalSapLevel | null
  affiliation: $Enums.HospitalAffiliation | null
  lat: number | null
  lng: number | null
}

export type HospitalMaxAggregateOutputType = {
  id: string | null
  name: string | null
  code: string | null
  sizeLevel: $Enums.HospitalSizeLevel | null
  sapLevel: $Enums.HospitalSapLevel | null
  affiliation: $Enums.HospitalAffiliation | null
  lat: number | null
  lng: number | null
}

export type HospitalCountAggregateOutputType = {
  id: number
  name: number
  code: number
  sizeLevel: number
  sapLevel: number
  affiliation: number
  lat: number
  lng: number
  _all: number
}


export type HospitalAvgAggregateInputType = {
  lat?: true
  lng?: true
}

export type HospitalSumAggregateInputType = {
  lat?: true
  lng?: true
}

export type HospitalMinAggregateInputType = {
  id?: true
  name?: true
  code?: true
  sizeLevel?: true
  sapLevel?: true
  affiliation?: true
  lat?: true
  lng?: true
}

export type HospitalMaxAggregateInputType = {
  id?: true
  name?: true
  code?: true
  sizeLevel?: true
  sapLevel?: true
  affiliation?: true
  lat?: true
  lng?: true
}

export type HospitalCountAggregateInputType = {
  id?: true
  name?: true
  code?: true
  sizeLevel?: true
  sapLevel?: true
  affiliation?: true
  lat?: true
  lng?: true
  _all?: true
}

export type HospitalAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Hospital to aggregate.
   */
  where?: Prisma.HospitalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hospitals to fetch.
   */
  orderBy?: Prisma.HospitalOrderByWithRelationInput | Prisma.HospitalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HospitalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hospitals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hospitals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Hospitals
  **/
  _count?: true | HospitalCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HospitalAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HospitalSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HospitalMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HospitalMaxAggregateInputType
}

export type GetHospitalAggregateType<T extends HospitalAggregateArgs> = {
      [P in keyof T & keyof AggregateHospital]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHospital[P]>
    : Prisma.GetScalarType<T[P], AggregateHospital[P]>
}




export type HospitalGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HospitalWhereInput
  orderBy?: Prisma.HospitalOrderByWithAggregationInput | Prisma.HospitalOrderByWithAggregationInput[]
  by: Prisma.HospitalScalarFieldEnum[] | Prisma.HospitalScalarFieldEnum
  having?: Prisma.HospitalScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HospitalCountAggregateInputType | true
  _avg?: HospitalAvgAggregateInputType
  _sum?: HospitalSumAggregateInputType
  _min?: HospitalMinAggregateInputType
  _max?: HospitalMaxAggregateInputType
}

export type HospitalGroupByOutputType = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat: number | null
  lng: number | null
  _count: HospitalCountAggregateOutputType | null
  _avg: HospitalAvgAggregateOutputType | null
  _sum: HospitalSumAggregateOutputType | null
  _min: HospitalMinAggregateOutputType | null
  _max: HospitalMaxAggregateOutputType | null
}

type GetHospitalGroupByPayload<T extends HospitalGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HospitalGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HospitalGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HospitalGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HospitalGroupByOutputType[P]>
      }
    >
  >



export type HospitalWhereInput = {
  AND?: Prisma.HospitalWhereInput | Prisma.HospitalWhereInput[]
  OR?: Prisma.HospitalWhereInput[]
  NOT?: Prisma.HospitalWhereInput | Prisma.HospitalWhereInput[]
  id?: Prisma.StringFilter<"Hospital"> | string
  name?: Prisma.StringFilter<"Hospital"> | string
  code?: Prisma.StringFilter<"Hospital"> | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFilter<"Hospital"> | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFilter<"Hospital"> | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFilter<"Hospital"> | $Enums.HospitalAffiliation
  lat?: Prisma.FloatNullableFilter<"Hospital"> | number | null
  lng?: Prisma.FloatNullableFilter<"Hospital"> | number | null
  lrStatus?: Prisma.XOR<Prisma.LrStatusNullableScalarRelationFilter, Prisma.LrStatusWhereInput> | null
  orStat?: Prisma.XOR<Prisma.OrStatNullableScalarRelationFilter, Prisma.OrStatWhereInput> | null
  icuWards?: Prisma.ICUWardListRelationFilter
  ipdWards?: Prisma.IPDWardListRelationFilter
  waitingTimes?: Prisma.WaitingTimeListRelationFilter
  visitCounts?: Prisma.VisitCountListRelationFilter
}

export type HospitalOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  sizeLevel?: Prisma.SortOrder
  sapLevel?: Prisma.SortOrder
  affiliation?: Prisma.SortOrder
  lat?: Prisma.SortOrderInput | Prisma.SortOrder
  lng?: Prisma.SortOrderInput | Prisma.SortOrder
  lrStatus?: Prisma.LrStatusOrderByWithRelationInput
  orStat?: Prisma.OrStatOrderByWithRelationInput
  icuWards?: Prisma.ICUWardOrderByRelationAggregateInput
  ipdWards?: Prisma.IPDWardOrderByRelationAggregateInput
  waitingTimes?: Prisma.WaitingTimeOrderByRelationAggregateInput
  visitCounts?: Prisma.VisitCountOrderByRelationAggregateInput
}

export type HospitalWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  code?: string
  AND?: Prisma.HospitalWhereInput | Prisma.HospitalWhereInput[]
  OR?: Prisma.HospitalWhereInput[]
  NOT?: Prisma.HospitalWhereInput | Prisma.HospitalWhereInput[]
  name?: Prisma.StringFilter<"Hospital"> | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFilter<"Hospital"> | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFilter<"Hospital"> | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFilter<"Hospital"> | $Enums.HospitalAffiliation
  lat?: Prisma.FloatNullableFilter<"Hospital"> | number | null
  lng?: Prisma.FloatNullableFilter<"Hospital"> | number | null
  lrStatus?: Prisma.XOR<Prisma.LrStatusNullableScalarRelationFilter, Prisma.LrStatusWhereInput> | null
  orStat?: Prisma.XOR<Prisma.OrStatNullableScalarRelationFilter, Prisma.OrStatWhereInput> | null
  icuWards?: Prisma.ICUWardListRelationFilter
  ipdWards?: Prisma.IPDWardListRelationFilter
  waitingTimes?: Prisma.WaitingTimeListRelationFilter
  visitCounts?: Prisma.VisitCountListRelationFilter
}, "id" | "code">

export type HospitalOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  sizeLevel?: Prisma.SortOrder
  sapLevel?: Prisma.SortOrder
  affiliation?: Prisma.SortOrder
  lat?: Prisma.SortOrderInput | Prisma.SortOrder
  lng?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.HospitalCountOrderByAggregateInput
  _avg?: Prisma.HospitalAvgOrderByAggregateInput
  _max?: Prisma.HospitalMaxOrderByAggregateInput
  _min?: Prisma.HospitalMinOrderByAggregateInput
  _sum?: Prisma.HospitalSumOrderByAggregateInput
}

export type HospitalScalarWhereWithAggregatesInput = {
  AND?: Prisma.HospitalScalarWhereWithAggregatesInput | Prisma.HospitalScalarWhereWithAggregatesInput[]
  OR?: Prisma.HospitalScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HospitalScalarWhereWithAggregatesInput | Prisma.HospitalScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Hospital"> | string
  name?: Prisma.StringWithAggregatesFilter<"Hospital"> | string
  code?: Prisma.StringWithAggregatesFilter<"Hospital"> | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelWithAggregatesFilter<"Hospital"> | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelWithAggregatesFilter<"Hospital"> | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationWithAggregatesFilter<"Hospital"> | $Enums.HospitalAffiliation
  lat?: Prisma.FloatNullableWithAggregatesFilter<"Hospital"> | number | null
  lng?: Prisma.FloatNullableWithAggregatesFilter<"Hospital"> | number | null
}

export type HospitalCreateInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusCreateNestedOneWithoutHospitalInput
  orStat?: Prisma.OrStatCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardCreateNestedManyWithoutHospitalInput
  ipdWards?: Prisma.IPDWardCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountCreateNestedManyWithoutHospitalInput
}

export type HospitalUncheckedCreateInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusUncheckedCreateNestedOneWithoutHospitalInput
  orStat?: Prisma.OrStatUncheckedCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardUncheckedCreateNestedManyWithoutHospitalInput
  ipdWards?: Prisma.IPDWardUncheckedCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeUncheckedCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountUncheckedCreateNestedManyWithoutHospitalInput
}

export type HospitalUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUpdateOneWithoutHospitalNestedInput
  orStat?: Prisma.OrStatUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUpdateManyWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUpdateManyWithoutHospitalNestedInput
}

export type HospitalUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUncheckedUpdateOneWithoutHospitalNestedInput
  orStat?: Prisma.OrStatUncheckedUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUncheckedUpdateManyWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUncheckedUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUncheckedUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUncheckedUpdateManyWithoutHospitalNestedInput
}

export type HospitalCreateManyInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
}

export type HospitalUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type HospitalUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type HospitalCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  sizeLevel?: Prisma.SortOrder
  sapLevel?: Prisma.SortOrder
  affiliation?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
}

export type HospitalAvgOrderByAggregateInput = {
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
}

export type HospitalMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  sizeLevel?: Prisma.SortOrder
  sapLevel?: Prisma.SortOrder
  affiliation?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
}

export type HospitalMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  sizeLevel?: Prisma.SortOrder
  sapLevel?: Prisma.SortOrder
  affiliation?: Prisma.SortOrder
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
}

export type HospitalSumOrderByAggregateInput = {
  lat?: Prisma.SortOrder
  lng?: Prisma.SortOrder
}

export type HospitalScalarRelationFilter = {
  is?: Prisma.HospitalWhereInput
  isNot?: Prisma.HospitalWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type EnumHospitalSizeLevelFieldUpdateOperationsInput = {
  set?: $Enums.HospitalSizeLevel
}

export type EnumHospitalSapLevelFieldUpdateOperationsInput = {
  set?: $Enums.HospitalSapLevel
}

export type EnumHospitalAffiliationFieldUpdateOperationsInput = {
  set?: $Enums.HospitalAffiliation
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type HospitalCreateNestedOneWithoutLrStatusInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutLrStatusInput, Prisma.HospitalUncheckedCreateWithoutLrStatusInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutLrStatusInput
  connect?: Prisma.HospitalWhereUniqueInput
}

export type HospitalUpdateOneRequiredWithoutLrStatusNestedInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutLrStatusInput, Prisma.HospitalUncheckedCreateWithoutLrStatusInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutLrStatusInput
  upsert?: Prisma.HospitalUpsertWithoutLrStatusInput
  connect?: Prisma.HospitalWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HospitalUpdateToOneWithWhereWithoutLrStatusInput, Prisma.HospitalUpdateWithoutLrStatusInput>, Prisma.HospitalUncheckedUpdateWithoutLrStatusInput>
}

export type HospitalCreateNestedOneWithoutIcuWardsInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutIcuWardsInput, Prisma.HospitalUncheckedCreateWithoutIcuWardsInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutIcuWardsInput
  connect?: Prisma.HospitalWhereUniqueInput
}

export type HospitalUpdateOneRequiredWithoutIcuWardsNestedInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutIcuWardsInput, Prisma.HospitalUncheckedCreateWithoutIcuWardsInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutIcuWardsInput
  upsert?: Prisma.HospitalUpsertWithoutIcuWardsInput
  connect?: Prisma.HospitalWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HospitalUpdateToOneWithWhereWithoutIcuWardsInput, Prisma.HospitalUpdateWithoutIcuWardsInput>, Prisma.HospitalUncheckedUpdateWithoutIcuWardsInput>
}

export type HospitalCreateNestedOneWithoutIpdWardsInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutIpdWardsInput, Prisma.HospitalUncheckedCreateWithoutIpdWardsInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutIpdWardsInput
  connect?: Prisma.HospitalWhereUniqueInput
}

export type HospitalUpdateOneRequiredWithoutIpdWardsNestedInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutIpdWardsInput, Prisma.HospitalUncheckedCreateWithoutIpdWardsInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutIpdWardsInput
  upsert?: Prisma.HospitalUpsertWithoutIpdWardsInput
  connect?: Prisma.HospitalWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HospitalUpdateToOneWithWhereWithoutIpdWardsInput, Prisma.HospitalUpdateWithoutIpdWardsInput>, Prisma.HospitalUncheckedUpdateWithoutIpdWardsInput>
}

export type HospitalCreateNestedOneWithoutOrStatInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutOrStatInput, Prisma.HospitalUncheckedCreateWithoutOrStatInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutOrStatInput
  connect?: Prisma.HospitalWhereUniqueInput
}

export type HospitalUpdateOneRequiredWithoutOrStatNestedInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutOrStatInput, Prisma.HospitalUncheckedCreateWithoutOrStatInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutOrStatInput
  upsert?: Prisma.HospitalUpsertWithoutOrStatInput
  connect?: Prisma.HospitalWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HospitalUpdateToOneWithWhereWithoutOrStatInput, Prisma.HospitalUpdateWithoutOrStatInput>, Prisma.HospitalUncheckedUpdateWithoutOrStatInput>
}

export type HospitalCreateNestedOneWithoutWaitingTimesInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutWaitingTimesInput, Prisma.HospitalUncheckedCreateWithoutWaitingTimesInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutWaitingTimesInput
  connect?: Prisma.HospitalWhereUniqueInput
}

export type HospitalUpdateOneRequiredWithoutWaitingTimesNestedInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutWaitingTimesInput, Prisma.HospitalUncheckedCreateWithoutWaitingTimesInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutWaitingTimesInput
  upsert?: Prisma.HospitalUpsertWithoutWaitingTimesInput
  connect?: Prisma.HospitalWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HospitalUpdateToOneWithWhereWithoutWaitingTimesInput, Prisma.HospitalUpdateWithoutWaitingTimesInput>, Prisma.HospitalUncheckedUpdateWithoutWaitingTimesInput>
}

export type HospitalCreateNestedOneWithoutVisitCountsInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutVisitCountsInput, Prisma.HospitalUncheckedCreateWithoutVisitCountsInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutVisitCountsInput
  connect?: Prisma.HospitalWhereUniqueInput
}

export type HospitalUpdateOneRequiredWithoutVisitCountsNestedInput = {
  create?: Prisma.XOR<Prisma.HospitalCreateWithoutVisitCountsInput, Prisma.HospitalUncheckedCreateWithoutVisitCountsInput>
  connectOrCreate?: Prisma.HospitalCreateOrConnectWithoutVisitCountsInput
  upsert?: Prisma.HospitalUpsertWithoutVisitCountsInput
  connect?: Prisma.HospitalWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HospitalUpdateToOneWithWhereWithoutVisitCountsInput, Prisma.HospitalUpdateWithoutVisitCountsInput>, Prisma.HospitalUncheckedUpdateWithoutVisitCountsInput>
}

export type HospitalCreateWithoutLrStatusInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  orStat?: Prisma.OrStatCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardCreateNestedManyWithoutHospitalInput
  ipdWards?: Prisma.IPDWardCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountCreateNestedManyWithoutHospitalInput
}

export type HospitalUncheckedCreateWithoutLrStatusInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  orStat?: Prisma.OrStatUncheckedCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardUncheckedCreateNestedManyWithoutHospitalInput
  ipdWards?: Prisma.IPDWardUncheckedCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeUncheckedCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountUncheckedCreateNestedManyWithoutHospitalInput
}

export type HospitalCreateOrConnectWithoutLrStatusInput = {
  where: Prisma.HospitalWhereUniqueInput
  create: Prisma.XOR<Prisma.HospitalCreateWithoutLrStatusInput, Prisma.HospitalUncheckedCreateWithoutLrStatusInput>
}

export type HospitalUpsertWithoutLrStatusInput = {
  update: Prisma.XOR<Prisma.HospitalUpdateWithoutLrStatusInput, Prisma.HospitalUncheckedUpdateWithoutLrStatusInput>
  create: Prisma.XOR<Prisma.HospitalCreateWithoutLrStatusInput, Prisma.HospitalUncheckedCreateWithoutLrStatusInput>
  where?: Prisma.HospitalWhereInput
}

export type HospitalUpdateToOneWithWhereWithoutLrStatusInput = {
  where?: Prisma.HospitalWhereInput
  data: Prisma.XOR<Prisma.HospitalUpdateWithoutLrStatusInput, Prisma.HospitalUncheckedUpdateWithoutLrStatusInput>
}

export type HospitalUpdateWithoutLrStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  orStat?: Prisma.OrStatUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUpdateManyWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUpdateManyWithoutHospitalNestedInput
}

export type HospitalUncheckedUpdateWithoutLrStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  orStat?: Prisma.OrStatUncheckedUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUncheckedUpdateManyWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUncheckedUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUncheckedUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUncheckedUpdateManyWithoutHospitalNestedInput
}

export type HospitalCreateWithoutIcuWardsInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusCreateNestedOneWithoutHospitalInput
  orStat?: Prisma.OrStatCreateNestedOneWithoutHospitalInput
  ipdWards?: Prisma.IPDWardCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountCreateNestedManyWithoutHospitalInput
}

export type HospitalUncheckedCreateWithoutIcuWardsInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusUncheckedCreateNestedOneWithoutHospitalInput
  orStat?: Prisma.OrStatUncheckedCreateNestedOneWithoutHospitalInput
  ipdWards?: Prisma.IPDWardUncheckedCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeUncheckedCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountUncheckedCreateNestedManyWithoutHospitalInput
}

export type HospitalCreateOrConnectWithoutIcuWardsInput = {
  where: Prisma.HospitalWhereUniqueInput
  create: Prisma.XOR<Prisma.HospitalCreateWithoutIcuWardsInput, Prisma.HospitalUncheckedCreateWithoutIcuWardsInput>
}

export type HospitalUpsertWithoutIcuWardsInput = {
  update: Prisma.XOR<Prisma.HospitalUpdateWithoutIcuWardsInput, Prisma.HospitalUncheckedUpdateWithoutIcuWardsInput>
  create: Prisma.XOR<Prisma.HospitalCreateWithoutIcuWardsInput, Prisma.HospitalUncheckedCreateWithoutIcuWardsInput>
  where?: Prisma.HospitalWhereInput
}

export type HospitalUpdateToOneWithWhereWithoutIcuWardsInput = {
  where?: Prisma.HospitalWhereInput
  data: Prisma.XOR<Prisma.HospitalUpdateWithoutIcuWardsInput, Prisma.HospitalUncheckedUpdateWithoutIcuWardsInput>
}

export type HospitalUpdateWithoutIcuWardsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUpdateOneWithoutHospitalNestedInput
  orStat?: Prisma.OrStatUpdateOneWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUpdateManyWithoutHospitalNestedInput
}

export type HospitalUncheckedUpdateWithoutIcuWardsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUncheckedUpdateOneWithoutHospitalNestedInput
  orStat?: Prisma.OrStatUncheckedUpdateOneWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUncheckedUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUncheckedUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUncheckedUpdateManyWithoutHospitalNestedInput
}

export type HospitalCreateWithoutIpdWardsInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusCreateNestedOneWithoutHospitalInput
  orStat?: Prisma.OrStatCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountCreateNestedManyWithoutHospitalInput
}

export type HospitalUncheckedCreateWithoutIpdWardsInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusUncheckedCreateNestedOneWithoutHospitalInput
  orStat?: Prisma.OrStatUncheckedCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardUncheckedCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeUncheckedCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountUncheckedCreateNestedManyWithoutHospitalInput
}

export type HospitalCreateOrConnectWithoutIpdWardsInput = {
  where: Prisma.HospitalWhereUniqueInput
  create: Prisma.XOR<Prisma.HospitalCreateWithoutIpdWardsInput, Prisma.HospitalUncheckedCreateWithoutIpdWardsInput>
}

export type HospitalUpsertWithoutIpdWardsInput = {
  update: Prisma.XOR<Prisma.HospitalUpdateWithoutIpdWardsInput, Prisma.HospitalUncheckedUpdateWithoutIpdWardsInput>
  create: Prisma.XOR<Prisma.HospitalCreateWithoutIpdWardsInput, Prisma.HospitalUncheckedCreateWithoutIpdWardsInput>
  where?: Prisma.HospitalWhereInput
}

export type HospitalUpdateToOneWithWhereWithoutIpdWardsInput = {
  where?: Prisma.HospitalWhereInput
  data: Prisma.XOR<Prisma.HospitalUpdateWithoutIpdWardsInput, Prisma.HospitalUncheckedUpdateWithoutIpdWardsInput>
}

export type HospitalUpdateWithoutIpdWardsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUpdateOneWithoutHospitalNestedInput
  orStat?: Prisma.OrStatUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUpdateManyWithoutHospitalNestedInput
}

export type HospitalUncheckedUpdateWithoutIpdWardsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUncheckedUpdateOneWithoutHospitalNestedInput
  orStat?: Prisma.OrStatUncheckedUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUncheckedUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUncheckedUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUncheckedUpdateManyWithoutHospitalNestedInput
}

export type HospitalCreateWithoutOrStatInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardCreateNestedManyWithoutHospitalInput
  ipdWards?: Prisma.IPDWardCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountCreateNestedManyWithoutHospitalInput
}

export type HospitalUncheckedCreateWithoutOrStatInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusUncheckedCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardUncheckedCreateNestedManyWithoutHospitalInput
  ipdWards?: Prisma.IPDWardUncheckedCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeUncheckedCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountUncheckedCreateNestedManyWithoutHospitalInput
}

export type HospitalCreateOrConnectWithoutOrStatInput = {
  where: Prisma.HospitalWhereUniqueInput
  create: Prisma.XOR<Prisma.HospitalCreateWithoutOrStatInput, Prisma.HospitalUncheckedCreateWithoutOrStatInput>
}

export type HospitalUpsertWithoutOrStatInput = {
  update: Prisma.XOR<Prisma.HospitalUpdateWithoutOrStatInput, Prisma.HospitalUncheckedUpdateWithoutOrStatInput>
  create: Prisma.XOR<Prisma.HospitalCreateWithoutOrStatInput, Prisma.HospitalUncheckedCreateWithoutOrStatInput>
  where?: Prisma.HospitalWhereInput
}

export type HospitalUpdateToOneWithWhereWithoutOrStatInput = {
  where?: Prisma.HospitalWhereInput
  data: Prisma.XOR<Prisma.HospitalUpdateWithoutOrStatInput, Prisma.HospitalUncheckedUpdateWithoutOrStatInput>
}

export type HospitalUpdateWithoutOrStatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUpdateManyWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUpdateManyWithoutHospitalNestedInput
}

export type HospitalUncheckedUpdateWithoutOrStatInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUncheckedUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUncheckedUpdateManyWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUncheckedUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUncheckedUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUncheckedUpdateManyWithoutHospitalNestedInput
}

export type HospitalCreateWithoutWaitingTimesInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusCreateNestedOneWithoutHospitalInput
  orStat?: Prisma.OrStatCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardCreateNestedManyWithoutHospitalInput
  ipdWards?: Prisma.IPDWardCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountCreateNestedManyWithoutHospitalInput
}

export type HospitalUncheckedCreateWithoutWaitingTimesInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusUncheckedCreateNestedOneWithoutHospitalInput
  orStat?: Prisma.OrStatUncheckedCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardUncheckedCreateNestedManyWithoutHospitalInput
  ipdWards?: Prisma.IPDWardUncheckedCreateNestedManyWithoutHospitalInput
  visitCounts?: Prisma.VisitCountUncheckedCreateNestedManyWithoutHospitalInput
}

export type HospitalCreateOrConnectWithoutWaitingTimesInput = {
  where: Prisma.HospitalWhereUniqueInput
  create: Prisma.XOR<Prisma.HospitalCreateWithoutWaitingTimesInput, Prisma.HospitalUncheckedCreateWithoutWaitingTimesInput>
}

export type HospitalUpsertWithoutWaitingTimesInput = {
  update: Prisma.XOR<Prisma.HospitalUpdateWithoutWaitingTimesInput, Prisma.HospitalUncheckedUpdateWithoutWaitingTimesInput>
  create: Prisma.XOR<Prisma.HospitalCreateWithoutWaitingTimesInput, Prisma.HospitalUncheckedCreateWithoutWaitingTimesInput>
  where?: Prisma.HospitalWhereInput
}

export type HospitalUpdateToOneWithWhereWithoutWaitingTimesInput = {
  where?: Prisma.HospitalWhereInput
  data: Prisma.XOR<Prisma.HospitalUpdateWithoutWaitingTimesInput, Prisma.HospitalUncheckedUpdateWithoutWaitingTimesInput>
}

export type HospitalUpdateWithoutWaitingTimesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUpdateOneWithoutHospitalNestedInput
  orStat?: Prisma.OrStatUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUpdateManyWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUpdateManyWithoutHospitalNestedInput
}

export type HospitalUncheckedUpdateWithoutWaitingTimesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUncheckedUpdateOneWithoutHospitalNestedInput
  orStat?: Prisma.OrStatUncheckedUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUncheckedUpdateManyWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUncheckedUpdateManyWithoutHospitalNestedInput
  visitCounts?: Prisma.VisitCountUncheckedUpdateManyWithoutHospitalNestedInput
}

export type HospitalCreateWithoutVisitCountsInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusCreateNestedOneWithoutHospitalInput
  orStat?: Prisma.OrStatCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardCreateNestedManyWithoutHospitalInput
  ipdWards?: Prisma.IPDWardCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeCreateNestedManyWithoutHospitalInput
}

export type HospitalUncheckedCreateWithoutVisitCountsInput = {
  id: string
  name: string
  code: string
  sizeLevel: $Enums.HospitalSizeLevel
  sapLevel: $Enums.HospitalSapLevel
  affiliation: $Enums.HospitalAffiliation
  lat?: number | null
  lng?: number | null
  lrStatus?: Prisma.LrStatusUncheckedCreateNestedOneWithoutHospitalInput
  orStat?: Prisma.OrStatUncheckedCreateNestedOneWithoutHospitalInput
  icuWards?: Prisma.ICUWardUncheckedCreateNestedManyWithoutHospitalInput
  ipdWards?: Prisma.IPDWardUncheckedCreateNestedManyWithoutHospitalInput
  waitingTimes?: Prisma.WaitingTimeUncheckedCreateNestedManyWithoutHospitalInput
}

export type HospitalCreateOrConnectWithoutVisitCountsInput = {
  where: Prisma.HospitalWhereUniqueInput
  create: Prisma.XOR<Prisma.HospitalCreateWithoutVisitCountsInput, Prisma.HospitalUncheckedCreateWithoutVisitCountsInput>
}

export type HospitalUpsertWithoutVisitCountsInput = {
  update: Prisma.XOR<Prisma.HospitalUpdateWithoutVisitCountsInput, Prisma.HospitalUncheckedUpdateWithoutVisitCountsInput>
  create: Prisma.XOR<Prisma.HospitalCreateWithoutVisitCountsInput, Prisma.HospitalUncheckedCreateWithoutVisitCountsInput>
  where?: Prisma.HospitalWhereInput
}

export type HospitalUpdateToOneWithWhereWithoutVisitCountsInput = {
  where?: Prisma.HospitalWhereInput
  data: Prisma.XOR<Prisma.HospitalUpdateWithoutVisitCountsInput, Prisma.HospitalUncheckedUpdateWithoutVisitCountsInput>
}

export type HospitalUpdateWithoutVisitCountsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUpdateOneWithoutHospitalNestedInput
  orStat?: Prisma.OrStatUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUpdateManyWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUpdateManyWithoutHospitalNestedInput
}

export type HospitalUncheckedUpdateWithoutVisitCountsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  sizeLevel?: Prisma.EnumHospitalSizeLevelFieldUpdateOperationsInput | $Enums.HospitalSizeLevel
  sapLevel?: Prisma.EnumHospitalSapLevelFieldUpdateOperationsInput | $Enums.HospitalSapLevel
  affiliation?: Prisma.EnumHospitalAffiliationFieldUpdateOperationsInput | $Enums.HospitalAffiliation
  lat?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lng?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  lrStatus?: Prisma.LrStatusUncheckedUpdateOneWithoutHospitalNestedInput
  orStat?: Prisma.OrStatUncheckedUpdateOneWithoutHospitalNestedInput
  icuWards?: Prisma.ICUWardUncheckedUpdateManyWithoutHospitalNestedInput
  ipdWards?: Prisma.IPDWardUncheckedUpdateManyWithoutHospitalNestedInput
  waitingTimes?: Prisma.WaitingTimeUncheckedUpdateManyWithoutHospitalNestedInput
}


/**
 * Count Type HospitalCountOutputType
 */

export type HospitalCountOutputType = {
  icuWards: number
  ipdWards: number
  waitingTimes: number
  visitCounts: number
}

export type HospitalCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  icuWards?: boolean | HospitalCountOutputTypeCountIcuWardsArgs
  ipdWards?: boolean | HospitalCountOutputTypeCountIpdWardsArgs
  waitingTimes?: boolean | HospitalCountOutputTypeCountWaitingTimesArgs
  visitCounts?: boolean | HospitalCountOutputTypeCountVisitCountsArgs
}

/**
 * HospitalCountOutputType without action
 */
export type HospitalCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HospitalCountOutputType
   */
  select?: Prisma.HospitalCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HospitalCountOutputType without action
 */
export type HospitalCountOutputTypeCountIcuWardsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ICUWardWhereInput
}

/**
 * HospitalCountOutputType without action
 */
export type HospitalCountOutputTypeCountIpdWardsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IPDWardWhereInput
}

/**
 * HospitalCountOutputType without action
 */
export type HospitalCountOutputTypeCountWaitingTimesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WaitingTimeWhereInput
}

/**
 * HospitalCountOutputType without action
 */
export type HospitalCountOutputTypeCountVisitCountsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VisitCountWhereInput
}


export type HospitalSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  code?: boolean
  sizeLevel?: boolean
  sapLevel?: boolean
  affiliation?: boolean
  lat?: boolean
  lng?: boolean
  lrStatus?: boolean | Prisma.Hospital$lrStatusArgs<ExtArgs>
  orStat?: boolean | Prisma.Hospital$orStatArgs<ExtArgs>
  icuWards?: boolean | Prisma.Hospital$icuWardsArgs<ExtArgs>
  ipdWards?: boolean | Prisma.Hospital$ipdWardsArgs<ExtArgs>
  waitingTimes?: boolean | Prisma.Hospital$waitingTimesArgs<ExtArgs>
  visitCounts?: boolean | Prisma.Hospital$visitCountsArgs<ExtArgs>
  _count?: boolean | Prisma.HospitalCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["hospital"]>

export type HospitalSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  code?: boolean
  sizeLevel?: boolean
  sapLevel?: boolean
  affiliation?: boolean
  lat?: boolean
  lng?: boolean
}, ExtArgs["result"]["hospital"]>

export type HospitalSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  code?: boolean
  sizeLevel?: boolean
  sapLevel?: boolean
  affiliation?: boolean
  lat?: boolean
  lng?: boolean
}, ExtArgs["result"]["hospital"]>

export type HospitalSelectScalar = {
  id?: boolean
  name?: boolean
  code?: boolean
  sizeLevel?: boolean
  sapLevel?: boolean
  affiliation?: boolean
  lat?: boolean
  lng?: boolean
}

export type HospitalOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "code" | "sizeLevel" | "sapLevel" | "affiliation" | "lat" | "lng", ExtArgs["result"]["hospital"]>
export type HospitalInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lrStatus?: boolean | Prisma.Hospital$lrStatusArgs<ExtArgs>
  orStat?: boolean | Prisma.Hospital$orStatArgs<ExtArgs>
  icuWards?: boolean | Prisma.Hospital$icuWardsArgs<ExtArgs>
  ipdWards?: boolean | Prisma.Hospital$ipdWardsArgs<ExtArgs>
  waitingTimes?: boolean | Prisma.Hospital$waitingTimesArgs<ExtArgs>
  visitCounts?: boolean | Prisma.Hospital$visitCountsArgs<ExtArgs>
  _count?: boolean | Prisma.HospitalCountOutputTypeDefaultArgs<ExtArgs>
}
export type HospitalIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type HospitalIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $HospitalPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Hospital"
  objects: {
    lrStatus: Prisma.$LrStatusPayload<ExtArgs> | null
    orStat: Prisma.$OrStatPayload<ExtArgs> | null
    icuWards: Prisma.$ICUWardPayload<ExtArgs>[]
    ipdWards: Prisma.$IPDWardPayload<ExtArgs>[]
    waitingTimes: Prisma.$WaitingTimePayload<ExtArgs>[]
    visitCounts: Prisma.$VisitCountPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    code: string
    sizeLevel: $Enums.HospitalSizeLevel
    sapLevel: $Enums.HospitalSapLevel
    affiliation: $Enums.HospitalAffiliation
    lat: number | null
    lng: number | null
  }, ExtArgs["result"]["hospital"]>
  composites: {}
}

export type HospitalGetPayload<S extends boolean | null | undefined | HospitalDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HospitalPayload, S>

export type HospitalCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HospitalFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HospitalCountAggregateInputType | true
  }

export interface HospitalDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Hospital'], meta: { name: 'Hospital' } }
  /**
   * Find zero or one Hospital that matches the filter.
   * @param {HospitalFindUniqueArgs} args - Arguments to find a Hospital
   * @example
   * // Get one Hospital
   * const hospital = await prisma.hospital.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HospitalFindUniqueArgs>(args: Prisma.SelectSubset<T, HospitalFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Hospital that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HospitalFindUniqueOrThrowArgs} args - Arguments to find a Hospital
   * @example
   * // Get one Hospital
   * const hospital = await prisma.hospital.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HospitalFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HospitalFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hospital that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HospitalFindFirstArgs} args - Arguments to find a Hospital
   * @example
   * // Get one Hospital
   * const hospital = await prisma.hospital.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HospitalFindFirstArgs>(args?: Prisma.SelectSubset<T, HospitalFindFirstArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hospital that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HospitalFindFirstOrThrowArgs} args - Arguments to find a Hospital
   * @example
   * // Get one Hospital
   * const hospital = await prisma.hospital.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HospitalFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HospitalFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Hospitals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HospitalFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Hospitals
   * const hospitals = await prisma.hospital.findMany()
   * 
   * // Get first 10 Hospitals
   * const hospitals = await prisma.hospital.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const hospitalWithIdOnly = await prisma.hospital.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HospitalFindManyArgs>(args?: Prisma.SelectSubset<T, HospitalFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Hospital.
   * @param {HospitalCreateArgs} args - Arguments to create a Hospital.
   * @example
   * // Create one Hospital
   * const Hospital = await prisma.hospital.create({
   *   data: {
   *     // ... data to create a Hospital
   *   }
   * })
   * 
   */
  create<T extends HospitalCreateArgs>(args: Prisma.SelectSubset<T, HospitalCreateArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Hospitals.
   * @param {HospitalCreateManyArgs} args - Arguments to create many Hospitals.
   * @example
   * // Create many Hospitals
   * const hospital = await prisma.hospital.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HospitalCreateManyArgs>(args?: Prisma.SelectSubset<T, HospitalCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Hospitals and returns the data saved in the database.
   * @param {HospitalCreateManyAndReturnArgs} args - Arguments to create many Hospitals.
   * @example
   * // Create many Hospitals
   * const hospital = await prisma.hospital.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Hospitals and only return the `id`
   * const hospitalWithIdOnly = await prisma.hospital.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HospitalCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HospitalCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Hospital.
   * @param {HospitalDeleteArgs} args - Arguments to delete one Hospital.
   * @example
   * // Delete one Hospital
   * const Hospital = await prisma.hospital.delete({
   *   where: {
   *     // ... filter to delete one Hospital
   *   }
   * })
   * 
   */
  delete<T extends HospitalDeleteArgs>(args: Prisma.SelectSubset<T, HospitalDeleteArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Hospital.
   * @param {HospitalUpdateArgs} args - Arguments to update one Hospital.
   * @example
   * // Update one Hospital
   * const hospital = await prisma.hospital.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HospitalUpdateArgs>(args: Prisma.SelectSubset<T, HospitalUpdateArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Hospitals.
   * @param {HospitalDeleteManyArgs} args - Arguments to filter Hospitals to delete.
   * @example
   * // Delete a few Hospitals
   * const { count } = await prisma.hospital.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HospitalDeleteManyArgs>(args?: Prisma.SelectSubset<T, HospitalDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Hospitals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HospitalUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Hospitals
   * const hospital = await prisma.hospital.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HospitalUpdateManyArgs>(args: Prisma.SelectSubset<T, HospitalUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Hospitals and returns the data updated in the database.
   * @param {HospitalUpdateManyAndReturnArgs} args - Arguments to update many Hospitals.
   * @example
   * // Update many Hospitals
   * const hospital = await prisma.hospital.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Hospitals and only return the `id`
   * const hospitalWithIdOnly = await prisma.hospital.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HospitalUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HospitalUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Hospital.
   * @param {HospitalUpsertArgs} args - Arguments to update or create a Hospital.
   * @example
   * // Update or create a Hospital
   * const hospital = await prisma.hospital.upsert({
   *   create: {
   *     // ... data to create a Hospital
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Hospital we want to update
   *   }
   * })
   */
  upsert<T extends HospitalUpsertArgs>(args: Prisma.SelectSubset<T, HospitalUpsertArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Hospitals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HospitalCountArgs} args - Arguments to filter Hospitals to count.
   * @example
   * // Count the number of Hospitals
   * const count = await prisma.hospital.count({
   *   where: {
   *     // ... the filter for the Hospitals we want to count
   *   }
   * })
  **/
  count<T extends HospitalCountArgs>(
    args?: Prisma.Subset<T, HospitalCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HospitalCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Hospital.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HospitalAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HospitalAggregateArgs>(args: Prisma.Subset<T, HospitalAggregateArgs>): Prisma.PrismaPromise<GetHospitalAggregateType<T>>

  /**
   * Group by Hospital.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HospitalGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HospitalGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HospitalGroupByArgs['orderBy'] }
      : { orderBy?: HospitalGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HospitalGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHospitalGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Hospital model
 */
readonly fields: HospitalFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Hospital.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HospitalClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lrStatus<T extends Prisma.Hospital$lrStatusArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Hospital$lrStatusArgs<ExtArgs>>): Prisma.Prisma__LrStatusClient<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  orStat<T extends Prisma.Hospital$orStatArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Hospital$orStatArgs<ExtArgs>>): Prisma.Prisma__OrStatClient<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  icuWards<T extends Prisma.Hospital$icuWardsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Hospital$icuWardsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ICUWardPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  ipdWards<T extends Prisma.Hospital$ipdWardsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Hospital$ipdWardsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  waitingTimes<T extends Prisma.Hospital$waitingTimesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Hospital$waitingTimesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  visitCounts<T extends Prisma.Hospital$visitCountsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Hospital$visitCountsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Hospital model
 */
export interface HospitalFieldRefs {
  readonly id: Prisma.FieldRef<"Hospital", 'String'>
  readonly name: Prisma.FieldRef<"Hospital", 'String'>
  readonly code: Prisma.FieldRef<"Hospital", 'String'>
  readonly sizeLevel: Prisma.FieldRef<"Hospital", 'HospitalSizeLevel'>
  readonly sapLevel: Prisma.FieldRef<"Hospital", 'HospitalSapLevel'>
  readonly affiliation: Prisma.FieldRef<"Hospital", 'HospitalAffiliation'>
  readonly lat: Prisma.FieldRef<"Hospital", 'Float'>
  readonly lng: Prisma.FieldRef<"Hospital", 'Float'>
}
    

// Custom InputTypes
/**
 * Hospital findUnique
 */
export type HospitalFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HospitalInclude<ExtArgs> | null
  /**
   * Filter, which Hospital to fetch.
   */
  where: Prisma.HospitalWhereUniqueInput
}

/**
 * Hospital findUniqueOrThrow
 */
export type HospitalFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HospitalInclude<ExtArgs> | null
  /**
   * Filter, which Hospital to fetch.
   */
  where: Prisma.HospitalWhereUniqueInput
}

/**
 * Hospital findFirst
 */
export type HospitalFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HospitalInclude<ExtArgs> | null
  /**
   * Filter, which Hospital to fetch.
   */
  where?: Prisma.HospitalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hospitals to fetch.
   */
  orderBy?: Prisma.HospitalOrderByWithRelationInput | Prisma.HospitalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Hospitals.
   */
  cursor?: Prisma.HospitalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hospitals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hospitals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Hospitals.
   */
  distinct?: Prisma.HospitalScalarFieldEnum | Prisma.HospitalScalarFieldEnum[]
}

/**
 * Hospital findFirstOrThrow
 */
export type HospitalFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HospitalInclude<ExtArgs> | null
  /**
   * Filter, which Hospital to fetch.
   */
  where?: Prisma.HospitalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hospitals to fetch.
   */
  orderBy?: Prisma.HospitalOrderByWithRelationInput | Prisma.HospitalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Hospitals.
   */
  cursor?: Prisma.HospitalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hospitals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hospitals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Hospitals.
   */
  distinct?: Prisma.HospitalScalarFieldEnum | Prisma.HospitalScalarFieldEnum[]
}

/**
 * Hospital findMany
 */
export type HospitalFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HospitalInclude<ExtArgs> | null
  /**
   * Filter, which Hospitals to fetch.
   */
  where?: Prisma.HospitalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Hospitals to fetch.
   */
  orderBy?: Prisma.HospitalOrderByWithRelationInput | Prisma.HospitalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Hospitals.
   */
  cursor?: Prisma.HospitalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Hospitals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Hospitals.
   */
  skip?: number
  distinct?: Prisma.HospitalScalarFieldEnum | Prisma.HospitalScalarFieldEnum[]
}

/**
 * Hospital create
 */
export type HospitalCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HospitalInclude<ExtArgs> | null
  /**
   * The data needed to create a Hospital.
   */
  data: Prisma.XOR<Prisma.HospitalCreateInput, Prisma.HospitalUncheckedCreateInput>
}

/**
 * Hospital createMany
 */
export type HospitalCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Hospitals.
   */
  data: Prisma.HospitalCreateManyInput | Prisma.HospitalCreateManyInput[]
}

/**
 * Hospital createManyAndReturn
 */
export type HospitalCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * The data used to create many Hospitals.
   */
  data: Prisma.HospitalCreateManyInput | Prisma.HospitalCreateManyInput[]
}

/**
 * Hospital update
 */
export type HospitalUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HospitalInclude<ExtArgs> | null
  /**
   * The data needed to update a Hospital.
   */
  data: Prisma.XOR<Prisma.HospitalUpdateInput, Prisma.HospitalUncheckedUpdateInput>
  /**
   * Choose, which Hospital to update.
   */
  where: Prisma.HospitalWhereUniqueInput
}

/**
 * Hospital updateMany
 */
export type HospitalUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Hospitals.
   */
  data: Prisma.XOR<Prisma.HospitalUpdateManyMutationInput, Prisma.HospitalUncheckedUpdateManyInput>
  /**
   * Filter which Hospitals to update
   */
  where?: Prisma.HospitalWhereInput
  /**
   * Limit how many Hospitals to update.
   */
  limit?: number
}

/**
 * Hospital updateManyAndReturn
 */
export type HospitalUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * The data used to update Hospitals.
   */
  data: Prisma.XOR<Prisma.HospitalUpdateManyMutationInput, Prisma.HospitalUncheckedUpdateManyInput>
  /**
   * Filter which Hospitals to update
   */
  where?: Prisma.HospitalWhereInput
  /**
   * Limit how many Hospitals to update.
   */
  limit?: number
}

/**
 * Hospital upsert
 */
export type HospitalUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HospitalInclude<ExtArgs> | null
  /**
   * The filter to search for the Hospital to update in case it exists.
   */
  where: Prisma.HospitalWhereUniqueInput
  /**
   * In case the Hospital found by the `where` argument doesn't exist, create a new Hospital with this data.
   */
  create: Prisma.XOR<Prisma.HospitalCreateInput, Prisma.HospitalUncheckedCreateInput>
  /**
   * In case the Hospital was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HospitalUpdateInput, Prisma.HospitalUncheckedUpdateInput>
}

/**
 * Hospital delete
 */
export type HospitalDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HospitalInclude<ExtArgs> | null
  /**
   * Filter which Hospital to delete.
   */
  where: Prisma.HospitalWhereUniqueInput
}

/**
 * Hospital deleteMany
 */
export type HospitalDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Hospitals to delete
   */
  where?: Prisma.HospitalWhereInput
  /**
   * Limit how many Hospitals to delete.
   */
  limit?: number
}

/**
 * Hospital.lrStatus
 */
export type Hospital$lrStatusArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusInclude<ExtArgs> | null
  where?: Prisma.LrStatusWhereInput
}

/**
 * Hospital.orStat
 */
export type Hospital$orStatArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatInclude<ExtArgs> | null
  where?: Prisma.OrStatWhereInput
}

/**
 * Hospital.icuWards
 */
export type Hospital$icuWardsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ICUWard
   */
  select?: Prisma.ICUWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ICUWard
   */
  omit?: Prisma.ICUWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ICUWardInclude<ExtArgs> | null
  where?: Prisma.ICUWardWhereInput
  orderBy?: Prisma.ICUWardOrderByWithRelationInput | Prisma.ICUWardOrderByWithRelationInput[]
  cursor?: Prisma.ICUWardWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ICUWardScalarFieldEnum | Prisma.ICUWardScalarFieldEnum[]
}

/**
 * Hospital.ipdWards
 */
export type Hospital$ipdWardsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardInclude<ExtArgs> | null
  where?: Prisma.IPDWardWhereInput
  orderBy?: Prisma.IPDWardOrderByWithRelationInput | Prisma.IPDWardOrderByWithRelationInput[]
  cursor?: Prisma.IPDWardWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.IPDWardScalarFieldEnum | Prisma.IPDWardScalarFieldEnum[]
}

/**
 * Hospital.waitingTimes
 */
export type Hospital$waitingTimesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeInclude<ExtArgs> | null
  where?: Prisma.WaitingTimeWhereInput
  orderBy?: Prisma.WaitingTimeOrderByWithRelationInput | Prisma.WaitingTimeOrderByWithRelationInput[]
  cursor?: Prisma.WaitingTimeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WaitingTimeScalarFieldEnum | Prisma.WaitingTimeScalarFieldEnum[]
}

/**
 * Hospital.visitCounts
 */
export type Hospital$visitCountsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountInclude<ExtArgs> | null
  where?: Prisma.VisitCountWhereInput
  orderBy?: Prisma.VisitCountOrderByWithRelationInput | Prisma.VisitCountOrderByWithRelationInput[]
  cursor?: Prisma.VisitCountWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VisitCountScalarFieldEnum | Prisma.VisitCountScalarFieldEnum[]
}

/**
 * Hospital without action
 */
export type HospitalDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Hospital
   */
  select?: Prisma.HospitalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Hospital
   */
  omit?: Prisma.HospitalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HospitalInclude<ExtArgs> | null
}
