
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WaitingTime` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model WaitingTime
 * 
 */
export type WaitingTimeModel = runtime.Types.Result.DefaultSelection<Prisma.$WaitingTimePayload>

export type AggregateWaitingTime = {
  _count: WaitingTimeCountAggregateOutputType | null
  _avg: WaitingTimeAvgAggregateOutputType | null
  _sum: WaitingTimeSumAggregateOutputType | null
  _min: WaitingTimeMinAggregateOutputType | null
  _max: WaitingTimeMaxAggregateOutputType | null
}

export type WaitingTimeAvgAggregateOutputType = {
  minutes: number | null
}

export type WaitingTimeSumAggregateOutputType = {
  minutes: number | null
}

export type WaitingTimeMinAggregateOutputType = {
  id: string | null
  hospitalId: string | null
  date: string | null
  dayName: string | null
  minutes: number | null
}

export type WaitingTimeMaxAggregateOutputType = {
  id: string | null
  hospitalId: string | null
  date: string | null
  dayName: string | null
  minutes: number | null
}

export type WaitingTimeCountAggregateOutputType = {
  id: number
  hospitalId: number
  date: number
  dayName: number
  minutes: number
  _all: number
}


export type WaitingTimeAvgAggregateInputType = {
  minutes?: true
}

export type WaitingTimeSumAggregateInputType = {
  minutes?: true
}

export type WaitingTimeMinAggregateInputType = {
  id?: true
  hospitalId?: true
  date?: true
  dayName?: true
  minutes?: true
}

export type WaitingTimeMaxAggregateInputType = {
  id?: true
  hospitalId?: true
  date?: true
  dayName?: true
  minutes?: true
}

export type WaitingTimeCountAggregateInputType = {
  id?: true
  hospitalId?: true
  date?: true
  dayName?: true
  minutes?: true
  _all?: true
}

export type WaitingTimeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WaitingTime to aggregate.
   */
  where?: Prisma.WaitingTimeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WaitingTimes to fetch.
   */
  orderBy?: Prisma.WaitingTimeOrderByWithRelationInput | Prisma.WaitingTimeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WaitingTimeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WaitingTimes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WaitingTimes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WaitingTimes
  **/
  _count?: true | WaitingTimeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WaitingTimeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WaitingTimeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WaitingTimeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WaitingTimeMaxAggregateInputType
}

export type GetWaitingTimeAggregateType<T extends WaitingTimeAggregateArgs> = {
      [P in keyof T & keyof AggregateWaitingTime]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWaitingTime[P]>
    : Prisma.GetScalarType<T[P], AggregateWaitingTime[P]>
}




export type WaitingTimeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WaitingTimeWhereInput
  orderBy?: Prisma.WaitingTimeOrderByWithAggregationInput | Prisma.WaitingTimeOrderByWithAggregationInput[]
  by: Prisma.WaitingTimeScalarFieldEnum[] | Prisma.WaitingTimeScalarFieldEnum
  having?: Prisma.WaitingTimeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WaitingTimeCountAggregateInputType | true
  _avg?: WaitingTimeAvgAggregateInputType
  _sum?: WaitingTimeSumAggregateInputType
  _min?: WaitingTimeMinAggregateInputType
  _max?: WaitingTimeMaxAggregateInputType
}

export type WaitingTimeGroupByOutputType = {
  id: string
  hospitalId: string
  date: string
  dayName: string
  minutes: number
  _count: WaitingTimeCountAggregateOutputType | null
  _avg: WaitingTimeAvgAggregateOutputType | null
  _sum: WaitingTimeSumAggregateOutputType | null
  _min: WaitingTimeMinAggregateOutputType | null
  _max: WaitingTimeMaxAggregateOutputType | null
}

type GetWaitingTimeGroupByPayload<T extends WaitingTimeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WaitingTimeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WaitingTimeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WaitingTimeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WaitingTimeGroupByOutputType[P]>
      }
    >
  >



export type WaitingTimeWhereInput = {
  AND?: Prisma.WaitingTimeWhereInput | Prisma.WaitingTimeWhereInput[]
  OR?: Prisma.WaitingTimeWhereInput[]
  NOT?: Prisma.WaitingTimeWhereInput | Prisma.WaitingTimeWhereInput[]
  id?: Prisma.StringFilter<"WaitingTime"> | string
  hospitalId?: Prisma.StringFilter<"WaitingTime"> | string
  date?: Prisma.StringFilter<"WaitingTime"> | string
  dayName?: Prisma.StringFilter<"WaitingTime"> | string
  minutes?: Prisma.IntFilter<"WaitingTime"> | number
  hospital?: Prisma.XOR<Prisma.HospitalScalarRelationFilter, Prisma.HospitalWhereInput>
}

export type WaitingTimeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dayName?: Prisma.SortOrder
  minutes?: Prisma.SortOrder
  hospital?: Prisma.HospitalOrderByWithRelationInput
}

export type WaitingTimeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WaitingTimeWhereInput | Prisma.WaitingTimeWhereInput[]
  OR?: Prisma.WaitingTimeWhereInput[]
  NOT?: Prisma.WaitingTimeWhereInput | Prisma.WaitingTimeWhereInput[]
  hospitalId?: Prisma.StringFilter<"WaitingTime"> | string
  date?: Prisma.StringFilter<"WaitingTime"> | string
  dayName?: Prisma.StringFilter<"WaitingTime"> | string
  minutes?: Prisma.IntFilter<"WaitingTime"> | number
  hospital?: Prisma.XOR<Prisma.HospitalScalarRelationFilter, Prisma.HospitalWhereInput>
}, "id">

export type WaitingTimeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dayName?: Prisma.SortOrder
  minutes?: Prisma.SortOrder
  _count?: Prisma.WaitingTimeCountOrderByAggregateInput
  _avg?: Prisma.WaitingTimeAvgOrderByAggregateInput
  _max?: Prisma.WaitingTimeMaxOrderByAggregateInput
  _min?: Prisma.WaitingTimeMinOrderByAggregateInput
  _sum?: Prisma.WaitingTimeSumOrderByAggregateInput
}

export type WaitingTimeScalarWhereWithAggregatesInput = {
  AND?: Prisma.WaitingTimeScalarWhereWithAggregatesInput | Prisma.WaitingTimeScalarWhereWithAggregatesInput[]
  OR?: Prisma.WaitingTimeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WaitingTimeScalarWhereWithAggregatesInput | Prisma.WaitingTimeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WaitingTime"> | string
  hospitalId?: Prisma.StringWithAggregatesFilter<"WaitingTime"> | string
  date?: Prisma.StringWithAggregatesFilter<"WaitingTime"> | string
  dayName?: Prisma.StringWithAggregatesFilter<"WaitingTime"> | string
  minutes?: Prisma.IntWithAggregatesFilter<"WaitingTime"> | number
}

export type WaitingTimeCreateInput = {
  id?: string
  date: string
  dayName: string
  minutes: number
  hospital: Prisma.HospitalCreateNestedOneWithoutWaitingTimesInput
}

export type WaitingTimeUncheckedCreateInput = {
  id?: string
  hospitalId: string
  date: string
  dayName: string
  minutes: number
}

export type WaitingTimeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  minutes?: Prisma.IntFieldUpdateOperationsInput | number
  hospital?: Prisma.HospitalUpdateOneRequiredWithoutWaitingTimesNestedInput
}

export type WaitingTimeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hospitalId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  minutes?: Prisma.IntFieldUpdateOperationsInput | number
}

export type WaitingTimeCreateManyInput = {
  id?: string
  hospitalId: string
  date: string
  dayName: string
  minutes: number
}

export type WaitingTimeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  minutes?: Prisma.IntFieldUpdateOperationsInput | number
}

export type WaitingTimeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hospitalId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  minutes?: Prisma.IntFieldUpdateOperationsInput | number
}

export type WaitingTimeListRelationFilter = {
  every?: Prisma.WaitingTimeWhereInput
  some?: Prisma.WaitingTimeWhereInput
  none?: Prisma.WaitingTimeWhereInput
}

export type WaitingTimeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WaitingTimeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dayName?: Prisma.SortOrder
  minutes?: Prisma.SortOrder
}

export type WaitingTimeAvgOrderByAggregateInput = {
  minutes?: Prisma.SortOrder
}

export type WaitingTimeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dayName?: Prisma.SortOrder
  minutes?: Prisma.SortOrder
}

export type WaitingTimeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dayName?: Prisma.SortOrder
  minutes?: Prisma.SortOrder
}

export type WaitingTimeSumOrderByAggregateInput = {
  minutes?: Prisma.SortOrder
}

export type WaitingTimeCreateNestedManyWithoutHospitalInput = {
  create?: Prisma.XOR<Prisma.WaitingTimeCreateWithoutHospitalInput, Prisma.WaitingTimeUncheckedCreateWithoutHospitalInput> | Prisma.WaitingTimeCreateWithoutHospitalInput[] | Prisma.WaitingTimeUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.WaitingTimeCreateOrConnectWithoutHospitalInput | Prisma.WaitingTimeCreateOrConnectWithoutHospitalInput[]
  createMany?: Prisma.WaitingTimeCreateManyHospitalInputEnvelope
  connect?: Prisma.WaitingTimeWhereUniqueInput | Prisma.WaitingTimeWhereUniqueInput[]
}

export type WaitingTimeUncheckedCreateNestedManyWithoutHospitalInput = {
  create?: Prisma.XOR<Prisma.WaitingTimeCreateWithoutHospitalInput, Prisma.WaitingTimeUncheckedCreateWithoutHospitalInput> | Prisma.WaitingTimeCreateWithoutHospitalInput[] | Prisma.WaitingTimeUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.WaitingTimeCreateOrConnectWithoutHospitalInput | Prisma.WaitingTimeCreateOrConnectWithoutHospitalInput[]
  createMany?: Prisma.WaitingTimeCreateManyHospitalInputEnvelope
  connect?: Prisma.WaitingTimeWhereUniqueInput | Prisma.WaitingTimeWhereUniqueInput[]
}

export type WaitingTimeUpdateManyWithoutHospitalNestedInput = {
  create?: Prisma.XOR<Prisma.WaitingTimeCreateWithoutHospitalInput, Prisma.WaitingTimeUncheckedCreateWithoutHospitalInput> | Prisma.WaitingTimeCreateWithoutHospitalInput[] | Prisma.WaitingTimeUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.WaitingTimeCreateOrConnectWithoutHospitalInput | Prisma.WaitingTimeCreateOrConnectWithoutHospitalInput[]
  upsert?: Prisma.WaitingTimeUpsertWithWhereUniqueWithoutHospitalInput | Prisma.WaitingTimeUpsertWithWhereUniqueWithoutHospitalInput[]
  createMany?: Prisma.WaitingTimeCreateManyHospitalInputEnvelope
  set?: Prisma.WaitingTimeWhereUniqueInput | Prisma.WaitingTimeWhereUniqueInput[]
  disconnect?: Prisma.WaitingTimeWhereUniqueInput | Prisma.WaitingTimeWhereUniqueInput[]
  delete?: Prisma.WaitingTimeWhereUniqueInput | Prisma.WaitingTimeWhereUniqueInput[]
  connect?: Prisma.WaitingTimeWhereUniqueInput | Prisma.WaitingTimeWhereUniqueInput[]
  update?: Prisma.WaitingTimeUpdateWithWhereUniqueWithoutHospitalInput | Prisma.WaitingTimeUpdateWithWhereUniqueWithoutHospitalInput[]
  updateMany?: Prisma.WaitingTimeUpdateManyWithWhereWithoutHospitalInput | Prisma.WaitingTimeUpdateManyWithWhereWithoutHospitalInput[]
  deleteMany?: Prisma.WaitingTimeScalarWhereInput | Prisma.WaitingTimeScalarWhereInput[]
}

export type WaitingTimeUncheckedUpdateManyWithoutHospitalNestedInput = {
  create?: Prisma.XOR<Prisma.WaitingTimeCreateWithoutHospitalInput, Prisma.WaitingTimeUncheckedCreateWithoutHospitalInput> | Prisma.WaitingTimeCreateWithoutHospitalInput[] | Prisma.WaitingTimeUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.WaitingTimeCreateOrConnectWithoutHospitalInput | Prisma.WaitingTimeCreateOrConnectWithoutHospitalInput[]
  upsert?: Prisma.WaitingTimeUpsertWithWhereUniqueWithoutHospitalInput | Prisma.WaitingTimeUpsertWithWhereUniqueWithoutHospitalInput[]
  createMany?: Prisma.WaitingTimeCreateManyHospitalInputEnvelope
  set?: Prisma.WaitingTimeWhereUniqueInput | Prisma.WaitingTimeWhereUniqueInput[]
  disconnect?: Prisma.WaitingTimeWhereUniqueInput | Prisma.WaitingTimeWhereUniqueInput[]
  delete?: Prisma.WaitingTimeWhereUniqueInput | Prisma.WaitingTimeWhereUniqueInput[]
  connect?: Prisma.WaitingTimeWhereUniqueInput | Prisma.WaitingTimeWhereUniqueInput[]
  update?: Prisma.WaitingTimeUpdateWithWhereUniqueWithoutHospitalInput | Prisma.WaitingTimeUpdateWithWhereUniqueWithoutHospitalInput[]
  updateMany?: Prisma.WaitingTimeUpdateManyWithWhereWithoutHospitalInput | Prisma.WaitingTimeUpdateManyWithWhereWithoutHospitalInput[]
  deleteMany?: Prisma.WaitingTimeScalarWhereInput | Prisma.WaitingTimeScalarWhereInput[]
}

export type WaitingTimeCreateWithoutHospitalInput = {
  id?: string
  date: string
  dayName: string
  minutes: number
}

export type WaitingTimeUncheckedCreateWithoutHospitalInput = {
  id?: string
  date: string
  dayName: string
  minutes: number
}

export type WaitingTimeCreateOrConnectWithoutHospitalInput = {
  where: Prisma.WaitingTimeWhereUniqueInput
  create: Prisma.XOR<Prisma.WaitingTimeCreateWithoutHospitalInput, Prisma.WaitingTimeUncheckedCreateWithoutHospitalInput>
}

export type WaitingTimeCreateManyHospitalInputEnvelope = {
  data: Prisma.WaitingTimeCreateManyHospitalInput | Prisma.WaitingTimeCreateManyHospitalInput[]
}

export type WaitingTimeUpsertWithWhereUniqueWithoutHospitalInput = {
  where: Prisma.WaitingTimeWhereUniqueInput
  update: Prisma.XOR<Prisma.WaitingTimeUpdateWithoutHospitalInput, Prisma.WaitingTimeUncheckedUpdateWithoutHospitalInput>
  create: Prisma.XOR<Prisma.WaitingTimeCreateWithoutHospitalInput, Prisma.WaitingTimeUncheckedCreateWithoutHospitalInput>
}

export type WaitingTimeUpdateWithWhereUniqueWithoutHospitalInput = {
  where: Prisma.WaitingTimeWhereUniqueInput
  data: Prisma.XOR<Prisma.WaitingTimeUpdateWithoutHospitalInput, Prisma.WaitingTimeUncheckedUpdateWithoutHospitalInput>
}

export type WaitingTimeUpdateManyWithWhereWithoutHospitalInput = {
  where: Prisma.WaitingTimeScalarWhereInput
  data: Prisma.XOR<Prisma.WaitingTimeUpdateManyMutationInput, Prisma.WaitingTimeUncheckedUpdateManyWithoutHospitalInput>
}

export type WaitingTimeScalarWhereInput = {
  AND?: Prisma.WaitingTimeScalarWhereInput | Prisma.WaitingTimeScalarWhereInput[]
  OR?: Prisma.WaitingTimeScalarWhereInput[]
  NOT?: Prisma.WaitingTimeScalarWhereInput | Prisma.WaitingTimeScalarWhereInput[]
  id?: Prisma.StringFilter<"WaitingTime"> | string
  hospitalId?: Prisma.StringFilter<"WaitingTime"> | string
  date?: Prisma.StringFilter<"WaitingTime"> | string
  dayName?: Prisma.StringFilter<"WaitingTime"> | string
  minutes?: Prisma.IntFilter<"WaitingTime"> | number
}

export type WaitingTimeCreateManyHospitalInput = {
  id?: string
  date: string
  dayName: string
  minutes: number
}

export type WaitingTimeUpdateWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  minutes?: Prisma.IntFieldUpdateOperationsInput | number
}

export type WaitingTimeUncheckedUpdateWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  minutes?: Prisma.IntFieldUpdateOperationsInput | number
}

export type WaitingTimeUncheckedUpdateManyWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  minutes?: Prisma.IntFieldUpdateOperationsInput | number
}



export type WaitingTimeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  date?: boolean
  dayName?: boolean
  minutes?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["waitingTime"]>

export type WaitingTimeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  date?: boolean
  dayName?: boolean
  minutes?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["waitingTime"]>

export type WaitingTimeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  date?: boolean
  dayName?: boolean
  minutes?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["waitingTime"]>

export type WaitingTimeSelectScalar = {
  id?: boolean
  hospitalId?: boolean
  date?: boolean
  dayName?: boolean
  minutes?: boolean
}

export type WaitingTimeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "hospitalId" | "date" | "dayName" | "minutes", ExtArgs["result"]["waitingTime"]>
export type WaitingTimeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}
export type WaitingTimeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}
export type WaitingTimeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}

export type $WaitingTimePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WaitingTime"
  objects: {
    hospital: Prisma.$HospitalPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    hospitalId: string
    date: string
    dayName: string
    minutes: number
  }, ExtArgs["result"]["waitingTime"]>
  composites: {}
}

export type WaitingTimeGetPayload<S extends boolean | null | undefined | WaitingTimeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload, S>

export type WaitingTimeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WaitingTimeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WaitingTimeCountAggregateInputType | true
  }

export interface WaitingTimeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WaitingTime'], meta: { name: 'WaitingTime' } }
  /**
   * Find zero or one WaitingTime that matches the filter.
   * @param {WaitingTimeFindUniqueArgs} args - Arguments to find a WaitingTime
   * @example
   * // Get one WaitingTime
   * const waitingTime = await prisma.waitingTime.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WaitingTimeFindUniqueArgs>(args: Prisma.SelectSubset<T, WaitingTimeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WaitingTimeClient<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WaitingTime that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WaitingTimeFindUniqueOrThrowArgs} args - Arguments to find a WaitingTime
   * @example
   * // Get one WaitingTime
   * const waitingTime = await prisma.waitingTime.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WaitingTimeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WaitingTimeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WaitingTimeClient<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WaitingTime that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaitingTimeFindFirstArgs} args - Arguments to find a WaitingTime
   * @example
   * // Get one WaitingTime
   * const waitingTime = await prisma.waitingTime.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WaitingTimeFindFirstArgs>(args?: Prisma.SelectSubset<T, WaitingTimeFindFirstArgs<ExtArgs>>): Prisma.Prisma__WaitingTimeClient<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WaitingTime that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaitingTimeFindFirstOrThrowArgs} args - Arguments to find a WaitingTime
   * @example
   * // Get one WaitingTime
   * const waitingTime = await prisma.waitingTime.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WaitingTimeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WaitingTimeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WaitingTimeClient<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WaitingTimes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaitingTimeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WaitingTimes
   * const waitingTimes = await prisma.waitingTime.findMany()
   * 
   * // Get first 10 WaitingTimes
   * const waitingTimes = await prisma.waitingTime.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const waitingTimeWithIdOnly = await prisma.waitingTime.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WaitingTimeFindManyArgs>(args?: Prisma.SelectSubset<T, WaitingTimeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WaitingTime.
   * @param {WaitingTimeCreateArgs} args - Arguments to create a WaitingTime.
   * @example
   * // Create one WaitingTime
   * const WaitingTime = await prisma.waitingTime.create({
   *   data: {
   *     // ... data to create a WaitingTime
   *   }
   * })
   * 
   */
  create<T extends WaitingTimeCreateArgs>(args: Prisma.SelectSubset<T, WaitingTimeCreateArgs<ExtArgs>>): Prisma.Prisma__WaitingTimeClient<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WaitingTimes.
   * @param {WaitingTimeCreateManyArgs} args - Arguments to create many WaitingTimes.
   * @example
   * // Create many WaitingTimes
   * const waitingTime = await prisma.waitingTime.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WaitingTimeCreateManyArgs>(args?: Prisma.SelectSubset<T, WaitingTimeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WaitingTimes and returns the data saved in the database.
   * @param {WaitingTimeCreateManyAndReturnArgs} args - Arguments to create many WaitingTimes.
   * @example
   * // Create many WaitingTimes
   * const waitingTime = await prisma.waitingTime.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WaitingTimes and only return the `id`
   * const waitingTimeWithIdOnly = await prisma.waitingTime.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WaitingTimeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WaitingTimeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WaitingTime.
   * @param {WaitingTimeDeleteArgs} args - Arguments to delete one WaitingTime.
   * @example
   * // Delete one WaitingTime
   * const WaitingTime = await prisma.waitingTime.delete({
   *   where: {
   *     // ... filter to delete one WaitingTime
   *   }
   * })
   * 
   */
  delete<T extends WaitingTimeDeleteArgs>(args: Prisma.SelectSubset<T, WaitingTimeDeleteArgs<ExtArgs>>): Prisma.Prisma__WaitingTimeClient<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WaitingTime.
   * @param {WaitingTimeUpdateArgs} args - Arguments to update one WaitingTime.
   * @example
   * // Update one WaitingTime
   * const waitingTime = await prisma.waitingTime.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WaitingTimeUpdateArgs>(args: Prisma.SelectSubset<T, WaitingTimeUpdateArgs<ExtArgs>>): Prisma.Prisma__WaitingTimeClient<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WaitingTimes.
   * @param {WaitingTimeDeleteManyArgs} args - Arguments to filter WaitingTimes to delete.
   * @example
   * // Delete a few WaitingTimes
   * const { count } = await prisma.waitingTime.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WaitingTimeDeleteManyArgs>(args?: Prisma.SelectSubset<T, WaitingTimeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WaitingTimes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaitingTimeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WaitingTimes
   * const waitingTime = await prisma.waitingTime.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WaitingTimeUpdateManyArgs>(args: Prisma.SelectSubset<T, WaitingTimeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WaitingTimes and returns the data updated in the database.
   * @param {WaitingTimeUpdateManyAndReturnArgs} args - Arguments to update many WaitingTimes.
   * @example
   * // Update many WaitingTimes
   * const waitingTime = await prisma.waitingTime.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WaitingTimes and only return the `id`
   * const waitingTimeWithIdOnly = await prisma.waitingTime.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WaitingTimeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WaitingTimeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WaitingTime.
   * @param {WaitingTimeUpsertArgs} args - Arguments to update or create a WaitingTime.
   * @example
   * // Update or create a WaitingTime
   * const waitingTime = await prisma.waitingTime.upsert({
   *   create: {
   *     // ... data to create a WaitingTime
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WaitingTime we want to update
   *   }
   * })
   */
  upsert<T extends WaitingTimeUpsertArgs>(args: Prisma.SelectSubset<T, WaitingTimeUpsertArgs<ExtArgs>>): Prisma.Prisma__WaitingTimeClient<runtime.Types.Result.GetResult<Prisma.$WaitingTimePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WaitingTimes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaitingTimeCountArgs} args - Arguments to filter WaitingTimes to count.
   * @example
   * // Count the number of WaitingTimes
   * const count = await prisma.waitingTime.count({
   *   where: {
   *     // ... the filter for the WaitingTimes we want to count
   *   }
   * })
  **/
  count<T extends WaitingTimeCountArgs>(
    args?: Prisma.Subset<T, WaitingTimeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WaitingTimeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WaitingTime.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaitingTimeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WaitingTimeAggregateArgs>(args: Prisma.Subset<T, WaitingTimeAggregateArgs>): Prisma.PrismaPromise<GetWaitingTimeAggregateType<T>>

  /**
   * Group by WaitingTime.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WaitingTimeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WaitingTimeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WaitingTimeGroupByArgs['orderBy'] }
      : { orderBy?: WaitingTimeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WaitingTimeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWaitingTimeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WaitingTime model
 */
readonly fields: WaitingTimeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WaitingTime.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WaitingTimeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  hospital<T extends Prisma.HospitalDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HospitalDefaultArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WaitingTime model
 */
export interface WaitingTimeFieldRefs {
  readonly id: Prisma.FieldRef<"WaitingTime", 'String'>
  readonly hospitalId: Prisma.FieldRef<"WaitingTime", 'String'>
  readonly date: Prisma.FieldRef<"WaitingTime", 'String'>
  readonly dayName: Prisma.FieldRef<"WaitingTime", 'String'>
  readonly minutes: Prisma.FieldRef<"WaitingTime", 'Int'>
}
    

// Custom InputTypes
/**
 * WaitingTime findUnique
 */
export type WaitingTimeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeInclude<ExtArgs> | null
  /**
   * Filter, which WaitingTime to fetch.
   */
  where: Prisma.WaitingTimeWhereUniqueInput
}

/**
 * WaitingTime findUniqueOrThrow
 */
export type WaitingTimeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeInclude<ExtArgs> | null
  /**
   * Filter, which WaitingTime to fetch.
   */
  where: Prisma.WaitingTimeWhereUniqueInput
}

/**
 * WaitingTime findFirst
 */
export type WaitingTimeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeInclude<ExtArgs> | null
  /**
   * Filter, which WaitingTime to fetch.
   */
  where?: Prisma.WaitingTimeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WaitingTimes to fetch.
   */
  orderBy?: Prisma.WaitingTimeOrderByWithRelationInput | Prisma.WaitingTimeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WaitingTimes.
   */
  cursor?: Prisma.WaitingTimeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WaitingTimes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WaitingTimes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WaitingTimes.
   */
  distinct?: Prisma.WaitingTimeScalarFieldEnum | Prisma.WaitingTimeScalarFieldEnum[]
}

/**
 * WaitingTime findFirstOrThrow
 */
export type WaitingTimeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeInclude<ExtArgs> | null
  /**
   * Filter, which WaitingTime to fetch.
   */
  where?: Prisma.WaitingTimeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WaitingTimes to fetch.
   */
  orderBy?: Prisma.WaitingTimeOrderByWithRelationInput | Prisma.WaitingTimeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WaitingTimes.
   */
  cursor?: Prisma.WaitingTimeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WaitingTimes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WaitingTimes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WaitingTimes.
   */
  distinct?: Prisma.WaitingTimeScalarFieldEnum | Prisma.WaitingTimeScalarFieldEnum[]
}

/**
 * WaitingTime findMany
 */
export type WaitingTimeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeInclude<ExtArgs> | null
  /**
   * Filter, which WaitingTimes to fetch.
   */
  where?: Prisma.WaitingTimeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WaitingTimes to fetch.
   */
  orderBy?: Prisma.WaitingTimeOrderByWithRelationInput | Prisma.WaitingTimeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WaitingTimes.
   */
  cursor?: Prisma.WaitingTimeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WaitingTimes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WaitingTimes.
   */
  skip?: number
  distinct?: Prisma.WaitingTimeScalarFieldEnum | Prisma.WaitingTimeScalarFieldEnum[]
}

/**
 * WaitingTime create
 */
export type WaitingTimeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeInclude<ExtArgs> | null
  /**
   * The data needed to create a WaitingTime.
   */
  data: Prisma.XOR<Prisma.WaitingTimeCreateInput, Prisma.WaitingTimeUncheckedCreateInput>
}

/**
 * WaitingTime createMany
 */
export type WaitingTimeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WaitingTimes.
   */
  data: Prisma.WaitingTimeCreateManyInput | Prisma.WaitingTimeCreateManyInput[]
}

/**
 * WaitingTime createManyAndReturn
 */
export type WaitingTimeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * The data used to create many WaitingTimes.
   */
  data: Prisma.WaitingTimeCreateManyInput | Prisma.WaitingTimeCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WaitingTime update
 */
export type WaitingTimeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeInclude<ExtArgs> | null
  /**
   * The data needed to update a WaitingTime.
   */
  data: Prisma.XOR<Prisma.WaitingTimeUpdateInput, Prisma.WaitingTimeUncheckedUpdateInput>
  /**
   * Choose, which WaitingTime to update.
   */
  where: Prisma.WaitingTimeWhereUniqueInput
}

/**
 * WaitingTime updateMany
 */
export type WaitingTimeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WaitingTimes.
   */
  data: Prisma.XOR<Prisma.WaitingTimeUpdateManyMutationInput, Prisma.WaitingTimeUncheckedUpdateManyInput>
  /**
   * Filter which WaitingTimes to update
   */
  where?: Prisma.WaitingTimeWhereInput
  /**
   * Limit how many WaitingTimes to update.
   */
  limit?: number
}

/**
 * WaitingTime updateManyAndReturn
 */
export type WaitingTimeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * The data used to update WaitingTimes.
   */
  data: Prisma.XOR<Prisma.WaitingTimeUpdateManyMutationInput, Prisma.WaitingTimeUncheckedUpdateManyInput>
  /**
   * Filter which WaitingTimes to update
   */
  where?: Prisma.WaitingTimeWhereInput
  /**
   * Limit how many WaitingTimes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WaitingTime upsert
 */
export type WaitingTimeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeInclude<ExtArgs> | null
  /**
   * The filter to search for the WaitingTime to update in case it exists.
   */
  where: Prisma.WaitingTimeWhereUniqueInput
  /**
   * In case the WaitingTime found by the `where` argument doesn't exist, create a new WaitingTime with this data.
   */
  create: Prisma.XOR<Prisma.WaitingTimeCreateInput, Prisma.WaitingTimeUncheckedCreateInput>
  /**
   * In case the WaitingTime was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WaitingTimeUpdateInput, Prisma.WaitingTimeUncheckedUpdateInput>
}

/**
 * WaitingTime delete
 */
export type WaitingTimeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeInclude<ExtArgs> | null
  /**
   * Filter which WaitingTime to delete.
   */
  where: Prisma.WaitingTimeWhereUniqueInput
}

/**
 * WaitingTime deleteMany
 */
export type WaitingTimeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WaitingTimes to delete
   */
  where?: Prisma.WaitingTimeWhereInput
  /**
   * Limit how many WaitingTimes to delete.
   */
  limit?: number
}

/**
 * WaitingTime without action
 */
export type WaitingTimeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WaitingTime
   */
  select?: Prisma.WaitingTimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WaitingTime
   */
  omit?: Prisma.WaitingTimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WaitingTimeInclude<ExtArgs> | null
}
