
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `IPDWard` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model IPDWard
 * 
 */
export type IPDWardModel = runtime.Types.Result.DefaultSelection<Prisma.$IPDWardPayload>

export type AggregateIPDWard = {
  _count: IPDWardCountAggregateOutputType | null
  _avg: IPDWardAvgAggregateOutputType | null
  _sum: IPDWardSumAggregateOutputType | null
  _min: IPDWardMinAggregateOutputType | null
  _max: IPDWardMaxAggregateOutputType | null
}

export type IPDWardAvgAggregateOutputType = {
  totalBeds: number | null
  usedBeds: number | null
}

export type IPDWardSumAggregateOutputType = {
  totalBeds: number | null
  usedBeds: number | null
}

export type IPDWardMinAggregateOutputType = {
  id: string | null
  hospitalId: string | null
  name: string | null
  totalBeds: number | null
  usedBeds: number | null
}

export type IPDWardMaxAggregateOutputType = {
  id: string | null
  hospitalId: string | null
  name: string | null
  totalBeds: number | null
  usedBeds: number | null
}

export type IPDWardCountAggregateOutputType = {
  id: number
  hospitalId: number
  name: number
  totalBeds: number
  usedBeds: number
  _all: number
}


export type IPDWardAvgAggregateInputType = {
  totalBeds?: true
  usedBeds?: true
}

export type IPDWardSumAggregateInputType = {
  totalBeds?: true
  usedBeds?: true
}

export type IPDWardMinAggregateInputType = {
  id?: true
  hospitalId?: true
  name?: true
  totalBeds?: true
  usedBeds?: true
}

export type IPDWardMaxAggregateInputType = {
  id?: true
  hospitalId?: true
  name?: true
  totalBeds?: true
  usedBeds?: true
}

export type IPDWardCountAggregateInputType = {
  id?: true
  hospitalId?: true
  name?: true
  totalBeds?: true
  usedBeds?: true
  _all?: true
}

export type IPDWardAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which IPDWard to aggregate.
   */
  where?: Prisma.IPDWardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IPDWards to fetch.
   */
  orderBy?: Prisma.IPDWardOrderByWithRelationInput | Prisma.IPDWardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.IPDWardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IPDWards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IPDWards.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned IPDWards
  **/
  _count?: true | IPDWardCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: IPDWardAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: IPDWardSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: IPDWardMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: IPDWardMaxAggregateInputType
}

export type GetIPDWardAggregateType<T extends IPDWardAggregateArgs> = {
      [P in keyof T & keyof AggregateIPDWard]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIPDWard[P]>
    : Prisma.GetScalarType<T[P], AggregateIPDWard[P]>
}




export type IPDWardGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IPDWardWhereInput
  orderBy?: Prisma.IPDWardOrderByWithAggregationInput | Prisma.IPDWardOrderByWithAggregationInput[]
  by: Prisma.IPDWardScalarFieldEnum[] | Prisma.IPDWardScalarFieldEnum
  having?: Prisma.IPDWardScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: IPDWardCountAggregateInputType | true
  _avg?: IPDWardAvgAggregateInputType
  _sum?: IPDWardSumAggregateInputType
  _min?: IPDWardMinAggregateInputType
  _max?: IPDWardMaxAggregateInputType
}

export type IPDWardGroupByOutputType = {
  id: string
  hospitalId: string
  name: string
  totalBeds: number
  usedBeds: number
  _count: IPDWardCountAggregateOutputType | null
  _avg: IPDWardAvgAggregateOutputType | null
  _sum: IPDWardSumAggregateOutputType | null
  _min: IPDWardMinAggregateOutputType | null
  _max: IPDWardMaxAggregateOutputType | null
}

type GetIPDWardGroupByPayload<T extends IPDWardGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<IPDWardGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof IPDWardGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], IPDWardGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], IPDWardGroupByOutputType[P]>
      }
    >
  >



export type IPDWardWhereInput = {
  AND?: Prisma.IPDWardWhereInput | Prisma.IPDWardWhereInput[]
  OR?: Prisma.IPDWardWhereInput[]
  NOT?: Prisma.IPDWardWhereInput | Prisma.IPDWardWhereInput[]
  id?: Prisma.StringFilter<"IPDWard"> | string
  hospitalId?: Prisma.StringFilter<"IPDWard"> | string
  name?: Prisma.StringFilter<"IPDWard"> | string
  totalBeds?: Prisma.IntFilter<"IPDWard"> | number
  usedBeds?: Prisma.IntFilter<"IPDWard"> | number
  hospital?: Prisma.XOR<Prisma.HospitalScalarRelationFilter, Prisma.HospitalWhereInput>
}

export type IPDWardOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  totalBeds?: Prisma.SortOrder
  usedBeds?: Prisma.SortOrder
  hospital?: Prisma.HospitalOrderByWithRelationInput
}

export type IPDWardWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.IPDWardWhereInput | Prisma.IPDWardWhereInput[]
  OR?: Prisma.IPDWardWhereInput[]
  NOT?: Prisma.IPDWardWhereInput | Prisma.IPDWardWhereInput[]
  hospitalId?: Prisma.StringFilter<"IPDWard"> | string
  name?: Prisma.StringFilter<"IPDWard"> | string
  totalBeds?: Prisma.IntFilter<"IPDWard"> | number
  usedBeds?: Prisma.IntFilter<"IPDWard"> | number
  hospital?: Prisma.XOR<Prisma.HospitalScalarRelationFilter, Prisma.HospitalWhereInput>
}, "id">

export type IPDWardOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  totalBeds?: Prisma.SortOrder
  usedBeds?: Prisma.SortOrder
  _count?: Prisma.IPDWardCountOrderByAggregateInput
  _avg?: Prisma.IPDWardAvgOrderByAggregateInput
  _max?: Prisma.IPDWardMaxOrderByAggregateInput
  _min?: Prisma.IPDWardMinOrderByAggregateInput
  _sum?: Prisma.IPDWardSumOrderByAggregateInput
}

export type IPDWardScalarWhereWithAggregatesInput = {
  AND?: Prisma.IPDWardScalarWhereWithAggregatesInput | Prisma.IPDWardScalarWhereWithAggregatesInput[]
  OR?: Prisma.IPDWardScalarWhereWithAggregatesInput[]
  NOT?: Prisma.IPDWardScalarWhereWithAggregatesInput | Prisma.IPDWardScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"IPDWard"> | string
  hospitalId?: Prisma.StringWithAggregatesFilter<"IPDWard"> | string
  name?: Prisma.StringWithAggregatesFilter<"IPDWard"> | string
  totalBeds?: Prisma.IntWithAggregatesFilter<"IPDWard"> | number
  usedBeds?: Prisma.IntWithAggregatesFilter<"IPDWard"> | number
}

export type IPDWardCreateInput = {
  id?: string
  name: string
  totalBeds: number
  usedBeds: number
  hospital: Prisma.HospitalCreateNestedOneWithoutIpdWardsInput
}

export type IPDWardUncheckedCreateInput = {
  id?: string
  hospitalId: string
  name: string
  totalBeds: number
  usedBeds: number
}

export type IPDWardUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  totalBeds?: Prisma.IntFieldUpdateOperationsInput | number
  usedBeds?: Prisma.IntFieldUpdateOperationsInput | number
  hospital?: Prisma.HospitalUpdateOneRequiredWithoutIpdWardsNestedInput
}

export type IPDWardUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hospitalId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  totalBeds?: Prisma.IntFieldUpdateOperationsInput | number
  usedBeds?: Prisma.IntFieldUpdateOperationsInput | number
}

export type IPDWardCreateManyInput = {
  id?: string
  hospitalId: string
  name: string
  totalBeds: number
  usedBeds: number
}

export type IPDWardUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  totalBeds?: Prisma.IntFieldUpdateOperationsInput | number
  usedBeds?: Prisma.IntFieldUpdateOperationsInput | number
}

export type IPDWardUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hospitalId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  totalBeds?: Prisma.IntFieldUpdateOperationsInput | number
  usedBeds?: Prisma.IntFieldUpdateOperationsInput | number
}

export type IPDWardListRelationFilter = {
  every?: Prisma.IPDWardWhereInput
  some?: Prisma.IPDWardWhereInput
  none?: Prisma.IPDWardWhereInput
}

export type IPDWardOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type IPDWardCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  totalBeds?: Prisma.SortOrder
  usedBeds?: Prisma.SortOrder
}

export type IPDWardAvgOrderByAggregateInput = {
  totalBeds?: Prisma.SortOrder
  usedBeds?: Prisma.SortOrder
}

export type IPDWardMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  totalBeds?: Prisma.SortOrder
  usedBeds?: Prisma.SortOrder
}

export type IPDWardMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  totalBeds?: Prisma.SortOrder
  usedBeds?: Prisma.SortOrder
}

export type IPDWardSumOrderByAggregateInput = {
  totalBeds?: Prisma.SortOrder
  usedBeds?: Prisma.SortOrder
}

export type IPDWardCreateNestedManyWithoutHospitalInput = {
  create?: Prisma.XOR<Prisma.IPDWardCreateWithoutHospitalInput, Prisma.IPDWardUncheckedCreateWithoutHospitalInput> | Prisma.IPDWardCreateWithoutHospitalInput[] | Prisma.IPDWardUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.IPDWardCreateOrConnectWithoutHospitalInput | Prisma.IPDWardCreateOrConnectWithoutHospitalInput[]
  createMany?: Prisma.IPDWardCreateManyHospitalInputEnvelope
  connect?: Prisma.IPDWardWhereUniqueInput | Prisma.IPDWardWhereUniqueInput[]
}

export type IPDWardUncheckedCreateNestedManyWithoutHospitalInput = {
  create?: Prisma.XOR<Prisma.IPDWardCreateWithoutHospitalInput, Prisma.IPDWardUncheckedCreateWithoutHospitalInput> | Prisma.IPDWardCreateWithoutHospitalInput[] | Prisma.IPDWardUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.IPDWardCreateOrConnectWithoutHospitalInput | Prisma.IPDWardCreateOrConnectWithoutHospitalInput[]
  createMany?: Prisma.IPDWardCreateManyHospitalInputEnvelope
  connect?: Prisma.IPDWardWhereUniqueInput | Prisma.IPDWardWhereUniqueInput[]
}

export type IPDWardUpdateManyWithoutHospitalNestedInput = {
  create?: Prisma.XOR<Prisma.IPDWardCreateWithoutHospitalInput, Prisma.IPDWardUncheckedCreateWithoutHospitalInput> | Prisma.IPDWardCreateWithoutHospitalInput[] | Prisma.IPDWardUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.IPDWardCreateOrConnectWithoutHospitalInput | Prisma.IPDWardCreateOrConnectWithoutHospitalInput[]
  upsert?: Prisma.IPDWardUpsertWithWhereUniqueWithoutHospitalInput | Prisma.IPDWardUpsertWithWhereUniqueWithoutHospitalInput[]
  createMany?: Prisma.IPDWardCreateManyHospitalInputEnvelope
  set?: Prisma.IPDWardWhereUniqueInput | Prisma.IPDWardWhereUniqueInput[]
  disconnect?: Prisma.IPDWardWhereUniqueInput | Prisma.IPDWardWhereUniqueInput[]
  delete?: Prisma.IPDWardWhereUniqueInput | Prisma.IPDWardWhereUniqueInput[]
  connect?: Prisma.IPDWardWhereUniqueInput | Prisma.IPDWardWhereUniqueInput[]
  update?: Prisma.IPDWardUpdateWithWhereUniqueWithoutHospitalInput | Prisma.IPDWardUpdateWithWhereUniqueWithoutHospitalInput[]
  updateMany?: Prisma.IPDWardUpdateManyWithWhereWithoutHospitalInput | Prisma.IPDWardUpdateManyWithWhereWithoutHospitalInput[]
  deleteMany?: Prisma.IPDWardScalarWhereInput | Prisma.IPDWardScalarWhereInput[]
}

export type IPDWardUncheckedUpdateManyWithoutHospitalNestedInput = {
  create?: Prisma.XOR<Prisma.IPDWardCreateWithoutHospitalInput, Prisma.IPDWardUncheckedCreateWithoutHospitalInput> | Prisma.IPDWardCreateWithoutHospitalInput[] | Prisma.IPDWardUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.IPDWardCreateOrConnectWithoutHospitalInput | Prisma.IPDWardCreateOrConnectWithoutHospitalInput[]
  upsert?: Prisma.IPDWardUpsertWithWhereUniqueWithoutHospitalInput | Prisma.IPDWardUpsertWithWhereUniqueWithoutHospitalInput[]
  createMany?: Prisma.IPDWardCreateManyHospitalInputEnvelope
  set?: Prisma.IPDWardWhereUniqueInput | Prisma.IPDWardWhereUniqueInput[]
  disconnect?: Prisma.IPDWardWhereUniqueInput | Prisma.IPDWardWhereUniqueInput[]
  delete?: Prisma.IPDWardWhereUniqueInput | Prisma.IPDWardWhereUniqueInput[]
  connect?: Prisma.IPDWardWhereUniqueInput | Prisma.IPDWardWhereUniqueInput[]
  update?: Prisma.IPDWardUpdateWithWhereUniqueWithoutHospitalInput | Prisma.IPDWardUpdateWithWhereUniqueWithoutHospitalInput[]
  updateMany?: Prisma.IPDWardUpdateManyWithWhereWithoutHospitalInput | Prisma.IPDWardUpdateManyWithWhereWithoutHospitalInput[]
  deleteMany?: Prisma.IPDWardScalarWhereInput | Prisma.IPDWardScalarWhereInput[]
}

export type IPDWardCreateWithoutHospitalInput = {
  id?: string
  name: string
  totalBeds: number
  usedBeds: number
}

export type IPDWardUncheckedCreateWithoutHospitalInput = {
  id?: string
  name: string
  totalBeds: number
  usedBeds: number
}

export type IPDWardCreateOrConnectWithoutHospitalInput = {
  where: Prisma.IPDWardWhereUniqueInput
  create: Prisma.XOR<Prisma.IPDWardCreateWithoutHospitalInput, Prisma.IPDWardUncheckedCreateWithoutHospitalInput>
}

export type IPDWardCreateManyHospitalInputEnvelope = {
  data: Prisma.IPDWardCreateManyHospitalInput | Prisma.IPDWardCreateManyHospitalInput[]
}

export type IPDWardUpsertWithWhereUniqueWithoutHospitalInput = {
  where: Prisma.IPDWardWhereUniqueInput
  update: Prisma.XOR<Prisma.IPDWardUpdateWithoutHospitalInput, Prisma.IPDWardUncheckedUpdateWithoutHospitalInput>
  create: Prisma.XOR<Prisma.IPDWardCreateWithoutHospitalInput, Prisma.IPDWardUncheckedCreateWithoutHospitalInput>
}

export type IPDWardUpdateWithWhereUniqueWithoutHospitalInput = {
  where: Prisma.IPDWardWhereUniqueInput
  data: Prisma.XOR<Prisma.IPDWardUpdateWithoutHospitalInput, Prisma.IPDWardUncheckedUpdateWithoutHospitalInput>
}

export type IPDWardUpdateManyWithWhereWithoutHospitalInput = {
  where: Prisma.IPDWardScalarWhereInput
  data: Prisma.XOR<Prisma.IPDWardUpdateManyMutationInput, Prisma.IPDWardUncheckedUpdateManyWithoutHospitalInput>
}

export type IPDWardScalarWhereInput = {
  AND?: Prisma.IPDWardScalarWhereInput | Prisma.IPDWardScalarWhereInput[]
  OR?: Prisma.IPDWardScalarWhereInput[]
  NOT?: Prisma.IPDWardScalarWhereInput | Prisma.IPDWardScalarWhereInput[]
  id?: Prisma.StringFilter<"IPDWard"> | string
  hospitalId?: Prisma.StringFilter<"IPDWard"> | string
  name?: Prisma.StringFilter<"IPDWard"> | string
  totalBeds?: Prisma.IntFilter<"IPDWard"> | number
  usedBeds?: Prisma.IntFilter<"IPDWard"> | number
}

export type IPDWardCreateManyHospitalInput = {
  id?: string
  name: string
  totalBeds: number
  usedBeds: number
}

export type IPDWardUpdateWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  totalBeds?: Prisma.IntFieldUpdateOperationsInput | number
  usedBeds?: Prisma.IntFieldUpdateOperationsInput | number
}

export type IPDWardUncheckedUpdateWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  totalBeds?: Prisma.IntFieldUpdateOperationsInput | number
  usedBeds?: Prisma.IntFieldUpdateOperationsInput | number
}

export type IPDWardUncheckedUpdateManyWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  totalBeds?: Prisma.IntFieldUpdateOperationsInput | number
  usedBeds?: Prisma.IntFieldUpdateOperationsInput | number
}



export type IPDWardSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  name?: boolean
  totalBeds?: boolean
  usedBeds?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["iPDWard"]>

export type IPDWardSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  name?: boolean
  totalBeds?: boolean
  usedBeds?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["iPDWard"]>

export type IPDWardSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  name?: boolean
  totalBeds?: boolean
  usedBeds?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["iPDWard"]>

export type IPDWardSelectScalar = {
  id?: boolean
  hospitalId?: boolean
  name?: boolean
  totalBeds?: boolean
  usedBeds?: boolean
}

export type IPDWardOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "hospitalId" | "name" | "totalBeds" | "usedBeds", ExtArgs["result"]["iPDWard"]>
export type IPDWardInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}
export type IPDWardIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}
export type IPDWardIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}

export type $IPDWardPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "IPDWard"
  objects: {
    hospital: Prisma.$HospitalPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    hospitalId: string
    name: string
    totalBeds: number
    usedBeds: number
  }, ExtArgs["result"]["iPDWard"]>
  composites: {}
}

export type IPDWardGetPayload<S extends boolean | null | undefined | IPDWardDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$IPDWardPayload, S>

export type IPDWardCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<IPDWardFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: IPDWardCountAggregateInputType | true
  }

export interface IPDWardDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['IPDWard'], meta: { name: 'IPDWard' } }
  /**
   * Find zero or one IPDWard that matches the filter.
   * @param {IPDWardFindUniqueArgs} args - Arguments to find a IPDWard
   * @example
   * // Get one IPDWard
   * const iPDWard = await prisma.iPDWard.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends IPDWardFindUniqueArgs>(args: Prisma.SelectSubset<T, IPDWardFindUniqueArgs<ExtArgs>>): Prisma.Prisma__IPDWardClient<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one IPDWard that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {IPDWardFindUniqueOrThrowArgs} args - Arguments to find a IPDWard
   * @example
   * // Get one IPDWard
   * const iPDWard = await prisma.iPDWard.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends IPDWardFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, IPDWardFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__IPDWardClient<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first IPDWard that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IPDWardFindFirstArgs} args - Arguments to find a IPDWard
   * @example
   * // Get one IPDWard
   * const iPDWard = await prisma.iPDWard.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends IPDWardFindFirstArgs>(args?: Prisma.SelectSubset<T, IPDWardFindFirstArgs<ExtArgs>>): Prisma.Prisma__IPDWardClient<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first IPDWard that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IPDWardFindFirstOrThrowArgs} args - Arguments to find a IPDWard
   * @example
   * // Get one IPDWard
   * const iPDWard = await prisma.iPDWard.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends IPDWardFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, IPDWardFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__IPDWardClient<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more IPDWards that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IPDWardFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all IPDWards
   * const iPDWards = await prisma.iPDWard.findMany()
   * 
   * // Get first 10 IPDWards
   * const iPDWards = await prisma.iPDWard.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const iPDWardWithIdOnly = await prisma.iPDWard.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends IPDWardFindManyArgs>(args?: Prisma.SelectSubset<T, IPDWardFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a IPDWard.
   * @param {IPDWardCreateArgs} args - Arguments to create a IPDWard.
   * @example
   * // Create one IPDWard
   * const IPDWard = await prisma.iPDWard.create({
   *   data: {
   *     // ... data to create a IPDWard
   *   }
   * })
   * 
   */
  create<T extends IPDWardCreateArgs>(args: Prisma.SelectSubset<T, IPDWardCreateArgs<ExtArgs>>): Prisma.Prisma__IPDWardClient<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many IPDWards.
   * @param {IPDWardCreateManyArgs} args - Arguments to create many IPDWards.
   * @example
   * // Create many IPDWards
   * const iPDWard = await prisma.iPDWard.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends IPDWardCreateManyArgs>(args?: Prisma.SelectSubset<T, IPDWardCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many IPDWards and returns the data saved in the database.
   * @param {IPDWardCreateManyAndReturnArgs} args - Arguments to create many IPDWards.
   * @example
   * // Create many IPDWards
   * const iPDWard = await prisma.iPDWard.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many IPDWards and only return the `id`
   * const iPDWardWithIdOnly = await prisma.iPDWard.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends IPDWardCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, IPDWardCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a IPDWard.
   * @param {IPDWardDeleteArgs} args - Arguments to delete one IPDWard.
   * @example
   * // Delete one IPDWard
   * const IPDWard = await prisma.iPDWard.delete({
   *   where: {
   *     // ... filter to delete one IPDWard
   *   }
   * })
   * 
   */
  delete<T extends IPDWardDeleteArgs>(args: Prisma.SelectSubset<T, IPDWardDeleteArgs<ExtArgs>>): Prisma.Prisma__IPDWardClient<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one IPDWard.
   * @param {IPDWardUpdateArgs} args - Arguments to update one IPDWard.
   * @example
   * // Update one IPDWard
   * const iPDWard = await prisma.iPDWard.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends IPDWardUpdateArgs>(args: Prisma.SelectSubset<T, IPDWardUpdateArgs<ExtArgs>>): Prisma.Prisma__IPDWardClient<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more IPDWards.
   * @param {IPDWardDeleteManyArgs} args - Arguments to filter IPDWards to delete.
   * @example
   * // Delete a few IPDWards
   * const { count } = await prisma.iPDWard.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends IPDWardDeleteManyArgs>(args?: Prisma.SelectSubset<T, IPDWardDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more IPDWards.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IPDWardUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many IPDWards
   * const iPDWard = await prisma.iPDWard.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends IPDWardUpdateManyArgs>(args: Prisma.SelectSubset<T, IPDWardUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more IPDWards and returns the data updated in the database.
   * @param {IPDWardUpdateManyAndReturnArgs} args - Arguments to update many IPDWards.
   * @example
   * // Update many IPDWards
   * const iPDWard = await prisma.iPDWard.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more IPDWards and only return the `id`
   * const iPDWardWithIdOnly = await prisma.iPDWard.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends IPDWardUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, IPDWardUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one IPDWard.
   * @param {IPDWardUpsertArgs} args - Arguments to update or create a IPDWard.
   * @example
   * // Update or create a IPDWard
   * const iPDWard = await prisma.iPDWard.upsert({
   *   create: {
   *     // ... data to create a IPDWard
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the IPDWard we want to update
   *   }
   * })
   */
  upsert<T extends IPDWardUpsertArgs>(args: Prisma.SelectSubset<T, IPDWardUpsertArgs<ExtArgs>>): Prisma.Prisma__IPDWardClient<runtime.Types.Result.GetResult<Prisma.$IPDWardPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of IPDWards.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IPDWardCountArgs} args - Arguments to filter IPDWards to count.
   * @example
   * // Count the number of IPDWards
   * const count = await prisma.iPDWard.count({
   *   where: {
   *     // ... the filter for the IPDWards we want to count
   *   }
   * })
  **/
  count<T extends IPDWardCountArgs>(
    args?: Prisma.Subset<T, IPDWardCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], IPDWardCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a IPDWard.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IPDWardAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends IPDWardAggregateArgs>(args: Prisma.Subset<T, IPDWardAggregateArgs>): Prisma.PrismaPromise<GetIPDWardAggregateType<T>>

  /**
   * Group by IPDWard.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IPDWardGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends IPDWardGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: IPDWardGroupByArgs['orderBy'] }
      : { orderBy?: IPDWardGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, IPDWardGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIPDWardGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the IPDWard model
 */
readonly fields: IPDWardFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for IPDWard.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__IPDWardClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  hospital<T extends Prisma.HospitalDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HospitalDefaultArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the IPDWard model
 */
export interface IPDWardFieldRefs {
  readonly id: Prisma.FieldRef<"IPDWard", 'String'>
  readonly hospitalId: Prisma.FieldRef<"IPDWard", 'String'>
  readonly name: Prisma.FieldRef<"IPDWard", 'String'>
  readonly totalBeds: Prisma.FieldRef<"IPDWard", 'Int'>
  readonly usedBeds: Prisma.FieldRef<"IPDWard", 'Int'>
}
    

// Custom InputTypes
/**
 * IPDWard findUnique
 */
export type IPDWardFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardInclude<ExtArgs> | null
  /**
   * Filter, which IPDWard to fetch.
   */
  where: Prisma.IPDWardWhereUniqueInput
}

/**
 * IPDWard findUniqueOrThrow
 */
export type IPDWardFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardInclude<ExtArgs> | null
  /**
   * Filter, which IPDWard to fetch.
   */
  where: Prisma.IPDWardWhereUniqueInput
}

/**
 * IPDWard findFirst
 */
export type IPDWardFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardInclude<ExtArgs> | null
  /**
   * Filter, which IPDWard to fetch.
   */
  where?: Prisma.IPDWardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IPDWards to fetch.
   */
  orderBy?: Prisma.IPDWardOrderByWithRelationInput | Prisma.IPDWardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for IPDWards.
   */
  cursor?: Prisma.IPDWardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IPDWards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IPDWards.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of IPDWards.
   */
  distinct?: Prisma.IPDWardScalarFieldEnum | Prisma.IPDWardScalarFieldEnum[]
}

/**
 * IPDWard findFirstOrThrow
 */
export type IPDWardFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardInclude<ExtArgs> | null
  /**
   * Filter, which IPDWard to fetch.
   */
  where?: Prisma.IPDWardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IPDWards to fetch.
   */
  orderBy?: Prisma.IPDWardOrderByWithRelationInput | Prisma.IPDWardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for IPDWards.
   */
  cursor?: Prisma.IPDWardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IPDWards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IPDWards.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of IPDWards.
   */
  distinct?: Prisma.IPDWardScalarFieldEnum | Prisma.IPDWardScalarFieldEnum[]
}

/**
 * IPDWard findMany
 */
export type IPDWardFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardInclude<ExtArgs> | null
  /**
   * Filter, which IPDWards to fetch.
   */
  where?: Prisma.IPDWardWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IPDWards to fetch.
   */
  orderBy?: Prisma.IPDWardOrderByWithRelationInput | Prisma.IPDWardOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing IPDWards.
   */
  cursor?: Prisma.IPDWardWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IPDWards from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IPDWards.
   */
  skip?: number
  distinct?: Prisma.IPDWardScalarFieldEnum | Prisma.IPDWardScalarFieldEnum[]
}

/**
 * IPDWard create
 */
export type IPDWardCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardInclude<ExtArgs> | null
  /**
   * The data needed to create a IPDWard.
   */
  data: Prisma.XOR<Prisma.IPDWardCreateInput, Prisma.IPDWardUncheckedCreateInput>
}

/**
 * IPDWard createMany
 */
export type IPDWardCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many IPDWards.
   */
  data: Prisma.IPDWardCreateManyInput | Prisma.IPDWardCreateManyInput[]
}

/**
 * IPDWard createManyAndReturn
 */
export type IPDWardCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * The data used to create many IPDWards.
   */
  data: Prisma.IPDWardCreateManyInput | Prisma.IPDWardCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * IPDWard update
 */
export type IPDWardUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardInclude<ExtArgs> | null
  /**
   * The data needed to update a IPDWard.
   */
  data: Prisma.XOR<Prisma.IPDWardUpdateInput, Prisma.IPDWardUncheckedUpdateInput>
  /**
   * Choose, which IPDWard to update.
   */
  where: Prisma.IPDWardWhereUniqueInput
}

/**
 * IPDWard updateMany
 */
export type IPDWardUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update IPDWards.
   */
  data: Prisma.XOR<Prisma.IPDWardUpdateManyMutationInput, Prisma.IPDWardUncheckedUpdateManyInput>
  /**
   * Filter which IPDWards to update
   */
  where?: Prisma.IPDWardWhereInput
  /**
   * Limit how many IPDWards to update.
   */
  limit?: number
}

/**
 * IPDWard updateManyAndReturn
 */
export type IPDWardUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * The data used to update IPDWards.
   */
  data: Prisma.XOR<Prisma.IPDWardUpdateManyMutationInput, Prisma.IPDWardUncheckedUpdateManyInput>
  /**
   * Filter which IPDWards to update
   */
  where?: Prisma.IPDWardWhereInput
  /**
   * Limit how many IPDWards to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * IPDWard upsert
 */
export type IPDWardUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardInclude<ExtArgs> | null
  /**
   * The filter to search for the IPDWard to update in case it exists.
   */
  where: Prisma.IPDWardWhereUniqueInput
  /**
   * In case the IPDWard found by the `where` argument doesn't exist, create a new IPDWard with this data.
   */
  create: Prisma.XOR<Prisma.IPDWardCreateInput, Prisma.IPDWardUncheckedCreateInput>
  /**
   * In case the IPDWard was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.IPDWardUpdateInput, Prisma.IPDWardUncheckedUpdateInput>
}

/**
 * IPDWard delete
 */
export type IPDWardDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardInclude<ExtArgs> | null
  /**
   * Filter which IPDWard to delete.
   */
  where: Prisma.IPDWardWhereUniqueInput
}

/**
 * IPDWard deleteMany
 */
export type IPDWardDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which IPDWards to delete
   */
  where?: Prisma.IPDWardWhereInput
  /**
   * Limit how many IPDWards to delete.
   */
  limit?: number
}

/**
 * IPDWard without action
 */
export type IPDWardDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IPDWard
   */
  select?: Prisma.IPDWardSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IPDWard
   */
  omit?: Prisma.IPDWardOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IPDWardInclude<ExtArgs> | null
}
