
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LrStatus` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model LrStatus
 * 
 */
export type LrStatusModel = runtime.Types.Result.DefaultSelection<Prisma.$LrStatusPayload>

export type AggregateLrStatus = {
  _count: LrStatusCountAggregateOutputType | null
  _avg: LrStatusAvgAggregateOutputType | null
  _sum: LrStatusSumAggregateOutputType | null
  _min: LrStatusMinAggregateOutputType | null
  _max: LrStatusMaxAggregateOutputType | null
}

export type LrStatusAvgAggregateOutputType = {
  waiting: number | null
  normal: number | null
  abnormal: number | null
  miscarriage: number | null
  notDelivered: number | null
}

export type LrStatusSumAggregateOutputType = {
  waiting: number | null
  normal: number | null
  abnormal: number | null
  miscarriage: number | null
  notDelivered: number | null
}

export type LrStatusMinAggregateOutputType = {
  id: string | null
  hospitalId: string | null
  waiting: number | null
  normal: number | null
  abnormal: number | null
  miscarriage: number | null
  notDelivered: number | null
}

export type LrStatusMaxAggregateOutputType = {
  id: string | null
  hospitalId: string | null
  waiting: number | null
  normal: number | null
  abnormal: number | null
  miscarriage: number | null
  notDelivered: number | null
}

export type LrStatusCountAggregateOutputType = {
  id: number
  hospitalId: number
  waiting: number
  normal: number
  abnormal: number
  miscarriage: number
  notDelivered: number
  _all: number
}


export type LrStatusAvgAggregateInputType = {
  waiting?: true
  normal?: true
  abnormal?: true
  miscarriage?: true
  notDelivered?: true
}

export type LrStatusSumAggregateInputType = {
  waiting?: true
  normal?: true
  abnormal?: true
  miscarriage?: true
  notDelivered?: true
}

export type LrStatusMinAggregateInputType = {
  id?: true
  hospitalId?: true
  waiting?: true
  normal?: true
  abnormal?: true
  miscarriage?: true
  notDelivered?: true
}

export type LrStatusMaxAggregateInputType = {
  id?: true
  hospitalId?: true
  waiting?: true
  normal?: true
  abnormal?: true
  miscarriage?: true
  notDelivered?: true
}

export type LrStatusCountAggregateInputType = {
  id?: true
  hospitalId?: true
  waiting?: true
  normal?: true
  abnormal?: true
  miscarriage?: true
  notDelivered?: true
  _all?: true
}

export type LrStatusAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LrStatus to aggregate.
   */
  where?: Prisma.LrStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LrStatuses to fetch.
   */
  orderBy?: Prisma.LrStatusOrderByWithRelationInput | Prisma.LrStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LrStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LrStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LrStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LrStatuses
  **/
  _count?: true | LrStatusCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LrStatusAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LrStatusSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LrStatusMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LrStatusMaxAggregateInputType
}

export type GetLrStatusAggregateType<T extends LrStatusAggregateArgs> = {
      [P in keyof T & keyof AggregateLrStatus]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLrStatus[P]>
    : Prisma.GetScalarType<T[P], AggregateLrStatus[P]>
}




export type LrStatusGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LrStatusWhereInput
  orderBy?: Prisma.LrStatusOrderByWithAggregationInput | Prisma.LrStatusOrderByWithAggregationInput[]
  by: Prisma.LrStatusScalarFieldEnum[] | Prisma.LrStatusScalarFieldEnum
  having?: Prisma.LrStatusScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LrStatusCountAggregateInputType | true
  _avg?: LrStatusAvgAggregateInputType
  _sum?: LrStatusSumAggregateInputType
  _min?: LrStatusMinAggregateInputType
  _max?: LrStatusMaxAggregateInputType
}

export type LrStatusGroupByOutputType = {
  id: string
  hospitalId: string
  waiting: number
  normal: number
  abnormal: number
  miscarriage: number
  notDelivered: number
  _count: LrStatusCountAggregateOutputType | null
  _avg: LrStatusAvgAggregateOutputType | null
  _sum: LrStatusSumAggregateOutputType | null
  _min: LrStatusMinAggregateOutputType | null
  _max: LrStatusMaxAggregateOutputType | null
}

type GetLrStatusGroupByPayload<T extends LrStatusGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LrStatusGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LrStatusGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LrStatusGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LrStatusGroupByOutputType[P]>
      }
    >
  >



export type LrStatusWhereInput = {
  AND?: Prisma.LrStatusWhereInput | Prisma.LrStatusWhereInput[]
  OR?: Prisma.LrStatusWhereInput[]
  NOT?: Prisma.LrStatusWhereInput | Prisma.LrStatusWhereInput[]
  id?: Prisma.StringFilter<"LrStatus"> | string
  hospitalId?: Prisma.StringFilter<"LrStatus"> | string
  waiting?: Prisma.IntFilter<"LrStatus"> | number
  normal?: Prisma.IntFilter<"LrStatus"> | number
  abnormal?: Prisma.IntFilter<"LrStatus"> | number
  miscarriage?: Prisma.IntFilter<"LrStatus"> | number
  notDelivered?: Prisma.IntFilter<"LrStatus"> | number
  hospital?: Prisma.XOR<Prisma.HospitalScalarRelationFilter, Prisma.HospitalWhereInput>
}

export type LrStatusOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  waiting?: Prisma.SortOrder
  normal?: Prisma.SortOrder
  abnormal?: Prisma.SortOrder
  miscarriage?: Prisma.SortOrder
  notDelivered?: Prisma.SortOrder
  hospital?: Prisma.HospitalOrderByWithRelationInput
}

export type LrStatusWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  hospitalId?: string
  AND?: Prisma.LrStatusWhereInput | Prisma.LrStatusWhereInput[]
  OR?: Prisma.LrStatusWhereInput[]
  NOT?: Prisma.LrStatusWhereInput | Prisma.LrStatusWhereInput[]
  waiting?: Prisma.IntFilter<"LrStatus"> | number
  normal?: Prisma.IntFilter<"LrStatus"> | number
  abnormal?: Prisma.IntFilter<"LrStatus"> | number
  miscarriage?: Prisma.IntFilter<"LrStatus"> | number
  notDelivered?: Prisma.IntFilter<"LrStatus"> | number
  hospital?: Prisma.XOR<Prisma.HospitalScalarRelationFilter, Prisma.HospitalWhereInput>
}, "id" | "hospitalId">

export type LrStatusOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  waiting?: Prisma.SortOrder
  normal?: Prisma.SortOrder
  abnormal?: Prisma.SortOrder
  miscarriage?: Prisma.SortOrder
  notDelivered?: Prisma.SortOrder
  _count?: Prisma.LrStatusCountOrderByAggregateInput
  _avg?: Prisma.LrStatusAvgOrderByAggregateInput
  _max?: Prisma.LrStatusMaxOrderByAggregateInput
  _min?: Prisma.LrStatusMinOrderByAggregateInput
  _sum?: Prisma.LrStatusSumOrderByAggregateInput
}

export type LrStatusScalarWhereWithAggregatesInput = {
  AND?: Prisma.LrStatusScalarWhereWithAggregatesInput | Prisma.LrStatusScalarWhereWithAggregatesInput[]
  OR?: Prisma.LrStatusScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LrStatusScalarWhereWithAggregatesInput | Prisma.LrStatusScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LrStatus"> | string
  hospitalId?: Prisma.StringWithAggregatesFilter<"LrStatus"> | string
  waiting?: Prisma.IntWithAggregatesFilter<"LrStatus"> | number
  normal?: Prisma.IntWithAggregatesFilter<"LrStatus"> | number
  abnormal?: Prisma.IntWithAggregatesFilter<"LrStatus"> | number
  miscarriage?: Prisma.IntWithAggregatesFilter<"LrStatus"> | number
  notDelivered?: Prisma.IntWithAggregatesFilter<"LrStatus"> | number
}

export type LrStatusCreateInput = {
  id?: string
  waiting: number
  normal: number
  abnormal: number
  miscarriage: number
  notDelivered: number
  hospital: Prisma.HospitalCreateNestedOneWithoutLrStatusInput
}

export type LrStatusUncheckedCreateInput = {
  id?: string
  hospitalId: string
  waiting: number
  normal: number
  abnormal: number
  miscarriage: number
  notDelivered: number
}

export type LrStatusUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  waiting?: Prisma.IntFieldUpdateOperationsInput | number
  normal?: Prisma.IntFieldUpdateOperationsInput | number
  abnormal?: Prisma.IntFieldUpdateOperationsInput | number
  miscarriage?: Prisma.IntFieldUpdateOperationsInput | number
  notDelivered?: Prisma.IntFieldUpdateOperationsInput | number
  hospital?: Prisma.HospitalUpdateOneRequiredWithoutLrStatusNestedInput
}

export type LrStatusUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hospitalId?: Prisma.StringFieldUpdateOperationsInput | string
  waiting?: Prisma.IntFieldUpdateOperationsInput | number
  normal?: Prisma.IntFieldUpdateOperationsInput | number
  abnormal?: Prisma.IntFieldUpdateOperationsInput | number
  miscarriage?: Prisma.IntFieldUpdateOperationsInput | number
  notDelivered?: Prisma.IntFieldUpdateOperationsInput | number
}

export type LrStatusCreateManyInput = {
  id?: string
  hospitalId: string
  waiting: number
  normal: number
  abnormal: number
  miscarriage: number
  notDelivered: number
}

export type LrStatusUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  waiting?: Prisma.IntFieldUpdateOperationsInput | number
  normal?: Prisma.IntFieldUpdateOperationsInput | number
  abnormal?: Prisma.IntFieldUpdateOperationsInput | number
  miscarriage?: Prisma.IntFieldUpdateOperationsInput | number
  notDelivered?: Prisma.IntFieldUpdateOperationsInput | number
}

export type LrStatusUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hospitalId?: Prisma.StringFieldUpdateOperationsInput | string
  waiting?: Prisma.IntFieldUpdateOperationsInput | number
  normal?: Prisma.IntFieldUpdateOperationsInput | number
  abnormal?: Prisma.IntFieldUpdateOperationsInput | number
  miscarriage?: Prisma.IntFieldUpdateOperationsInput | number
  notDelivered?: Prisma.IntFieldUpdateOperationsInput | number
}

export type LrStatusNullableScalarRelationFilter = {
  is?: Prisma.LrStatusWhereInput | null
  isNot?: Prisma.LrStatusWhereInput | null
}

export type LrStatusCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  waiting?: Prisma.SortOrder
  normal?: Prisma.SortOrder
  abnormal?: Prisma.SortOrder
  miscarriage?: Prisma.SortOrder
  notDelivered?: Prisma.SortOrder
}

export type LrStatusAvgOrderByAggregateInput = {
  waiting?: Prisma.SortOrder
  normal?: Prisma.SortOrder
  abnormal?: Prisma.SortOrder
  miscarriage?: Prisma.SortOrder
  notDelivered?: Prisma.SortOrder
}

export type LrStatusMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  waiting?: Prisma.SortOrder
  normal?: Prisma.SortOrder
  abnormal?: Prisma.SortOrder
  miscarriage?: Prisma.SortOrder
  notDelivered?: Prisma.SortOrder
}

export type LrStatusMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  waiting?: Prisma.SortOrder
  normal?: Prisma.SortOrder
  abnormal?: Prisma.SortOrder
  miscarriage?: Prisma.SortOrder
  notDelivered?: Prisma.SortOrder
}

export type LrStatusSumOrderByAggregateInput = {
  waiting?: Prisma.SortOrder
  normal?: Prisma.SortOrder
  abnormal?: Prisma.SortOrder
  miscarriage?: Prisma.SortOrder
  notDelivered?: Prisma.SortOrder
}

export type LrStatusCreateNestedOneWithoutHospitalInput = {
  create?: Prisma.XOR<Prisma.LrStatusCreateWithoutHospitalInput, Prisma.LrStatusUncheckedCreateWithoutHospitalInput>
  connectOrCreate?: Prisma.LrStatusCreateOrConnectWithoutHospitalInput
  connect?: Prisma.LrStatusWhereUniqueInput
}

export type LrStatusUncheckedCreateNestedOneWithoutHospitalInput = {
  create?: Prisma.XOR<Prisma.LrStatusCreateWithoutHospitalInput, Prisma.LrStatusUncheckedCreateWithoutHospitalInput>
  connectOrCreate?: Prisma.LrStatusCreateOrConnectWithoutHospitalInput
  connect?: Prisma.LrStatusWhereUniqueInput
}

export type LrStatusUpdateOneWithoutHospitalNestedInput = {
  create?: Prisma.XOR<Prisma.LrStatusCreateWithoutHospitalInput, Prisma.LrStatusUncheckedCreateWithoutHospitalInput>
  connectOrCreate?: Prisma.LrStatusCreateOrConnectWithoutHospitalInput
  upsert?: Prisma.LrStatusUpsertWithoutHospitalInput
  disconnect?: Prisma.LrStatusWhereInput | boolean
  delete?: Prisma.LrStatusWhereInput | boolean
  connect?: Prisma.LrStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LrStatusUpdateToOneWithWhereWithoutHospitalInput, Prisma.LrStatusUpdateWithoutHospitalInput>, Prisma.LrStatusUncheckedUpdateWithoutHospitalInput>
}

export type LrStatusUncheckedUpdateOneWithoutHospitalNestedInput = {
  create?: Prisma.XOR<Prisma.LrStatusCreateWithoutHospitalInput, Prisma.LrStatusUncheckedCreateWithoutHospitalInput>
  connectOrCreate?: Prisma.LrStatusCreateOrConnectWithoutHospitalInput
  upsert?: Prisma.LrStatusUpsertWithoutHospitalInput
  disconnect?: Prisma.LrStatusWhereInput | boolean
  delete?: Prisma.LrStatusWhereInput | boolean
  connect?: Prisma.LrStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LrStatusUpdateToOneWithWhereWithoutHospitalInput, Prisma.LrStatusUpdateWithoutHospitalInput>, Prisma.LrStatusUncheckedUpdateWithoutHospitalInput>
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type LrStatusCreateWithoutHospitalInput = {
  id?: string
  waiting: number
  normal: number
  abnormal: number
  miscarriage: number
  notDelivered: number
}

export type LrStatusUncheckedCreateWithoutHospitalInput = {
  id?: string
  waiting: number
  normal: number
  abnormal: number
  miscarriage: number
  notDelivered: number
}

export type LrStatusCreateOrConnectWithoutHospitalInput = {
  where: Prisma.LrStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.LrStatusCreateWithoutHospitalInput, Prisma.LrStatusUncheckedCreateWithoutHospitalInput>
}

export type LrStatusUpsertWithoutHospitalInput = {
  update: Prisma.XOR<Prisma.LrStatusUpdateWithoutHospitalInput, Prisma.LrStatusUncheckedUpdateWithoutHospitalInput>
  create: Prisma.XOR<Prisma.LrStatusCreateWithoutHospitalInput, Prisma.LrStatusUncheckedCreateWithoutHospitalInput>
  where?: Prisma.LrStatusWhereInput
}

export type LrStatusUpdateToOneWithWhereWithoutHospitalInput = {
  where?: Prisma.LrStatusWhereInput
  data: Prisma.XOR<Prisma.LrStatusUpdateWithoutHospitalInput, Prisma.LrStatusUncheckedUpdateWithoutHospitalInput>
}

export type LrStatusUpdateWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  waiting?: Prisma.IntFieldUpdateOperationsInput | number
  normal?: Prisma.IntFieldUpdateOperationsInput | number
  abnormal?: Prisma.IntFieldUpdateOperationsInput | number
  miscarriage?: Prisma.IntFieldUpdateOperationsInput | number
  notDelivered?: Prisma.IntFieldUpdateOperationsInput | number
}

export type LrStatusUncheckedUpdateWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  waiting?: Prisma.IntFieldUpdateOperationsInput | number
  normal?: Prisma.IntFieldUpdateOperationsInput | number
  abnormal?: Prisma.IntFieldUpdateOperationsInput | number
  miscarriage?: Prisma.IntFieldUpdateOperationsInput | number
  notDelivered?: Prisma.IntFieldUpdateOperationsInput | number
}



export type LrStatusSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  waiting?: boolean
  normal?: boolean
  abnormal?: boolean
  miscarriage?: boolean
  notDelivered?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lrStatus"]>

export type LrStatusSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  waiting?: boolean
  normal?: boolean
  abnormal?: boolean
  miscarriage?: boolean
  notDelivered?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lrStatus"]>

export type LrStatusSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  waiting?: boolean
  normal?: boolean
  abnormal?: boolean
  miscarriage?: boolean
  notDelivered?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lrStatus"]>

export type LrStatusSelectScalar = {
  id?: boolean
  hospitalId?: boolean
  waiting?: boolean
  normal?: boolean
  abnormal?: boolean
  miscarriage?: boolean
  notDelivered?: boolean
}

export type LrStatusOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "hospitalId" | "waiting" | "normal" | "abnormal" | "miscarriage" | "notDelivered", ExtArgs["result"]["lrStatus"]>
export type LrStatusInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}
export type LrStatusIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}
export type LrStatusIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}

export type $LrStatusPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LrStatus"
  objects: {
    hospital: Prisma.$HospitalPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    hospitalId: string
    waiting: number
    normal: number
    abnormal: number
    miscarriage: number
    notDelivered: number
  }, ExtArgs["result"]["lrStatus"]>
  composites: {}
}

export type LrStatusGetPayload<S extends boolean | null | undefined | LrStatusDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LrStatusPayload, S>

export type LrStatusCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LrStatusFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LrStatusCountAggregateInputType | true
  }

export interface LrStatusDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LrStatus'], meta: { name: 'LrStatus' } }
  /**
   * Find zero or one LrStatus that matches the filter.
   * @param {LrStatusFindUniqueArgs} args - Arguments to find a LrStatus
   * @example
   * // Get one LrStatus
   * const lrStatus = await prisma.lrStatus.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LrStatusFindUniqueArgs>(args: Prisma.SelectSubset<T, LrStatusFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LrStatusClient<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LrStatus that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LrStatusFindUniqueOrThrowArgs} args - Arguments to find a LrStatus
   * @example
   * // Get one LrStatus
   * const lrStatus = await prisma.lrStatus.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LrStatusFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LrStatusFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LrStatusClient<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LrStatus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LrStatusFindFirstArgs} args - Arguments to find a LrStatus
   * @example
   * // Get one LrStatus
   * const lrStatus = await prisma.lrStatus.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LrStatusFindFirstArgs>(args?: Prisma.SelectSubset<T, LrStatusFindFirstArgs<ExtArgs>>): Prisma.Prisma__LrStatusClient<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LrStatus that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LrStatusFindFirstOrThrowArgs} args - Arguments to find a LrStatus
   * @example
   * // Get one LrStatus
   * const lrStatus = await prisma.lrStatus.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LrStatusFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LrStatusFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LrStatusClient<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LrStatuses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LrStatusFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LrStatuses
   * const lrStatuses = await prisma.lrStatus.findMany()
   * 
   * // Get first 10 LrStatuses
   * const lrStatuses = await prisma.lrStatus.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const lrStatusWithIdOnly = await prisma.lrStatus.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LrStatusFindManyArgs>(args?: Prisma.SelectSubset<T, LrStatusFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LrStatus.
   * @param {LrStatusCreateArgs} args - Arguments to create a LrStatus.
   * @example
   * // Create one LrStatus
   * const LrStatus = await prisma.lrStatus.create({
   *   data: {
   *     // ... data to create a LrStatus
   *   }
   * })
   * 
   */
  create<T extends LrStatusCreateArgs>(args: Prisma.SelectSubset<T, LrStatusCreateArgs<ExtArgs>>): Prisma.Prisma__LrStatusClient<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LrStatuses.
   * @param {LrStatusCreateManyArgs} args - Arguments to create many LrStatuses.
   * @example
   * // Create many LrStatuses
   * const lrStatus = await prisma.lrStatus.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LrStatusCreateManyArgs>(args?: Prisma.SelectSubset<T, LrStatusCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LrStatuses and returns the data saved in the database.
   * @param {LrStatusCreateManyAndReturnArgs} args - Arguments to create many LrStatuses.
   * @example
   * // Create many LrStatuses
   * const lrStatus = await prisma.lrStatus.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LrStatuses and only return the `id`
   * const lrStatusWithIdOnly = await prisma.lrStatus.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LrStatusCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LrStatusCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LrStatus.
   * @param {LrStatusDeleteArgs} args - Arguments to delete one LrStatus.
   * @example
   * // Delete one LrStatus
   * const LrStatus = await prisma.lrStatus.delete({
   *   where: {
   *     // ... filter to delete one LrStatus
   *   }
   * })
   * 
   */
  delete<T extends LrStatusDeleteArgs>(args: Prisma.SelectSubset<T, LrStatusDeleteArgs<ExtArgs>>): Prisma.Prisma__LrStatusClient<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LrStatus.
   * @param {LrStatusUpdateArgs} args - Arguments to update one LrStatus.
   * @example
   * // Update one LrStatus
   * const lrStatus = await prisma.lrStatus.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LrStatusUpdateArgs>(args: Prisma.SelectSubset<T, LrStatusUpdateArgs<ExtArgs>>): Prisma.Prisma__LrStatusClient<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LrStatuses.
   * @param {LrStatusDeleteManyArgs} args - Arguments to filter LrStatuses to delete.
   * @example
   * // Delete a few LrStatuses
   * const { count } = await prisma.lrStatus.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LrStatusDeleteManyArgs>(args?: Prisma.SelectSubset<T, LrStatusDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LrStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LrStatusUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LrStatuses
   * const lrStatus = await prisma.lrStatus.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LrStatusUpdateManyArgs>(args: Prisma.SelectSubset<T, LrStatusUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LrStatuses and returns the data updated in the database.
   * @param {LrStatusUpdateManyAndReturnArgs} args - Arguments to update many LrStatuses.
   * @example
   * // Update many LrStatuses
   * const lrStatus = await prisma.lrStatus.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LrStatuses and only return the `id`
   * const lrStatusWithIdOnly = await prisma.lrStatus.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LrStatusUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LrStatusUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LrStatus.
   * @param {LrStatusUpsertArgs} args - Arguments to update or create a LrStatus.
   * @example
   * // Update or create a LrStatus
   * const lrStatus = await prisma.lrStatus.upsert({
   *   create: {
   *     // ... data to create a LrStatus
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LrStatus we want to update
   *   }
   * })
   */
  upsert<T extends LrStatusUpsertArgs>(args: Prisma.SelectSubset<T, LrStatusUpsertArgs<ExtArgs>>): Prisma.Prisma__LrStatusClient<runtime.Types.Result.GetResult<Prisma.$LrStatusPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LrStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LrStatusCountArgs} args - Arguments to filter LrStatuses to count.
   * @example
   * // Count the number of LrStatuses
   * const count = await prisma.lrStatus.count({
   *   where: {
   *     // ... the filter for the LrStatuses we want to count
   *   }
   * })
  **/
  count<T extends LrStatusCountArgs>(
    args?: Prisma.Subset<T, LrStatusCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LrStatusCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LrStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LrStatusAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LrStatusAggregateArgs>(args: Prisma.Subset<T, LrStatusAggregateArgs>): Prisma.PrismaPromise<GetLrStatusAggregateType<T>>

  /**
   * Group by LrStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LrStatusGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LrStatusGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LrStatusGroupByArgs['orderBy'] }
      : { orderBy?: LrStatusGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LrStatusGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLrStatusGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LrStatus model
 */
readonly fields: LrStatusFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LrStatus.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LrStatusClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  hospital<T extends Prisma.HospitalDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HospitalDefaultArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LrStatus model
 */
export interface LrStatusFieldRefs {
  readonly id: Prisma.FieldRef<"LrStatus", 'String'>
  readonly hospitalId: Prisma.FieldRef<"LrStatus", 'String'>
  readonly waiting: Prisma.FieldRef<"LrStatus", 'Int'>
  readonly normal: Prisma.FieldRef<"LrStatus", 'Int'>
  readonly abnormal: Prisma.FieldRef<"LrStatus", 'Int'>
  readonly miscarriage: Prisma.FieldRef<"LrStatus", 'Int'>
  readonly notDelivered: Prisma.FieldRef<"LrStatus", 'Int'>
}
    

// Custom InputTypes
/**
 * LrStatus findUnique
 */
export type LrStatusFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusInclude<ExtArgs> | null
  /**
   * Filter, which LrStatus to fetch.
   */
  where: Prisma.LrStatusWhereUniqueInput
}

/**
 * LrStatus findUniqueOrThrow
 */
export type LrStatusFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusInclude<ExtArgs> | null
  /**
   * Filter, which LrStatus to fetch.
   */
  where: Prisma.LrStatusWhereUniqueInput
}

/**
 * LrStatus findFirst
 */
export type LrStatusFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusInclude<ExtArgs> | null
  /**
   * Filter, which LrStatus to fetch.
   */
  where?: Prisma.LrStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LrStatuses to fetch.
   */
  orderBy?: Prisma.LrStatusOrderByWithRelationInput | Prisma.LrStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LrStatuses.
   */
  cursor?: Prisma.LrStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LrStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LrStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LrStatuses.
   */
  distinct?: Prisma.LrStatusScalarFieldEnum | Prisma.LrStatusScalarFieldEnum[]
}

/**
 * LrStatus findFirstOrThrow
 */
export type LrStatusFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusInclude<ExtArgs> | null
  /**
   * Filter, which LrStatus to fetch.
   */
  where?: Prisma.LrStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LrStatuses to fetch.
   */
  orderBy?: Prisma.LrStatusOrderByWithRelationInput | Prisma.LrStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LrStatuses.
   */
  cursor?: Prisma.LrStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LrStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LrStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LrStatuses.
   */
  distinct?: Prisma.LrStatusScalarFieldEnum | Prisma.LrStatusScalarFieldEnum[]
}

/**
 * LrStatus findMany
 */
export type LrStatusFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusInclude<ExtArgs> | null
  /**
   * Filter, which LrStatuses to fetch.
   */
  where?: Prisma.LrStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LrStatuses to fetch.
   */
  orderBy?: Prisma.LrStatusOrderByWithRelationInput | Prisma.LrStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LrStatuses.
   */
  cursor?: Prisma.LrStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LrStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LrStatuses.
   */
  skip?: number
  distinct?: Prisma.LrStatusScalarFieldEnum | Prisma.LrStatusScalarFieldEnum[]
}

/**
 * LrStatus create
 */
export type LrStatusCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusInclude<ExtArgs> | null
  /**
   * The data needed to create a LrStatus.
   */
  data: Prisma.XOR<Prisma.LrStatusCreateInput, Prisma.LrStatusUncheckedCreateInput>
}

/**
 * LrStatus createMany
 */
export type LrStatusCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LrStatuses.
   */
  data: Prisma.LrStatusCreateManyInput | Prisma.LrStatusCreateManyInput[]
}

/**
 * LrStatus createManyAndReturn
 */
export type LrStatusCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * The data used to create many LrStatuses.
   */
  data: Prisma.LrStatusCreateManyInput | Prisma.LrStatusCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LrStatus update
 */
export type LrStatusUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusInclude<ExtArgs> | null
  /**
   * The data needed to update a LrStatus.
   */
  data: Prisma.XOR<Prisma.LrStatusUpdateInput, Prisma.LrStatusUncheckedUpdateInput>
  /**
   * Choose, which LrStatus to update.
   */
  where: Prisma.LrStatusWhereUniqueInput
}

/**
 * LrStatus updateMany
 */
export type LrStatusUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LrStatuses.
   */
  data: Prisma.XOR<Prisma.LrStatusUpdateManyMutationInput, Prisma.LrStatusUncheckedUpdateManyInput>
  /**
   * Filter which LrStatuses to update
   */
  where?: Prisma.LrStatusWhereInput
  /**
   * Limit how many LrStatuses to update.
   */
  limit?: number
}

/**
 * LrStatus updateManyAndReturn
 */
export type LrStatusUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * The data used to update LrStatuses.
   */
  data: Prisma.XOR<Prisma.LrStatusUpdateManyMutationInput, Prisma.LrStatusUncheckedUpdateManyInput>
  /**
   * Filter which LrStatuses to update
   */
  where?: Prisma.LrStatusWhereInput
  /**
   * Limit how many LrStatuses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LrStatus upsert
 */
export type LrStatusUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusInclude<ExtArgs> | null
  /**
   * The filter to search for the LrStatus to update in case it exists.
   */
  where: Prisma.LrStatusWhereUniqueInput
  /**
   * In case the LrStatus found by the `where` argument doesn't exist, create a new LrStatus with this data.
   */
  create: Prisma.XOR<Prisma.LrStatusCreateInput, Prisma.LrStatusUncheckedCreateInput>
  /**
   * In case the LrStatus was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LrStatusUpdateInput, Prisma.LrStatusUncheckedUpdateInput>
}

/**
 * LrStatus delete
 */
export type LrStatusDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusInclude<ExtArgs> | null
  /**
   * Filter which LrStatus to delete.
   */
  where: Prisma.LrStatusWhereUniqueInput
}

/**
 * LrStatus deleteMany
 */
export type LrStatusDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LrStatuses to delete
   */
  where?: Prisma.LrStatusWhereInput
  /**
   * Limit how many LrStatuses to delete.
   */
  limit?: number
}

/**
 * LrStatus without action
 */
export type LrStatusDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LrStatus
   */
  select?: Prisma.LrStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LrStatus
   */
  omit?: Prisma.LrStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LrStatusInclude<ExtArgs> | null
}
