
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OrStat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model OrStat
 * 
 */
export type OrStatModel = runtime.Types.Result.DefaultSelection<Prisma.$OrStatPayload>

export type AggregateOrStat = {
  _count: OrStatCountAggregateOutputType | null
  _avg: OrStatAvgAggregateOutputType | null
  _sum: OrStatSumAggregateOutputType | null
  _min: OrStatMinAggregateOutputType | null
  _max: OrStatMaxAggregateOutputType | null
}

export type OrStatAvgAggregateOutputType = {
  totalRooms: number | null
  activeSurgeries: number | null
  scheduledToday: number | null
  emergencyCases: number | null
  availableRooms: number | null
}

export type OrStatSumAggregateOutputType = {
  totalRooms: number | null
  activeSurgeries: number | null
  scheduledToday: number | null
  emergencyCases: number | null
  availableRooms: number | null
}

export type OrStatMinAggregateOutputType = {
  id: string | null
  hospitalId: string | null
  totalRooms: number | null
  activeSurgeries: number | null
  scheduledToday: number | null
  emergencyCases: number | null
  availableRooms: number | null
}

export type OrStatMaxAggregateOutputType = {
  id: string | null
  hospitalId: string | null
  totalRooms: number | null
  activeSurgeries: number | null
  scheduledToday: number | null
  emergencyCases: number | null
  availableRooms: number | null
}

export type OrStatCountAggregateOutputType = {
  id: number
  hospitalId: number
  totalRooms: number
  activeSurgeries: number
  scheduledToday: number
  emergencyCases: number
  availableRooms: number
  _all: number
}


export type OrStatAvgAggregateInputType = {
  totalRooms?: true
  activeSurgeries?: true
  scheduledToday?: true
  emergencyCases?: true
  availableRooms?: true
}

export type OrStatSumAggregateInputType = {
  totalRooms?: true
  activeSurgeries?: true
  scheduledToday?: true
  emergencyCases?: true
  availableRooms?: true
}

export type OrStatMinAggregateInputType = {
  id?: true
  hospitalId?: true
  totalRooms?: true
  activeSurgeries?: true
  scheduledToday?: true
  emergencyCases?: true
  availableRooms?: true
}

export type OrStatMaxAggregateInputType = {
  id?: true
  hospitalId?: true
  totalRooms?: true
  activeSurgeries?: true
  scheduledToday?: true
  emergencyCases?: true
  availableRooms?: true
}

export type OrStatCountAggregateInputType = {
  id?: true
  hospitalId?: true
  totalRooms?: true
  activeSurgeries?: true
  scheduledToday?: true
  emergencyCases?: true
  availableRooms?: true
  _all?: true
}

export type OrStatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrStat to aggregate.
   */
  where?: Prisma.OrStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrStats to fetch.
   */
  orderBy?: Prisma.OrStatOrderByWithRelationInput | Prisma.OrStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OrStats
  **/
  _count?: true | OrStatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OrStatAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OrStatSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrStatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrStatMaxAggregateInputType
}

export type GetOrStatAggregateType<T extends OrStatAggregateArgs> = {
      [P in keyof T & keyof AggregateOrStat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrStat[P]>
    : Prisma.GetScalarType<T[P], AggregateOrStat[P]>
}




export type OrStatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrStatWhereInput
  orderBy?: Prisma.OrStatOrderByWithAggregationInput | Prisma.OrStatOrderByWithAggregationInput[]
  by: Prisma.OrStatScalarFieldEnum[] | Prisma.OrStatScalarFieldEnum
  having?: Prisma.OrStatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrStatCountAggregateInputType | true
  _avg?: OrStatAvgAggregateInputType
  _sum?: OrStatSumAggregateInputType
  _min?: OrStatMinAggregateInputType
  _max?: OrStatMaxAggregateInputType
}

export type OrStatGroupByOutputType = {
  id: string
  hospitalId: string
  totalRooms: number
  activeSurgeries: number
  scheduledToday: number
  emergencyCases: number
  availableRooms: number
  _count: OrStatCountAggregateOutputType | null
  _avg: OrStatAvgAggregateOutputType | null
  _sum: OrStatSumAggregateOutputType | null
  _min: OrStatMinAggregateOutputType | null
  _max: OrStatMaxAggregateOutputType | null
}

type GetOrStatGroupByPayload<T extends OrStatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrStatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrStatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrStatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrStatGroupByOutputType[P]>
      }
    >
  >



export type OrStatWhereInput = {
  AND?: Prisma.OrStatWhereInput | Prisma.OrStatWhereInput[]
  OR?: Prisma.OrStatWhereInput[]
  NOT?: Prisma.OrStatWhereInput | Prisma.OrStatWhereInput[]
  id?: Prisma.StringFilter<"OrStat"> | string
  hospitalId?: Prisma.StringFilter<"OrStat"> | string
  totalRooms?: Prisma.IntFilter<"OrStat"> | number
  activeSurgeries?: Prisma.IntFilter<"OrStat"> | number
  scheduledToday?: Prisma.IntFilter<"OrStat"> | number
  emergencyCases?: Prisma.IntFilter<"OrStat"> | number
  availableRooms?: Prisma.IntFilter<"OrStat"> | number
  hospital?: Prisma.XOR<Prisma.HospitalScalarRelationFilter, Prisma.HospitalWhereInput>
}

export type OrStatOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  totalRooms?: Prisma.SortOrder
  activeSurgeries?: Prisma.SortOrder
  scheduledToday?: Prisma.SortOrder
  emergencyCases?: Prisma.SortOrder
  availableRooms?: Prisma.SortOrder
  hospital?: Prisma.HospitalOrderByWithRelationInput
}

export type OrStatWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  hospitalId?: string
  AND?: Prisma.OrStatWhereInput | Prisma.OrStatWhereInput[]
  OR?: Prisma.OrStatWhereInput[]
  NOT?: Prisma.OrStatWhereInput | Prisma.OrStatWhereInput[]
  totalRooms?: Prisma.IntFilter<"OrStat"> | number
  activeSurgeries?: Prisma.IntFilter<"OrStat"> | number
  scheduledToday?: Prisma.IntFilter<"OrStat"> | number
  emergencyCases?: Prisma.IntFilter<"OrStat"> | number
  availableRooms?: Prisma.IntFilter<"OrStat"> | number
  hospital?: Prisma.XOR<Prisma.HospitalScalarRelationFilter, Prisma.HospitalWhereInput>
}, "id" | "hospitalId">

export type OrStatOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  totalRooms?: Prisma.SortOrder
  activeSurgeries?: Prisma.SortOrder
  scheduledToday?: Prisma.SortOrder
  emergencyCases?: Prisma.SortOrder
  availableRooms?: Prisma.SortOrder
  _count?: Prisma.OrStatCountOrderByAggregateInput
  _avg?: Prisma.OrStatAvgOrderByAggregateInput
  _max?: Prisma.OrStatMaxOrderByAggregateInput
  _min?: Prisma.OrStatMinOrderByAggregateInput
  _sum?: Prisma.OrStatSumOrderByAggregateInput
}

export type OrStatScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrStatScalarWhereWithAggregatesInput | Prisma.OrStatScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrStatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrStatScalarWhereWithAggregatesInput | Prisma.OrStatScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OrStat"> | string
  hospitalId?: Prisma.StringWithAggregatesFilter<"OrStat"> | string
  totalRooms?: Prisma.IntWithAggregatesFilter<"OrStat"> | number
  activeSurgeries?: Prisma.IntWithAggregatesFilter<"OrStat"> | number
  scheduledToday?: Prisma.IntWithAggregatesFilter<"OrStat"> | number
  emergencyCases?: Prisma.IntWithAggregatesFilter<"OrStat"> | number
  availableRooms?: Prisma.IntWithAggregatesFilter<"OrStat"> | number
}

export type OrStatCreateInput = {
  id?: string
  totalRooms: number
  activeSurgeries: number
  scheduledToday: number
  emergencyCases: number
  availableRooms: number
  hospital: Prisma.HospitalCreateNestedOneWithoutOrStatInput
}

export type OrStatUncheckedCreateInput = {
  id?: string
  hospitalId: string
  totalRooms: number
  activeSurgeries: number
  scheduledToday: number
  emergencyCases: number
  availableRooms: number
}

export type OrStatUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  totalRooms?: Prisma.IntFieldUpdateOperationsInput | number
  activeSurgeries?: Prisma.IntFieldUpdateOperationsInput | number
  scheduledToday?: Prisma.IntFieldUpdateOperationsInput | number
  emergencyCases?: Prisma.IntFieldUpdateOperationsInput | number
  availableRooms?: Prisma.IntFieldUpdateOperationsInput | number
  hospital?: Prisma.HospitalUpdateOneRequiredWithoutOrStatNestedInput
}

export type OrStatUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hospitalId?: Prisma.StringFieldUpdateOperationsInput | string
  totalRooms?: Prisma.IntFieldUpdateOperationsInput | number
  activeSurgeries?: Prisma.IntFieldUpdateOperationsInput | number
  scheduledToday?: Prisma.IntFieldUpdateOperationsInput | number
  emergencyCases?: Prisma.IntFieldUpdateOperationsInput | number
  availableRooms?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OrStatCreateManyInput = {
  id?: string
  hospitalId: string
  totalRooms: number
  activeSurgeries: number
  scheduledToday: number
  emergencyCases: number
  availableRooms: number
}

export type OrStatUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  totalRooms?: Prisma.IntFieldUpdateOperationsInput | number
  activeSurgeries?: Prisma.IntFieldUpdateOperationsInput | number
  scheduledToday?: Prisma.IntFieldUpdateOperationsInput | number
  emergencyCases?: Prisma.IntFieldUpdateOperationsInput | number
  availableRooms?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OrStatUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hospitalId?: Prisma.StringFieldUpdateOperationsInput | string
  totalRooms?: Prisma.IntFieldUpdateOperationsInput | number
  activeSurgeries?: Prisma.IntFieldUpdateOperationsInput | number
  scheduledToday?: Prisma.IntFieldUpdateOperationsInput | number
  emergencyCases?: Prisma.IntFieldUpdateOperationsInput | number
  availableRooms?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OrStatNullableScalarRelationFilter = {
  is?: Prisma.OrStatWhereInput | null
  isNot?: Prisma.OrStatWhereInput | null
}

export type OrStatCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  totalRooms?: Prisma.SortOrder
  activeSurgeries?: Prisma.SortOrder
  scheduledToday?: Prisma.SortOrder
  emergencyCases?: Prisma.SortOrder
  availableRooms?: Prisma.SortOrder
}

export type OrStatAvgOrderByAggregateInput = {
  totalRooms?: Prisma.SortOrder
  activeSurgeries?: Prisma.SortOrder
  scheduledToday?: Prisma.SortOrder
  emergencyCases?: Prisma.SortOrder
  availableRooms?: Prisma.SortOrder
}

export type OrStatMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  totalRooms?: Prisma.SortOrder
  activeSurgeries?: Prisma.SortOrder
  scheduledToday?: Prisma.SortOrder
  emergencyCases?: Prisma.SortOrder
  availableRooms?: Prisma.SortOrder
}

export type OrStatMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  totalRooms?: Prisma.SortOrder
  activeSurgeries?: Prisma.SortOrder
  scheduledToday?: Prisma.SortOrder
  emergencyCases?: Prisma.SortOrder
  availableRooms?: Prisma.SortOrder
}

export type OrStatSumOrderByAggregateInput = {
  totalRooms?: Prisma.SortOrder
  activeSurgeries?: Prisma.SortOrder
  scheduledToday?: Prisma.SortOrder
  emergencyCases?: Prisma.SortOrder
  availableRooms?: Prisma.SortOrder
}

export type OrStatCreateNestedOneWithoutHospitalInput = {
  create?: Prisma.XOR<Prisma.OrStatCreateWithoutHospitalInput, Prisma.OrStatUncheckedCreateWithoutHospitalInput>
  connectOrCreate?: Prisma.OrStatCreateOrConnectWithoutHospitalInput
  connect?: Prisma.OrStatWhereUniqueInput
}

export type OrStatUncheckedCreateNestedOneWithoutHospitalInput = {
  create?: Prisma.XOR<Prisma.OrStatCreateWithoutHospitalInput, Prisma.OrStatUncheckedCreateWithoutHospitalInput>
  connectOrCreate?: Prisma.OrStatCreateOrConnectWithoutHospitalInput
  connect?: Prisma.OrStatWhereUniqueInput
}

export type OrStatUpdateOneWithoutHospitalNestedInput = {
  create?: Prisma.XOR<Prisma.OrStatCreateWithoutHospitalInput, Prisma.OrStatUncheckedCreateWithoutHospitalInput>
  connectOrCreate?: Prisma.OrStatCreateOrConnectWithoutHospitalInput
  upsert?: Prisma.OrStatUpsertWithoutHospitalInput
  disconnect?: Prisma.OrStatWhereInput | boolean
  delete?: Prisma.OrStatWhereInput | boolean
  connect?: Prisma.OrStatWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrStatUpdateToOneWithWhereWithoutHospitalInput, Prisma.OrStatUpdateWithoutHospitalInput>, Prisma.OrStatUncheckedUpdateWithoutHospitalInput>
}

export type OrStatUncheckedUpdateOneWithoutHospitalNestedInput = {
  create?: Prisma.XOR<Prisma.OrStatCreateWithoutHospitalInput, Prisma.OrStatUncheckedCreateWithoutHospitalInput>
  connectOrCreate?: Prisma.OrStatCreateOrConnectWithoutHospitalInput
  upsert?: Prisma.OrStatUpsertWithoutHospitalInput
  disconnect?: Prisma.OrStatWhereInput | boolean
  delete?: Prisma.OrStatWhereInput | boolean
  connect?: Prisma.OrStatWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrStatUpdateToOneWithWhereWithoutHospitalInput, Prisma.OrStatUpdateWithoutHospitalInput>, Prisma.OrStatUncheckedUpdateWithoutHospitalInput>
}

export type OrStatCreateWithoutHospitalInput = {
  id?: string
  totalRooms: number
  activeSurgeries: number
  scheduledToday: number
  emergencyCases: number
  availableRooms: number
}

export type OrStatUncheckedCreateWithoutHospitalInput = {
  id?: string
  totalRooms: number
  activeSurgeries: number
  scheduledToday: number
  emergencyCases: number
  availableRooms: number
}

export type OrStatCreateOrConnectWithoutHospitalInput = {
  where: Prisma.OrStatWhereUniqueInput
  create: Prisma.XOR<Prisma.OrStatCreateWithoutHospitalInput, Prisma.OrStatUncheckedCreateWithoutHospitalInput>
}

export type OrStatUpsertWithoutHospitalInput = {
  update: Prisma.XOR<Prisma.OrStatUpdateWithoutHospitalInput, Prisma.OrStatUncheckedUpdateWithoutHospitalInput>
  create: Prisma.XOR<Prisma.OrStatCreateWithoutHospitalInput, Prisma.OrStatUncheckedCreateWithoutHospitalInput>
  where?: Prisma.OrStatWhereInput
}

export type OrStatUpdateToOneWithWhereWithoutHospitalInput = {
  where?: Prisma.OrStatWhereInput
  data: Prisma.XOR<Prisma.OrStatUpdateWithoutHospitalInput, Prisma.OrStatUncheckedUpdateWithoutHospitalInput>
}

export type OrStatUpdateWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  totalRooms?: Prisma.IntFieldUpdateOperationsInput | number
  activeSurgeries?: Prisma.IntFieldUpdateOperationsInput | number
  scheduledToday?: Prisma.IntFieldUpdateOperationsInput | number
  emergencyCases?: Prisma.IntFieldUpdateOperationsInput | number
  availableRooms?: Prisma.IntFieldUpdateOperationsInput | number
}

export type OrStatUncheckedUpdateWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  totalRooms?: Prisma.IntFieldUpdateOperationsInput | number
  activeSurgeries?: Prisma.IntFieldUpdateOperationsInput | number
  scheduledToday?: Prisma.IntFieldUpdateOperationsInput | number
  emergencyCases?: Prisma.IntFieldUpdateOperationsInput | number
  availableRooms?: Prisma.IntFieldUpdateOperationsInput | number
}



export type OrStatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  totalRooms?: boolean
  activeSurgeries?: boolean
  scheduledToday?: boolean
  emergencyCases?: boolean
  availableRooms?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orStat"]>

export type OrStatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  totalRooms?: boolean
  activeSurgeries?: boolean
  scheduledToday?: boolean
  emergencyCases?: boolean
  availableRooms?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orStat"]>

export type OrStatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  totalRooms?: boolean
  activeSurgeries?: boolean
  scheduledToday?: boolean
  emergencyCases?: boolean
  availableRooms?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orStat"]>

export type OrStatSelectScalar = {
  id?: boolean
  hospitalId?: boolean
  totalRooms?: boolean
  activeSurgeries?: boolean
  scheduledToday?: boolean
  emergencyCases?: boolean
  availableRooms?: boolean
}

export type OrStatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "hospitalId" | "totalRooms" | "activeSurgeries" | "scheduledToday" | "emergencyCases" | "availableRooms", ExtArgs["result"]["orStat"]>
export type OrStatInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}
export type OrStatIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}
export type OrStatIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}

export type $OrStatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OrStat"
  objects: {
    hospital: Prisma.$HospitalPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    hospitalId: string
    totalRooms: number
    activeSurgeries: number
    scheduledToday: number
    emergencyCases: number
    availableRooms: number
  }, ExtArgs["result"]["orStat"]>
  composites: {}
}

export type OrStatGetPayload<S extends boolean | null | undefined | OrStatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrStatPayload, S>

export type OrStatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrStatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrStatCountAggregateInputType | true
  }

export interface OrStatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OrStat'], meta: { name: 'OrStat' } }
  /**
   * Find zero or one OrStat that matches the filter.
   * @param {OrStatFindUniqueArgs} args - Arguments to find a OrStat
   * @example
   * // Get one OrStat
   * const orStat = await prisma.orStat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrStatFindUniqueArgs>(args: Prisma.SelectSubset<T, OrStatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrStatClient<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OrStat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrStatFindUniqueOrThrowArgs} args - Arguments to find a OrStat
   * @example
   * // Get one OrStat
   * const orStat = await prisma.orStat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrStatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrStatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrStatClient<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrStat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrStatFindFirstArgs} args - Arguments to find a OrStat
   * @example
   * // Get one OrStat
   * const orStat = await prisma.orStat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrStatFindFirstArgs>(args?: Prisma.SelectSubset<T, OrStatFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrStatClient<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrStat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrStatFindFirstOrThrowArgs} args - Arguments to find a OrStat
   * @example
   * // Get one OrStat
   * const orStat = await prisma.orStat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrStatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrStatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrStatClient<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OrStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrStatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrStats
   * const orStats = await prisma.orStat.findMany()
   * 
   * // Get first 10 OrStats
   * const orStats = await prisma.orStat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orStatWithIdOnly = await prisma.orStat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrStatFindManyArgs>(args?: Prisma.SelectSubset<T, OrStatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OrStat.
   * @param {OrStatCreateArgs} args - Arguments to create a OrStat.
   * @example
   * // Create one OrStat
   * const OrStat = await prisma.orStat.create({
   *   data: {
   *     // ... data to create a OrStat
   *   }
   * })
   * 
   */
  create<T extends OrStatCreateArgs>(args: Prisma.SelectSubset<T, OrStatCreateArgs<ExtArgs>>): Prisma.Prisma__OrStatClient<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OrStats.
   * @param {OrStatCreateManyArgs} args - Arguments to create many OrStats.
   * @example
   * // Create many OrStats
   * const orStat = await prisma.orStat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrStatCreateManyArgs>(args?: Prisma.SelectSubset<T, OrStatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OrStats and returns the data saved in the database.
   * @param {OrStatCreateManyAndReturnArgs} args - Arguments to create many OrStats.
   * @example
   * // Create many OrStats
   * const orStat = await prisma.orStat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OrStats and only return the `id`
   * const orStatWithIdOnly = await prisma.orStat.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OrStatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OrStatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OrStat.
   * @param {OrStatDeleteArgs} args - Arguments to delete one OrStat.
   * @example
   * // Delete one OrStat
   * const OrStat = await prisma.orStat.delete({
   *   where: {
   *     // ... filter to delete one OrStat
   *   }
   * })
   * 
   */
  delete<T extends OrStatDeleteArgs>(args: Prisma.SelectSubset<T, OrStatDeleteArgs<ExtArgs>>): Prisma.Prisma__OrStatClient<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OrStat.
   * @param {OrStatUpdateArgs} args - Arguments to update one OrStat.
   * @example
   * // Update one OrStat
   * const orStat = await prisma.orStat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrStatUpdateArgs>(args: Prisma.SelectSubset<T, OrStatUpdateArgs<ExtArgs>>): Prisma.Prisma__OrStatClient<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OrStats.
   * @param {OrStatDeleteManyArgs} args - Arguments to filter OrStats to delete.
   * @example
   * // Delete a few OrStats
   * const { count } = await prisma.orStat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrStatDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrStatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrStatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrStats
   * const orStat = await prisma.orStat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrStatUpdateManyArgs>(args: Prisma.SelectSubset<T, OrStatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrStats and returns the data updated in the database.
   * @param {OrStatUpdateManyAndReturnArgs} args - Arguments to update many OrStats.
   * @example
   * // Update many OrStats
   * const orStat = await prisma.orStat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OrStats and only return the `id`
   * const orStatWithIdOnly = await prisma.orStat.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OrStatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OrStatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OrStat.
   * @param {OrStatUpsertArgs} args - Arguments to update or create a OrStat.
   * @example
   * // Update or create a OrStat
   * const orStat = await prisma.orStat.upsert({
   *   create: {
   *     // ... data to create a OrStat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrStat we want to update
   *   }
   * })
   */
  upsert<T extends OrStatUpsertArgs>(args: Prisma.SelectSubset<T, OrStatUpsertArgs<ExtArgs>>): Prisma.Prisma__OrStatClient<runtime.Types.Result.GetResult<Prisma.$OrStatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OrStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrStatCountArgs} args - Arguments to filter OrStats to count.
   * @example
   * // Count the number of OrStats
   * const count = await prisma.orStat.count({
   *   where: {
   *     // ... the filter for the OrStats we want to count
   *   }
   * })
  **/
  count<T extends OrStatCountArgs>(
    args?: Prisma.Subset<T, OrStatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrStatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OrStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrStatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrStatAggregateArgs>(args: Prisma.Subset<T, OrStatAggregateArgs>): Prisma.PrismaPromise<GetOrStatAggregateType<T>>

  /**
   * Group by OrStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrStatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrStatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrStatGroupByArgs['orderBy'] }
      : { orderBy?: OrStatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrStatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrStatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OrStat model
 */
readonly fields: OrStatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OrStat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrStatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  hospital<T extends Prisma.HospitalDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HospitalDefaultArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OrStat model
 */
export interface OrStatFieldRefs {
  readonly id: Prisma.FieldRef<"OrStat", 'String'>
  readonly hospitalId: Prisma.FieldRef<"OrStat", 'String'>
  readonly totalRooms: Prisma.FieldRef<"OrStat", 'Int'>
  readonly activeSurgeries: Prisma.FieldRef<"OrStat", 'Int'>
  readonly scheduledToday: Prisma.FieldRef<"OrStat", 'Int'>
  readonly emergencyCases: Prisma.FieldRef<"OrStat", 'Int'>
  readonly availableRooms: Prisma.FieldRef<"OrStat", 'Int'>
}
    

// Custom InputTypes
/**
 * OrStat findUnique
 */
export type OrStatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatInclude<ExtArgs> | null
  /**
   * Filter, which OrStat to fetch.
   */
  where: Prisma.OrStatWhereUniqueInput
}

/**
 * OrStat findUniqueOrThrow
 */
export type OrStatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatInclude<ExtArgs> | null
  /**
   * Filter, which OrStat to fetch.
   */
  where: Prisma.OrStatWhereUniqueInput
}

/**
 * OrStat findFirst
 */
export type OrStatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatInclude<ExtArgs> | null
  /**
   * Filter, which OrStat to fetch.
   */
  where?: Prisma.OrStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrStats to fetch.
   */
  orderBy?: Prisma.OrStatOrderByWithRelationInput | Prisma.OrStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrStats.
   */
  cursor?: Prisma.OrStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrStats.
   */
  distinct?: Prisma.OrStatScalarFieldEnum | Prisma.OrStatScalarFieldEnum[]
}

/**
 * OrStat findFirstOrThrow
 */
export type OrStatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatInclude<ExtArgs> | null
  /**
   * Filter, which OrStat to fetch.
   */
  where?: Prisma.OrStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrStats to fetch.
   */
  orderBy?: Prisma.OrStatOrderByWithRelationInput | Prisma.OrStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrStats.
   */
  cursor?: Prisma.OrStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrStats.
   */
  distinct?: Prisma.OrStatScalarFieldEnum | Prisma.OrStatScalarFieldEnum[]
}

/**
 * OrStat findMany
 */
export type OrStatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatInclude<ExtArgs> | null
  /**
   * Filter, which OrStats to fetch.
   */
  where?: Prisma.OrStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrStats to fetch.
   */
  orderBy?: Prisma.OrStatOrderByWithRelationInput | Prisma.OrStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OrStats.
   */
  cursor?: Prisma.OrStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrStats.
   */
  skip?: number
  distinct?: Prisma.OrStatScalarFieldEnum | Prisma.OrStatScalarFieldEnum[]
}

/**
 * OrStat create
 */
export type OrStatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatInclude<ExtArgs> | null
  /**
   * The data needed to create a OrStat.
   */
  data: Prisma.XOR<Prisma.OrStatCreateInput, Prisma.OrStatUncheckedCreateInput>
}

/**
 * OrStat createMany
 */
export type OrStatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OrStats.
   */
  data: Prisma.OrStatCreateManyInput | Prisma.OrStatCreateManyInput[]
}

/**
 * OrStat createManyAndReturn
 */
export type OrStatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * The data used to create many OrStats.
   */
  data: Prisma.OrStatCreateManyInput | Prisma.OrStatCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OrStat update
 */
export type OrStatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatInclude<ExtArgs> | null
  /**
   * The data needed to update a OrStat.
   */
  data: Prisma.XOR<Prisma.OrStatUpdateInput, Prisma.OrStatUncheckedUpdateInput>
  /**
   * Choose, which OrStat to update.
   */
  where: Prisma.OrStatWhereUniqueInput
}

/**
 * OrStat updateMany
 */
export type OrStatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OrStats.
   */
  data: Prisma.XOR<Prisma.OrStatUpdateManyMutationInput, Prisma.OrStatUncheckedUpdateManyInput>
  /**
   * Filter which OrStats to update
   */
  where?: Prisma.OrStatWhereInput
  /**
   * Limit how many OrStats to update.
   */
  limit?: number
}

/**
 * OrStat updateManyAndReturn
 */
export type OrStatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * The data used to update OrStats.
   */
  data: Prisma.XOR<Prisma.OrStatUpdateManyMutationInput, Prisma.OrStatUncheckedUpdateManyInput>
  /**
   * Filter which OrStats to update
   */
  where?: Prisma.OrStatWhereInput
  /**
   * Limit how many OrStats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OrStat upsert
 */
export type OrStatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatInclude<ExtArgs> | null
  /**
   * The filter to search for the OrStat to update in case it exists.
   */
  where: Prisma.OrStatWhereUniqueInput
  /**
   * In case the OrStat found by the `where` argument doesn't exist, create a new OrStat with this data.
   */
  create: Prisma.XOR<Prisma.OrStatCreateInput, Prisma.OrStatUncheckedCreateInput>
  /**
   * In case the OrStat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrStatUpdateInput, Prisma.OrStatUncheckedUpdateInput>
}

/**
 * OrStat delete
 */
export type OrStatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatInclude<ExtArgs> | null
  /**
   * Filter which OrStat to delete.
   */
  where: Prisma.OrStatWhereUniqueInput
}

/**
 * OrStat deleteMany
 */
export type OrStatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrStats to delete
   */
  where?: Prisma.OrStatWhereInput
  /**
   * Limit how many OrStats to delete.
   */
  limit?: number
}

/**
 * OrStat without action
 */
export type OrStatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrStat
   */
  select?: Prisma.OrStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrStat
   */
  omit?: Prisma.OrStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrStatInclude<ExtArgs> | null
}
