
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VisitCount` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model VisitCount
 * 
 */
export type VisitCountModel = runtime.Types.Result.DefaultSelection<Prisma.$VisitCountPayload>

export type AggregateVisitCount = {
  _count: VisitCountCountAggregateOutputType | null
  _avg: VisitCountAvgAggregateOutputType | null
  _sum: VisitCountSumAggregateOutputType | null
  _min: VisitCountMinAggregateOutputType | null
  _max: VisitCountMaxAggregateOutputType | null
}

export type VisitCountAvgAggregateOutputType = {
  count: number | null
}

export type VisitCountSumAggregateOutputType = {
  count: number | null
}

export type VisitCountMinAggregateOutputType = {
  id: string | null
  hospitalId: string | null
  date: string | null
  dayName: string | null
  count: number | null
}

export type VisitCountMaxAggregateOutputType = {
  id: string | null
  hospitalId: string | null
  date: string | null
  dayName: string | null
  count: number | null
}

export type VisitCountCountAggregateOutputType = {
  id: number
  hospitalId: number
  date: number
  dayName: number
  count: number
  _all: number
}


export type VisitCountAvgAggregateInputType = {
  count?: true
}

export type VisitCountSumAggregateInputType = {
  count?: true
}

export type VisitCountMinAggregateInputType = {
  id?: true
  hospitalId?: true
  date?: true
  dayName?: true
  count?: true
}

export type VisitCountMaxAggregateInputType = {
  id?: true
  hospitalId?: true
  date?: true
  dayName?: true
  count?: true
}

export type VisitCountCountAggregateInputType = {
  id?: true
  hospitalId?: true
  date?: true
  dayName?: true
  count?: true
  _all?: true
}

export type VisitCountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VisitCount to aggregate.
   */
  where?: Prisma.VisitCountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VisitCounts to fetch.
   */
  orderBy?: Prisma.VisitCountOrderByWithRelationInput | Prisma.VisitCountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VisitCountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VisitCounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VisitCounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VisitCounts
  **/
  _count?: true | VisitCountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VisitCountAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VisitCountSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VisitCountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VisitCountMaxAggregateInputType
}

export type GetVisitCountAggregateType<T extends VisitCountAggregateArgs> = {
      [P in keyof T & keyof AggregateVisitCount]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVisitCount[P]>
    : Prisma.GetScalarType<T[P], AggregateVisitCount[P]>
}




export type VisitCountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VisitCountWhereInput
  orderBy?: Prisma.VisitCountOrderByWithAggregationInput | Prisma.VisitCountOrderByWithAggregationInput[]
  by: Prisma.VisitCountScalarFieldEnum[] | Prisma.VisitCountScalarFieldEnum
  having?: Prisma.VisitCountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VisitCountCountAggregateInputType | true
  _avg?: VisitCountAvgAggregateInputType
  _sum?: VisitCountSumAggregateInputType
  _min?: VisitCountMinAggregateInputType
  _max?: VisitCountMaxAggregateInputType
}

export type VisitCountGroupByOutputType = {
  id: string
  hospitalId: string
  date: string
  dayName: string
  count: number
  _count: VisitCountCountAggregateOutputType | null
  _avg: VisitCountAvgAggregateOutputType | null
  _sum: VisitCountSumAggregateOutputType | null
  _min: VisitCountMinAggregateOutputType | null
  _max: VisitCountMaxAggregateOutputType | null
}

type GetVisitCountGroupByPayload<T extends VisitCountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VisitCountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VisitCountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VisitCountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VisitCountGroupByOutputType[P]>
      }
    >
  >



export type VisitCountWhereInput = {
  AND?: Prisma.VisitCountWhereInput | Prisma.VisitCountWhereInput[]
  OR?: Prisma.VisitCountWhereInput[]
  NOT?: Prisma.VisitCountWhereInput | Prisma.VisitCountWhereInput[]
  id?: Prisma.StringFilter<"VisitCount"> | string
  hospitalId?: Prisma.StringFilter<"VisitCount"> | string
  date?: Prisma.StringFilter<"VisitCount"> | string
  dayName?: Prisma.StringFilter<"VisitCount"> | string
  count?: Prisma.IntFilter<"VisitCount"> | number
  hospital?: Prisma.XOR<Prisma.HospitalScalarRelationFilter, Prisma.HospitalWhereInput>
}

export type VisitCountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dayName?: Prisma.SortOrder
  count?: Prisma.SortOrder
  hospital?: Prisma.HospitalOrderByWithRelationInput
}

export type VisitCountWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VisitCountWhereInput | Prisma.VisitCountWhereInput[]
  OR?: Prisma.VisitCountWhereInput[]
  NOT?: Prisma.VisitCountWhereInput | Prisma.VisitCountWhereInput[]
  hospitalId?: Prisma.StringFilter<"VisitCount"> | string
  date?: Prisma.StringFilter<"VisitCount"> | string
  dayName?: Prisma.StringFilter<"VisitCount"> | string
  count?: Prisma.IntFilter<"VisitCount"> | number
  hospital?: Prisma.XOR<Prisma.HospitalScalarRelationFilter, Prisma.HospitalWhereInput>
}, "id">

export type VisitCountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dayName?: Prisma.SortOrder
  count?: Prisma.SortOrder
  _count?: Prisma.VisitCountCountOrderByAggregateInput
  _avg?: Prisma.VisitCountAvgOrderByAggregateInput
  _max?: Prisma.VisitCountMaxOrderByAggregateInput
  _min?: Prisma.VisitCountMinOrderByAggregateInput
  _sum?: Prisma.VisitCountSumOrderByAggregateInput
}

export type VisitCountScalarWhereWithAggregatesInput = {
  AND?: Prisma.VisitCountScalarWhereWithAggregatesInput | Prisma.VisitCountScalarWhereWithAggregatesInput[]
  OR?: Prisma.VisitCountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VisitCountScalarWhereWithAggregatesInput | Prisma.VisitCountScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VisitCount"> | string
  hospitalId?: Prisma.StringWithAggregatesFilter<"VisitCount"> | string
  date?: Prisma.StringWithAggregatesFilter<"VisitCount"> | string
  dayName?: Prisma.StringWithAggregatesFilter<"VisitCount"> | string
  count?: Prisma.IntWithAggregatesFilter<"VisitCount"> | number
}

export type VisitCountCreateInput = {
  id?: string
  date: string
  dayName: string
  count: number
  hospital: Prisma.HospitalCreateNestedOneWithoutVisitCountsInput
}

export type VisitCountUncheckedCreateInput = {
  id?: string
  hospitalId: string
  date: string
  dayName: string
  count: number
}

export type VisitCountUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
  hospital?: Prisma.HospitalUpdateOneRequiredWithoutVisitCountsNestedInput
}

export type VisitCountUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hospitalId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
}

export type VisitCountCreateManyInput = {
  id?: string
  hospitalId: string
  date: string
  dayName: string
  count: number
}

export type VisitCountUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
}

export type VisitCountUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  hospitalId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
}

export type VisitCountListRelationFilter = {
  every?: Prisma.VisitCountWhereInput
  some?: Prisma.VisitCountWhereInput
  none?: Prisma.VisitCountWhereInput
}

export type VisitCountOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VisitCountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dayName?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type VisitCountAvgOrderByAggregateInput = {
  count?: Prisma.SortOrder
}

export type VisitCountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dayName?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type VisitCountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  hospitalId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  dayName?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type VisitCountSumOrderByAggregateInput = {
  count?: Prisma.SortOrder
}

export type VisitCountCreateNestedManyWithoutHospitalInput = {
  create?: Prisma.XOR<Prisma.VisitCountCreateWithoutHospitalInput, Prisma.VisitCountUncheckedCreateWithoutHospitalInput> | Prisma.VisitCountCreateWithoutHospitalInput[] | Prisma.VisitCountUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.VisitCountCreateOrConnectWithoutHospitalInput | Prisma.VisitCountCreateOrConnectWithoutHospitalInput[]
  createMany?: Prisma.VisitCountCreateManyHospitalInputEnvelope
  connect?: Prisma.VisitCountWhereUniqueInput | Prisma.VisitCountWhereUniqueInput[]
}

export type VisitCountUncheckedCreateNestedManyWithoutHospitalInput = {
  create?: Prisma.XOR<Prisma.VisitCountCreateWithoutHospitalInput, Prisma.VisitCountUncheckedCreateWithoutHospitalInput> | Prisma.VisitCountCreateWithoutHospitalInput[] | Prisma.VisitCountUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.VisitCountCreateOrConnectWithoutHospitalInput | Prisma.VisitCountCreateOrConnectWithoutHospitalInput[]
  createMany?: Prisma.VisitCountCreateManyHospitalInputEnvelope
  connect?: Prisma.VisitCountWhereUniqueInput | Prisma.VisitCountWhereUniqueInput[]
}

export type VisitCountUpdateManyWithoutHospitalNestedInput = {
  create?: Prisma.XOR<Prisma.VisitCountCreateWithoutHospitalInput, Prisma.VisitCountUncheckedCreateWithoutHospitalInput> | Prisma.VisitCountCreateWithoutHospitalInput[] | Prisma.VisitCountUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.VisitCountCreateOrConnectWithoutHospitalInput | Prisma.VisitCountCreateOrConnectWithoutHospitalInput[]
  upsert?: Prisma.VisitCountUpsertWithWhereUniqueWithoutHospitalInput | Prisma.VisitCountUpsertWithWhereUniqueWithoutHospitalInput[]
  createMany?: Prisma.VisitCountCreateManyHospitalInputEnvelope
  set?: Prisma.VisitCountWhereUniqueInput | Prisma.VisitCountWhereUniqueInput[]
  disconnect?: Prisma.VisitCountWhereUniqueInput | Prisma.VisitCountWhereUniqueInput[]
  delete?: Prisma.VisitCountWhereUniqueInput | Prisma.VisitCountWhereUniqueInput[]
  connect?: Prisma.VisitCountWhereUniqueInput | Prisma.VisitCountWhereUniqueInput[]
  update?: Prisma.VisitCountUpdateWithWhereUniqueWithoutHospitalInput | Prisma.VisitCountUpdateWithWhereUniqueWithoutHospitalInput[]
  updateMany?: Prisma.VisitCountUpdateManyWithWhereWithoutHospitalInput | Prisma.VisitCountUpdateManyWithWhereWithoutHospitalInput[]
  deleteMany?: Prisma.VisitCountScalarWhereInput | Prisma.VisitCountScalarWhereInput[]
}

export type VisitCountUncheckedUpdateManyWithoutHospitalNestedInput = {
  create?: Prisma.XOR<Prisma.VisitCountCreateWithoutHospitalInput, Prisma.VisitCountUncheckedCreateWithoutHospitalInput> | Prisma.VisitCountCreateWithoutHospitalInput[] | Prisma.VisitCountUncheckedCreateWithoutHospitalInput[]
  connectOrCreate?: Prisma.VisitCountCreateOrConnectWithoutHospitalInput | Prisma.VisitCountCreateOrConnectWithoutHospitalInput[]
  upsert?: Prisma.VisitCountUpsertWithWhereUniqueWithoutHospitalInput | Prisma.VisitCountUpsertWithWhereUniqueWithoutHospitalInput[]
  createMany?: Prisma.VisitCountCreateManyHospitalInputEnvelope
  set?: Prisma.VisitCountWhereUniqueInput | Prisma.VisitCountWhereUniqueInput[]
  disconnect?: Prisma.VisitCountWhereUniqueInput | Prisma.VisitCountWhereUniqueInput[]
  delete?: Prisma.VisitCountWhereUniqueInput | Prisma.VisitCountWhereUniqueInput[]
  connect?: Prisma.VisitCountWhereUniqueInput | Prisma.VisitCountWhereUniqueInput[]
  update?: Prisma.VisitCountUpdateWithWhereUniqueWithoutHospitalInput | Prisma.VisitCountUpdateWithWhereUniqueWithoutHospitalInput[]
  updateMany?: Prisma.VisitCountUpdateManyWithWhereWithoutHospitalInput | Prisma.VisitCountUpdateManyWithWhereWithoutHospitalInput[]
  deleteMany?: Prisma.VisitCountScalarWhereInput | Prisma.VisitCountScalarWhereInput[]
}

export type VisitCountCreateWithoutHospitalInput = {
  id?: string
  date: string
  dayName: string
  count: number
}

export type VisitCountUncheckedCreateWithoutHospitalInput = {
  id?: string
  date: string
  dayName: string
  count: number
}

export type VisitCountCreateOrConnectWithoutHospitalInput = {
  where: Prisma.VisitCountWhereUniqueInput
  create: Prisma.XOR<Prisma.VisitCountCreateWithoutHospitalInput, Prisma.VisitCountUncheckedCreateWithoutHospitalInput>
}

export type VisitCountCreateManyHospitalInputEnvelope = {
  data: Prisma.VisitCountCreateManyHospitalInput | Prisma.VisitCountCreateManyHospitalInput[]
}

export type VisitCountUpsertWithWhereUniqueWithoutHospitalInput = {
  where: Prisma.VisitCountWhereUniqueInput
  update: Prisma.XOR<Prisma.VisitCountUpdateWithoutHospitalInput, Prisma.VisitCountUncheckedUpdateWithoutHospitalInput>
  create: Prisma.XOR<Prisma.VisitCountCreateWithoutHospitalInput, Prisma.VisitCountUncheckedCreateWithoutHospitalInput>
}

export type VisitCountUpdateWithWhereUniqueWithoutHospitalInput = {
  where: Prisma.VisitCountWhereUniqueInput
  data: Prisma.XOR<Prisma.VisitCountUpdateWithoutHospitalInput, Prisma.VisitCountUncheckedUpdateWithoutHospitalInput>
}

export type VisitCountUpdateManyWithWhereWithoutHospitalInput = {
  where: Prisma.VisitCountScalarWhereInput
  data: Prisma.XOR<Prisma.VisitCountUpdateManyMutationInput, Prisma.VisitCountUncheckedUpdateManyWithoutHospitalInput>
}

export type VisitCountScalarWhereInput = {
  AND?: Prisma.VisitCountScalarWhereInput | Prisma.VisitCountScalarWhereInput[]
  OR?: Prisma.VisitCountScalarWhereInput[]
  NOT?: Prisma.VisitCountScalarWhereInput | Prisma.VisitCountScalarWhereInput[]
  id?: Prisma.StringFilter<"VisitCount"> | string
  hospitalId?: Prisma.StringFilter<"VisitCount"> | string
  date?: Prisma.StringFilter<"VisitCount"> | string
  dayName?: Prisma.StringFilter<"VisitCount"> | string
  count?: Prisma.IntFilter<"VisitCount"> | number
}

export type VisitCountCreateManyHospitalInput = {
  id?: string
  date: string
  dayName: string
  count: number
}

export type VisitCountUpdateWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
}

export type VisitCountUncheckedUpdateWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
}

export type VisitCountUncheckedUpdateManyWithoutHospitalInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.StringFieldUpdateOperationsInput | string
  dayName?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.IntFieldUpdateOperationsInput | number
}



export type VisitCountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  date?: boolean
  dayName?: boolean
  count?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["visitCount"]>

export type VisitCountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  date?: boolean
  dayName?: boolean
  count?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["visitCount"]>

export type VisitCountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  hospitalId?: boolean
  date?: boolean
  dayName?: boolean
  count?: boolean
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}, ExtArgs["result"]["visitCount"]>

export type VisitCountSelectScalar = {
  id?: boolean
  hospitalId?: boolean
  date?: boolean
  dayName?: boolean
  count?: boolean
}

export type VisitCountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "hospitalId" | "date" | "dayName" | "count", ExtArgs["result"]["visitCount"]>
export type VisitCountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}
export type VisitCountIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}
export type VisitCountIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  hospital?: boolean | Prisma.HospitalDefaultArgs<ExtArgs>
}

export type $VisitCountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VisitCount"
  objects: {
    hospital: Prisma.$HospitalPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    hospitalId: string
    date: string
    dayName: string
    count: number
  }, ExtArgs["result"]["visitCount"]>
  composites: {}
}

export type VisitCountGetPayload<S extends boolean | null | undefined | VisitCountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VisitCountPayload, S>

export type VisitCountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VisitCountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VisitCountCountAggregateInputType | true
  }

export interface VisitCountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VisitCount'], meta: { name: 'VisitCount' } }
  /**
   * Find zero or one VisitCount that matches the filter.
   * @param {VisitCountFindUniqueArgs} args - Arguments to find a VisitCount
   * @example
   * // Get one VisitCount
   * const visitCount = await prisma.visitCount.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VisitCountFindUniqueArgs>(args: Prisma.SelectSubset<T, VisitCountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VisitCountClient<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VisitCount that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VisitCountFindUniqueOrThrowArgs} args - Arguments to find a VisitCount
   * @example
   * // Get one VisitCount
   * const visitCount = await prisma.visitCount.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VisitCountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VisitCountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VisitCountClient<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VisitCount that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VisitCountFindFirstArgs} args - Arguments to find a VisitCount
   * @example
   * // Get one VisitCount
   * const visitCount = await prisma.visitCount.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VisitCountFindFirstArgs>(args?: Prisma.SelectSubset<T, VisitCountFindFirstArgs<ExtArgs>>): Prisma.Prisma__VisitCountClient<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VisitCount that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VisitCountFindFirstOrThrowArgs} args - Arguments to find a VisitCount
   * @example
   * // Get one VisitCount
   * const visitCount = await prisma.visitCount.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VisitCountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VisitCountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VisitCountClient<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VisitCounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VisitCountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VisitCounts
   * const visitCounts = await prisma.visitCount.findMany()
   * 
   * // Get first 10 VisitCounts
   * const visitCounts = await prisma.visitCount.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const visitCountWithIdOnly = await prisma.visitCount.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VisitCountFindManyArgs>(args?: Prisma.SelectSubset<T, VisitCountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VisitCount.
   * @param {VisitCountCreateArgs} args - Arguments to create a VisitCount.
   * @example
   * // Create one VisitCount
   * const VisitCount = await prisma.visitCount.create({
   *   data: {
   *     // ... data to create a VisitCount
   *   }
   * })
   * 
   */
  create<T extends VisitCountCreateArgs>(args: Prisma.SelectSubset<T, VisitCountCreateArgs<ExtArgs>>): Prisma.Prisma__VisitCountClient<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VisitCounts.
   * @param {VisitCountCreateManyArgs} args - Arguments to create many VisitCounts.
   * @example
   * // Create many VisitCounts
   * const visitCount = await prisma.visitCount.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VisitCountCreateManyArgs>(args?: Prisma.SelectSubset<T, VisitCountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VisitCounts and returns the data saved in the database.
   * @param {VisitCountCreateManyAndReturnArgs} args - Arguments to create many VisitCounts.
   * @example
   * // Create many VisitCounts
   * const visitCount = await prisma.visitCount.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VisitCounts and only return the `id`
   * const visitCountWithIdOnly = await prisma.visitCount.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VisitCountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VisitCountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VisitCount.
   * @param {VisitCountDeleteArgs} args - Arguments to delete one VisitCount.
   * @example
   * // Delete one VisitCount
   * const VisitCount = await prisma.visitCount.delete({
   *   where: {
   *     // ... filter to delete one VisitCount
   *   }
   * })
   * 
   */
  delete<T extends VisitCountDeleteArgs>(args: Prisma.SelectSubset<T, VisitCountDeleteArgs<ExtArgs>>): Prisma.Prisma__VisitCountClient<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VisitCount.
   * @param {VisitCountUpdateArgs} args - Arguments to update one VisitCount.
   * @example
   * // Update one VisitCount
   * const visitCount = await prisma.visitCount.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VisitCountUpdateArgs>(args: Prisma.SelectSubset<T, VisitCountUpdateArgs<ExtArgs>>): Prisma.Prisma__VisitCountClient<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VisitCounts.
   * @param {VisitCountDeleteManyArgs} args - Arguments to filter VisitCounts to delete.
   * @example
   * // Delete a few VisitCounts
   * const { count } = await prisma.visitCount.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VisitCountDeleteManyArgs>(args?: Prisma.SelectSubset<T, VisitCountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VisitCounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VisitCountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VisitCounts
   * const visitCount = await prisma.visitCount.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VisitCountUpdateManyArgs>(args: Prisma.SelectSubset<T, VisitCountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VisitCounts and returns the data updated in the database.
   * @param {VisitCountUpdateManyAndReturnArgs} args - Arguments to update many VisitCounts.
   * @example
   * // Update many VisitCounts
   * const visitCount = await prisma.visitCount.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VisitCounts and only return the `id`
   * const visitCountWithIdOnly = await prisma.visitCount.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VisitCountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VisitCountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VisitCount.
   * @param {VisitCountUpsertArgs} args - Arguments to update or create a VisitCount.
   * @example
   * // Update or create a VisitCount
   * const visitCount = await prisma.visitCount.upsert({
   *   create: {
   *     // ... data to create a VisitCount
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VisitCount we want to update
   *   }
   * })
   */
  upsert<T extends VisitCountUpsertArgs>(args: Prisma.SelectSubset<T, VisitCountUpsertArgs<ExtArgs>>): Prisma.Prisma__VisitCountClient<runtime.Types.Result.GetResult<Prisma.$VisitCountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VisitCounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VisitCountCountArgs} args - Arguments to filter VisitCounts to count.
   * @example
   * // Count the number of VisitCounts
   * const count = await prisma.visitCount.count({
   *   where: {
   *     // ... the filter for the VisitCounts we want to count
   *   }
   * })
  **/
  count<T extends VisitCountCountArgs>(
    args?: Prisma.Subset<T, VisitCountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VisitCountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VisitCount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VisitCountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VisitCountAggregateArgs>(args: Prisma.Subset<T, VisitCountAggregateArgs>): Prisma.PrismaPromise<GetVisitCountAggregateType<T>>

  /**
   * Group by VisitCount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VisitCountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VisitCountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VisitCountGroupByArgs['orderBy'] }
      : { orderBy?: VisitCountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VisitCountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVisitCountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VisitCount model
 */
readonly fields: VisitCountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VisitCount.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VisitCountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  hospital<T extends Prisma.HospitalDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HospitalDefaultArgs<ExtArgs>>): Prisma.Prisma__HospitalClient<runtime.Types.Result.GetResult<Prisma.$HospitalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VisitCount model
 */
export interface VisitCountFieldRefs {
  readonly id: Prisma.FieldRef<"VisitCount", 'String'>
  readonly hospitalId: Prisma.FieldRef<"VisitCount", 'String'>
  readonly date: Prisma.FieldRef<"VisitCount", 'String'>
  readonly dayName: Prisma.FieldRef<"VisitCount", 'String'>
  readonly count: Prisma.FieldRef<"VisitCount", 'Int'>
}
    

// Custom InputTypes
/**
 * VisitCount findUnique
 */
export type VisitCountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountInclude<ExtArgs> | null
  /**
   * Filter, which VisitCount to fetch.
   */
  where: Prisma.VisitCountWhereUniqueInput
}

/**
 * VisitCount findUniqueOrThrow
 */
export type VisitCountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountInclude<ExtArgs> | null
  /**
   * Filter, which VisitCount to fetch.
   */
  where: Prisma.VisitCountWhereUniqueInput
}

/**
 * VisitCount findFirst
 */
export type VisitCountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountInclude<ExtArgs> | null
  /**
   * Filter, which VisitCount to fetch.
   */
  where?: Prisma.VisitCountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VisitCounts to fetch.
   */
  orderBy?: Prisma.VisitCountOrderByWithRelationInput | Prisma.VisitCountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VisitCounts.
   */
  cursor?: Prisma.VisitCountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VisitCounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VisitCounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VisitCounts.
   */
  distinct?: Prisma.VisitCountScalarFieldEnum | Prisma.VisitCountScalarFieldEnum[]
}

/**
 * VisitCount findFirstOrThrow
 */
export type VisitCountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountInclude<ExtArgs> | null
  /**
   * Filter, which VisitCount to fetch.
   */
  where?: Prisma.VisitCountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VisitCounts to fetch.
   */
  orderBy?: Prisma.VisitCountOrderByWithRelationInput | Prisma.VisitCountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VisitCounts.
   */
  cursor?: Prisma.VisitCountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VisitCounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VisitCounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VisitCounts.
   */
  distinct?: Prisma.VisitCountScalarFieldEnum | Prisma.VisitCountScalarFieldEnum[]
}

/**
 * VisitCount findMany
 */
export type VisitCountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountInclude<ExtArgs> | null
  /**
   * Filter, which VisitCounts to fetch.
   */
  where?: Prisma.VisitCountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VisitCounts to fetch.
   */
  orderBy?: Prisma.VisitCountOrderByWithRelationInput | Prisma.VisitCountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VisitCounts.
   */
  cursor?: Prisma.VisitCountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VisitCounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VisitCounts.
   */
  skip?: number
  distinct?: Prisma.VisitCountScalarFieldEnum | Prisma.VisitCountScalarFieldEnum[]
}

/**
 * VisitCount create
 */
export type VisitCountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountInclude<ExtArgs> | null
  /**
   * The data needed to create a VisitCount.
   */
  data: Prisma.XOR<Prisma.VisitCountCreateInput, Prisma.VisitCountUncheckedCreateInput>
}

/**
 * VisitCount createMany
 */
export type VisitCountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VisitCounts.
   */
  data: Prisma.VisitCountCreateManyInput | Prisma.VisitCountCreateManyInput[]
}

/**
 * VisitCount createManyAndReturn
 */
export type VisitCountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * The data used to create many VisitCounts.
   */
  data: Prisma.VisitCountCreateManyInput | Prisma.VisitCountCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * VisitCount update
 */
export type VisitCountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountInclude<ExtArgs> | null
  /**
   * The data needed to update a VisitCount.
   */
  data: Prisma.XOR<Prisma.VisitCountUpdateInput, Prisma.VisitCountUncheckedUpdateInput>
  /**
   * Choose, which VisitCount to update.
   */
  where: Prisma.VisitCountWhereUniqueInput
}

/**
 * VisitCount updateMany
 */
export type VisitCountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VisitCounts.
   */
  data: Prisma.XOR<Prisma.VisitCountUpdateManyMutationInput, Prisma.VisitCountUncheckedUpdateManyInput>
  /**
   * Filter which VisitCounts to update
   */
  where?: Prisma.VisitCountWhereInput
  /**
   * Limit how many VisitCounts to update.
   */
  limit?: number
}

/**
 * VisitCount updateManyAndReturn
 */
export type VisitCountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * The data used to update VisitCounts.
   */
  data: Prisma.XOR<Prisma.VisitCountUpdateManyMutationInput, Prisma.VisitCountUncheckedUpdateManyInput>
  /**
   * Filter which VisitCounts to update
   */
  where?: Prisma.VisitCountWhereInput
  /**
   * Limit how many VisitCounts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * VisitCount upsert
 */
export type VisitCountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountInclude<ExtArgs> | null
  /**
   * The filter to search for the VisitCount to update in case it exists.
   */
  where: Prisma.VisitCountWhereUniqueInput
  /**
   * In case the VisitCount found by the `where` argument doesn't exist, create a new VisitCount with this data.
   */
  create: Prisma.XOR<Prisma.VisitCountCreateInput, Prisma.VisitCountUncheckedCreateInput>
  /**
   * In case the VisitCount was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VisitCountUpdateInput, Prisma.VisitCountUncheckedUpdateInput>
}

/**
 * VisitCount delete
 */
export type VisitCountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountInclude<ExtArgs> | null
  /**
   * Filter which VisitCount to delete.
   */
  where: Prisma.VisitCountWhereUniqueInput
}

/**
 * VisitCount deleteMany
 */
export type VisitCountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VisitCounts to delete
   */
  where?: Prisma.VisitCountWhereInput
  /**
   * Limit how many VisitCounts to delete.
   */
  limit?: number
}

/**
 * VisitCount without action
 */
export type VisitCountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VisitCount
   */
  select?: Prisma.VisitCountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VisitCount
   */
  omit?: Prisma.VisitCountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VisitCountInclude<ExtArgs> | null
}
