
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const HospitalSizeLevel = {
  S: 'S',
  A: 'A',
  M1: 'M1',
  M2: 'M2',
  F1: 'F1',
  F2: 'F2',
  F3: 'F3',
  P: 'P'
} as const

export type HospitalSizeLevel = (typeof HospitalSizeLevel)[keyof typeof HospitalSizeLevel]


export const HospitalSapLevel = {
  S: 'S',
  S_PLUS: 'S_PLUS',
  A: 'A',
  A_PLUS: 'A_PLUS',
  P: 'P',
  P_PLUS: 'P_PLUS'
} as const

export type HospitalSapLevel = (typeof HospitalSapLevel)[keyof typeof HospitalSapLevel]


export const HospitalAffiliation = {
  MOPH: 'MOPH',
  LAO: 'LAO',
  MOD: 'MOD',
  UNIVERSITY: 'UNIVERSITY'
} as const

export type HospitalAffiliation = (typeof HospitalAffiliation)[keyof typeof HospitalAffiliation]
