
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Hospital.ts'
export type * from './models/LrStatus.ts'
export type * from './models/ICUWard.ts'
export type * from './models/IPDWard.ts'
export type * from './models/OrStat.ts'
export type * from './models/WaitingTime.ts'
export type * from './models/VisitCount.ts'
export type * from './commonInputTypes.ts'