
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import type * as Prisma from "./internal/prismaNamespace.ts"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type EnumHospitalSizeLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalSizeLevel | Prisma.EnumHospitalSizeLevelFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalSizeLevel[]
  notIn?: $Enums.HospitalSizeLevel[]
  not?: Prisma.NestedEnumHospitalSizeLevelFilter<$PrismaModel> | $Enums.HospitalSizeLevel
}

export type EnumHospitalSapLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalSapLevel | Prisma.EnumHospitalSapLevelFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalSapLevel[]
  notIn?: $Enums.HospitalSapLevel[]
  not?: Prisma.NestedEnumHospitalSapLevelFilter<$PrismaModel> | $Enums.HospitalSapLevel
}

export type EnumHospitalAffiliationFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalAffiliation | Prisma.EnumHospitalAffiliationFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalAffiliation[]
  notIn?: $Enums.HospitalAffiliation[]
  not?: Prisma.NestedEnumHospitalAffiliationFilter<$PrismaModel> | $Enums.HospitalAffiliation
}

export type FloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type EnumHospitalSizeLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalSizeLevel | Prisma.EnumHospitalSizeLevelFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalSizeLevel[]
  notIn?: $Enums.HospitalSizeLevel[]
  not?: Prisma.NestedEnumHospitalSizeLevelWithAggregatesFilter<$PrismaModel> | $Enums.HospitalSizeLevel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumHospitalSizeLevelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumHospitalSizeLevelFilter<$PrismaModel>
}

export type EnumHospitalSapLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalSapLevel | Prisma.EnumHospitalSapLevelFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalSapLevel[]
  notIn?: $Enums.HospitalSapLevel[]
  not?: Prisma.NestedEnumHospitalSapLevelWithAggregatesFilter<$PrismaModel> | $Enums.HospitalSapLevel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumHospitalSapLevelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumHospitalSapLevelFilter<$PrismaModel>
}

export type EnumHospitalAffiliationWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalAffiliation | Prisma.EnumHospitalAffiliationFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalAffiliation[]
  notIn?: $Enums.HospitalAffiliation[]
  not?: Prisma.NestedEnumHospitalAffiliationWithAggregatesFilter<$PrismaModel> | $Enums.HospitalAffiliation
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumHospitalAffiliationFilter<$PrismaModel>
  _max?: Prisma.NestedEnumHospitalAffiliationFilter<$PrismaModel>
}

export type FloatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _min?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _max?: Prisma.NestedFloatNullableFilter<$PrismaModel>
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedEnumHospitalSizeLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalSizeLevel | Prisma.EnumHospitalSizeLevelFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalSizeLevel[]
  notIn?: $Enums.HospitalSizeLevel[]
  not?: Prisma.NestedEnumHospitalSizeLevelFilter<$PrismaModel> | $Enums.HospitalSizeLevel
}

export type NestedEnumHospitalSapLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalSapLevel | Prisma.EnumHospitalSapLevelFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalSapLevel[]
  notIn?: $Enums.HospitalSapLevel[]
  not?: Prisma.NestedEnumHospitalSapLevelFilter<$PrismaModel> | $Enums.HospitalSapLevel
}

export type NestedEnumHospitalAffiliationFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalAffiliation | Prisma.EnumHospitalAffiliationFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalAffiliation[]
  notIn?: $Enums.HospitalAffiliation[]
  not?: Prisma.NestedEnumHospitalAffiliationFilter<$PrismaModel> | $Enums.HospitalAffiliation
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedEnumHospitalSizeLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalSizeLevel | Prisma.EnumHospitalSizeLevelFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalSizeLevel[]
  notIn?: $Enums.HospitalSizeLevel[]
  not?: Prisma.NestedEnumHospitalSizeLevelWithAggregatesFilter<$PrismaModel> | $Enums.HospitalSizeLevel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumHospitalSizeLevelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumHospitalSizeLevelFilter<$PrismaModel>
}

export type NestedEnumHospitalSapLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalSapLevel | Prisma.EnumHospitalSapLevelFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalSapLevel[]
  notIn?: $Enums.HospitalSapLevel[]
  not?: Prisma.NestedEnumHospitalSapLevelWithAggregatesFilter<$PrismaModel> | $Enums.HospitalSapLevel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumHospitalSapLevelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumHospitalSapLevelFilter<$PrismaModel>
}

export type NestedEnumHospitalAffiliationWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.HospitalAffiliation | Prisma.EnumHospitalAffiliationFieldRefInput<$PrismaModel>
  in?: $Enums.HospitalAffiliation[]
  notIn?: $Enums.HospitalAffiliation[]
  not?: Prisma.NestedEnumHospitalAffiliationWithAggregatesFilter<$PrismaModel> | $Enums.HospitalAffiliation
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumHospitalAffiliationFilter<$PrismaModel>
  _max?: Prisma.NestedEnumHospitalAffiliationFilter<$PrismaModel>
}

export type NestedFloatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _min?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _max?: Prisma.NestedFloatNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}


