
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Hospital: 'Hospital',
  LrStatus: 'LrStatus',
  ICUWard: 'ICUWard',
  IPDWard: 'IPDWard',
  OrStat: 'OrStat',
  WaitingTime: 'WaitingTime',
  VisitCount: 'VisitCount'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const HospitalScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  sizeLevel: 'sizeLevel',
  sapLevel: 'sapLevel',
  affiliation: 'affiliation',
  lat: 'lat',
  lng: 'lng'
} as const

export type HospitalScalarFieldEnum = (typeof HospitalScalarFieldEnum)[keyof typeof HospitalScalarFieldEnum]


export const LrStatusScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  waiting: 'waiting',
  normal: 'normal',
  abnormal: 'abnormal',
  miscarriage: 'miscarriage',
  notDelivered: 'notDelivered'
} as const

export type LrStatusScalarFieldEnum = (typeof LrStatusScalarFieldEnum)[keyof typeof LrStatusScalarFieldEnum]


export const ICUWardScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  name: 'name',
  totalBeds: 'totalBeds',
  usedBeds: 'usedBeds'
} as const

export type ICUWardScalarFieldEnum = (typeof ICUWardScalarFieldEnum)[keyof typeof ICUWardScalarFieldEnum]


export const IPDWardScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  name: 'name',
  totalBeds: 'totalBeds',
  usedBeds: 'usedBeds'
} as const

export type IPDWardScalarFieldEnum = (typeof IPDWardScalarFieldEnum)[keyof typeof IPDWardScalarFieldEnum]


export const OrStatScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  totalRooms: 'totalRooms',
  activeSurgeries: 'activeSurgeries',
  scheduledToday: 'scheduledToday',
  emergencyCases: 'emergencyCases',
  availableRooms: 'availableRooms'
} as const

export type OrStatScalarFieldEnum = (typeof OrStatScalarFieldEnum)[keyof typeof OrStatScalarFieldEnum]


export const WaitingTimeScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  date: 'date',
  dayName: 'dayName',
  minutes: 'minutes'
} as const

export type WaitingTimeScalarFieldEnum = (typeof WaitingTimeScalarFieldEnum)[keyof typeof WaitingTimeScalarFieldEnum]


export const VisitCountScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  date: 'date',
  dayName: 'dayName',
  count: 'count'
} as const

export type VisitCountScalarFieldEnum = (typeof VisitCountScalarFieldEnum)[keyof typeof VisitCountScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

