
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.ts"
import { type PrismaClient } from "./class.ts"

export type * from '../models.ts'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
export const prismaVersion: PrismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Hospital: 'Hospital',
  LrStatus: 'LrStatus',
  ICUWard: 'ICUWard',
  IPDWard: 'IPDWard',
  OrStat: 'OrStat',
  WaitingTime: 'WaitingTime',
  VisitCount: 'VisitCount'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "hospital" | "lrStatus" | "iCUWard" | "iPDWard" | "orStat" | "waitingTime" | "visitCount"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Hospital: {
      payload: Prisma.$HospitalPayload<ExtArgs>
      fields: Prisma.HospitalFieldRefs
      operations: {
        findUnique: {
          args: Prisma.HospitalFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HospitalPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.HospitalFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HospitalPayload>
        }
        findFirst: {
          args: Prisma.HospitalFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HospitalPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.HospitalFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HospitalPayload>
        }
        findMany: {
          args: Prisma.HospitalFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HospitalPayload>[]
        }
        create: {
          args: Prisma.HospitalCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HospitalPayload>
        }
        createMany: {
          args: Prisma.HospitalCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.HospitalCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HospitalPayload>[]
        }
        delete: {
          args: Prisma.HospitalDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HospitalPayload>
        }
        update: {
          args: Prisma.HospitalUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HospitalPayload>
        }
        deleteMany: {
          args: Prisma.HospitalDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.HospitalUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.HospitalUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HospitalPayload>[]
        }
        upsert: {
          args: Prisma.HospitalUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HospitalPayload>
        }
        aggregate: {
          args: Prisma.HospitalAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateHospital>
        }
        groupBy: {
          args: Prisma.HospitalGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.HospitalGroupByOutputType>[]
        }
        count: {
          args: Prisma.HospitalCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.HospitalCountAggregateOutputType> | number
        }
      }
    }
    LrStatus: {
      payload: Prisma.$LrStatusPayload<ExtArgs>
      fields: Prisma.LrStatusFieldRefs
      operations: {
        findUnique: {
          args: Prisma.LrStatusFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LrStatusPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.LrStatusFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LrStatusPayload>
        }
        findFirst: {
          args: Prisma.LrStatusFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LrStatusPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.LrStatusFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LrStatusPayload>
        }
        findMany: {
          args: Prisma.LrStatusFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LrStatusPayload>[]
        }
        create: {
          args: Prisma.LrStatusCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LrStatusPayload>
        }
        createMany: {
          args: Prisma.LrStatusCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.LrStatusCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LrStatusPayload>[]
        }
        delete: {
          args: Prisma.LrStatusDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LrStatusPayload>
        }
        update: {
          args: Prisma.LrStatusUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LrStatusPayload>
        }
        deleteMany: {
          args: Prisma.LrStatusDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.LrStatusUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.LrStatusUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LrStatusPayload>[]
        }
        upsert: {
          args: Prisma.LrStatusUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LrStatusPayload>
        }
        aggregate: {
          args: Prisma.LrStatusAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateLrStatus>
        }
        groupBy: {
          args: Prisma.LrStatusGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LrStatusGroupByOutputType>[]
        }
        count: {
          args: Prisma.LrStatusCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LrStatusCountAggregateOutputType> | number
        }
      }
    }
    ICUWard: {
      payload: Prisma.$ICUWardPayload<ExtArgs>
      fields: Prisma.ICUWardFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ICUWardFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ICUWardPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ICUWardFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ICUWardPayload>
        }
        findFirst: {
          args: Prisma.ICUWardFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ICUWardPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ICUWardFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ICUWardPayload>
        }
        findMany: {
          args: Prisma.ICUWardFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ICUWardPayload>[]
        }
        create: {
          args: Prisma.ICUWardCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ICUWardPayload>
        }
        createMany: {
          args: Prisma.ICUWardCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ICUWardCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ICUWardPayload>[]
        }
        delete: {
          args: Prisma.ICUWardDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ICUWardPayload>
        }
        update: {
          args: Prisma.ICUWardUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ICUWardPayload>
        }
        deleteMany: {
          args: Prisma.ICUWardDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ICUWardUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ICUWardUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ICUWardPayload>[]
        }
        upsert: {
          args: Prisma.ICUWardUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ICUWardPayload>
        }
        aggregate: {
          args: Prisma.ICUWardAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateICUWard>
        }
        groupBy: {
          args: Prisma.ICUWardGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ICUWardGroupByOutputType>[]
        }
        count: {
          args: Prisma.ICUWardCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ICUWardCountAggregateOutputType> | number
        }
      }
    }
    IPDWard: {
      payload: Prisma.$IPDWardPayload<ExtArgs>
      fields: Prisma.IPDWardFieldRefs
      operations: {
        findUnique: {
          args: Prisma.IPDWardFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IPDWardPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.IPDWardFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IPDWardPayload>
        }
        findFirst: {
          args: Prisma.IPDWardFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IPDWardPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.IPDWardFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IPDWardPayload>
        }
        findMany: {
          args: Prisma.IPDWardFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IPDWardPayload>[]
        }
        create: {
          args: Prisma.IPDWardCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IPDWardPayload>
        }
        createMany: {
          args: Prisma.IPDWardCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.IPDWardCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IPDWardPayload>[]
        }
        delete: {
          args: Prisma.IPDWardDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IPDWardPayload>
        }
        update: {
          args: Prisma.IPDWardUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IPDWardPayload>
        }
        deleteMany: {
          args: Prisma.IPDWardDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.IPDWardUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.IPDWardUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IPDWardPayload>[]
        }
        upsert: {
          args: Prisma.IPDWardUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IPDWardPayload>
        }
        aggregate: {
          args: Prisma.IPDWardAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateIPDWard>
        }
        groupBy: {
          args: Prisma.IPDWardGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IPDWardGroupByOutputType>[]
        }
        count: {
          args: Prisma.IPDWardCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IPDWardCountAggregateOutputType> | number
        }
      }
    }
    OrStat: {
      payload: Prisma.$OrStatPayload<ExtArgs>
      fields: Prisma.OrStatFieldRefs
      operations: {
        findUnique: {
          args: Prisma.OrStatFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrStatPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.OrStatFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrStatPayload>
        }
        findFirst: {
          args: Prisma.OrStatFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrStatPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.OrStatFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrStatPayload>
        }
        findMany: {
          args: Prisma.OrStatFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrStatPayload>[]
        }
        create: {
          args: Prisma.OrStatCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrStatPayload>
        }
        createMany: {
          args: Prisma.OrStatCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.OrStatCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrStatPayload>[]
        }
        delete: {
          args: Prisma.OrStatDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrStatPayload>
        }
        update: {
          args: Prisma.OrStatUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrStatPayload>
        }
        deleteMany: {
          args: Prisma.OrStatDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.OrStatUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.OrStatUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrStatPayload>[]
        }
        upsert: {
          args: Prisma.OrStatUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrStatPayload>
        }
        aggregate: {
          args: Prisma.OrStatAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateOrStat>
        }
        groupBy: {
          args: Prisma.OrStatGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OrStatGroupByOutputType>[]
        }
        count: {
          args: Prisma.OrStatCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OrStatCountAggregateOutputType> | number
        }
      }
    }
    WaitingTime: {
      payload: Prisma.$WaitingTimePayload<ExtArgs>
      fields: Prisma.WaitingTimeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.WaitingTimeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WaitingTimePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.WaitingTimeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WaitingTimePayload>
        }
        findFirst: {
          args: Prisma.WaitingTimeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WaitingTimePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.WaitingTimeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WaitingTimePayload>
        }
        findMany: {
          args: Prisma.WaitingTimeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WaitingTimePayload>[]
        }
        create: {
          args: Prisma.WaitingTimeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WaitingTimePayload>
        }
        createMany: {
          args: Prisma.WaitingTimeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.WaitingTimeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WaitingTimePayload>[]
        }
        delete: {
          args: Prisma.WaitingTimeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WaitingTimePayload>
        }
        update: {
          args: Prisma.WaitingTimeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WaitingTimePayload>
        }
        deleteMany: {
          args: Prisma.WaitingTimeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.WaitingTimeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.WaitingTimeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WaitingTimePayload>[]
        }
        upsert: {
          args: Prisma.WaitingTimeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WaitingTimePayload>
        }
        aggregate: {
          args: Prisma.WaitingTimeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWaitingTime>
        }
        groupBy: {
          args: Prisma.WaitingTimeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WaitingTimeGroupByOutputType>[]
        }
        count: {
          args: Prisma.WaitingTimeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WaitingTimeCountAggregateOutputType> | number
        }
      }
    }
    VisitCount: {
      payload: Prisma.$VisitCountPayload<ExtArgs>
      fields: Prisma.VisitCountFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VisitCountFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VisitCountPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VisitCountFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VisitCountPayload>
        }
        findFirst: {
          args: Prisma.VisitCountFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VisitCountPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VisitCountFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VisitCountPayload>
        }
        findMany: {
          args: Prisma.VisitCountFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VisitCountPayload>[]
        }
        create: {
          args: Prisma.VisitCountCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VisitCountPayload>
        }
        createMany: {
          args: Prisma.VisitCountCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VisitCountCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VisitCountPayload>[]
        }
        delete: {
          args: Prisma.VisitCountDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VisitCountPayload>
        }
        update: {
          args: Prisma.VisitCountUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VisitCountPayload>
        }
        deleteMany: {
          args: Prisma.VisitCountDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VisitCountUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VisitCountUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VisitCountPayload>[]
        }
        upsert: {
          args: Prisma.VisitCountUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VisitCountPayload>
        }
        aggregate: {
          args: Prisma.VisitCountAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVisitCount>
        }
        groupBy: {
          args: Prisma.VisitCountGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VisitCountGroupByOutputType>[]
        }
        count: {
          args: Prisma.VisitCountCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VisitCountCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const HospitalScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  sizeLevel: 'sizeLevel',
  sapLevel: 'sapLevel',
  affiliation: 'affiliation',
  lat: 'lat',
  lng: 'lng'
} as const

export type HospitalScalarFieldEnum = (typeof HospitalScalarFieldEnum)[keyof typeof HospitalScalarFieldEnum]


export const LrStatusScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  waiting: 'waiting',
  normal: 'normal',
  abnormal: 'abnormal',
  miscarriage: 'miscarriage',
  notDelivered: 'notDelivered'
} as const

export type LrStatusScalarFieldEnum = (typeof LrStatusScalarFieldEnum)[keyof typeof LrStatusScalarFieldEnum]


export const ICUWardScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  name: 'name',
  totalBeds: 'totalBeds',
  usedBeds: 'usedBeds'
} as const

export type ICUWardScalarFieldEnum = (typeof ICUWardScalarFieldEnum)[keyof typeof ICUWardScalarFieldEnum]


export const IPDWardScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  name: 'name',
  totalBeds: 'totalBeds',
  usedBeds: 'usedBeds'
} as const

export type IPDWardScalarFieldEnum = (typeof IPDWardScalarFieldEnum)[keyof typeof IPDWardScalarFieldEnum]


export const OrStatScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  totalRooms: 'totalRooms',
  activeSurgeries: 'activeSurgeries',
  scheduledToday: 'scheduledToday',
  emergencyCases: 'emergencyCases',
  availableRooms: 'availableRooms'
} as const

export type OrStatScalarFieldEnum = (typeof OrStatScalarFieldEnum)[keyof typeof OrStatScalarFieldEnum]


export const WaitingTimeScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  date: 'date',
  dayName: 'dayName',
  minutes: 'minutes'
} as const

export type WaitingTimeScalarFieldEnum = (typeof WaitingTimeScalarFieldEnum)[keyof typeof WaitingTimeScalarFieldEnum]


export const VisitCountScalarFieldEnum = {
  id: 'id',
  hospitalId: 'hospitalId',
  date: 'date',
  dayName: 'dayName',
  count: 'count'
} as const

export type VisitCountScalarFieldEnum = (typeof VisitCountScalarFieldEnum)[keyof typeof VisitCountScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'HospitalSizeLevel'
 */
export type EnumHospitalSizeLevelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'HospitalSizeLevel'>
    


/**
 * Reference to a field of type 'HospitalSapLevel'
 */
export type EnumHospitalSapLevelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'HospitalSapLevel'>
    


/**
 * Reference to a field of type 'HospitalAffiliation'
 */
export type EnumHospitalAffiliationFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'HospitalAffiliation'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  hospital?: Prisma.HospitalOmit
  lrStatus?: Prisma.LrStatusOmit
  iCUWard?: Prisma.ICUWardOmit
  iPDWard?: Prisma.IPDWardOmit
  orStat?: Prisma.OrStatOmit
  waitingTime?: Prisma.WaitingTimeOmit
  visitCount?: Prisma.VisitCountOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

